Lonesome Donator Piece Test
HaloSpaceStation/HaloSpaceStation13 pull request #1019
Opened 2019-01-02 07:52 UTC by Wehraboo

Basically what the title says, my first go at this.

- Added ODST donator armour "wehraboo", wasn't quite sure if I needed to make it a lonesome dmi or not, so I just threw it into the ODSTDonorPackage. 

- Edited the ODST config file to include said donator sprite. 

Should be able to help other donators if this goes well.

2019-01-02 09:18 UTC, caelaislinn requested changes

2019-01-02 09:18 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +/obj/item/clothing/head/helmet/odst/donator/wehraboo
I'm assuming the sprites are in ODSTDonorPackage.dmi? You'll need to set icon = that for the sprites to be correctly set

2019-01-02 09:18 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +/obj/item/clothing/suit/armor/special/odst/donator/wehraboo
set icon here as well

2019-01-02 09:54 UTC, Wehraboo commented on code/modules/halo/clothing/odst.dm
> +/obj/item/clothing/head/helmet/odst/donator/wehraboo
Little unsure how to correctly reference the right .dmi, looked at the other donator sets as an example but I'm still clueless on it.

2019-01-02 10:14 UTC, daPotato commented
Your helmet doesn't have a transparent state, my brain organ tells me the Toggle_VISR01 blah blah code is unneeded, Cael can confirm me on this, I don't understand the way it handles visor switch states and I'm just here because I am bored.

I thiiiink Cael's change requests should push the fixes to the issues to your PR, but I don't know how GitHub works so don't quote me on that either.

2019-01-03 00:53 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +/obj/item/clothing/head/helmet/odst/donator/wehraboo
I double checked the code and what you've done here is actually correct.

2019-01-03 00:53 UTC, caelaislinn approved these changes

2019-01-03 00:55 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +	. = ..()
Potato is right, there is no sprite for when the visor is open. This is all fine and I can merge as is if you want, but toggling the visor will not have any visual effect.

2019-01-03 03:36 UTC, Wehraboo commented on code/modules/halo/clothing/odst.dm
> +	. = ..()
Yeah, this particular bunch of sprites doesn't have an open variant, which's fine with me.

2019-01-03 03:43 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +	. = ..()
The visor toggle button is dead code then. I'll merge this now but come back and clean it up later; I think we still have some ODST donators outstanding

2019-01-03 03:43 UTC, merged