ODST Medic MedHud
HaloSpaceStation/HaloSpaceStation13 pull request #1021
Opened 2019-01-03 05:43 UTC by daPotato

Simply uncomments the code for ODST Medic's inbuilt helmet MedHud.

'Fuck knows why it was commented out in the first place.

2019-01-03 05:49 UTC, caelaislinn approved these changes

2019-01-03 05:50 UTC, caelaislinn requested changes

2019-01-03 05:50 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +/obj/item/clothing/head/helmet/odst/medic/health/process_hud(var/mob/M)
Compile error "code/modules/halo/clothing/odst.dm:187:error: process_hud: undefined proc"

2019-01-03 06:40 UTC, daPotato commented on code/modules/halo/clothing/odst.dm
> +/obj/item/clothing/head/helmet/odst/medic/health/process_hud(var/mob/M)
According to my Mexican outsource, 

"its because the process_hud proc only applies to glassses, not helmet obj's"

He says he will work on it more tomorrow.

2019-01-12 02:08 UTC, caelaislinn commented
Closed until you can fix the issues

2019-01-12 02:08 UTC, closed without merging