Donor Fix Mk III
HaloSpaceStation/HaloSpaceStation13 pull request #1079
Opened 2019-01-19 03:43 UTC by Wehraboo

Noticed my donor thingy isn't quite right still, though thanks to Max I might of been able to finally fix this buggery.

2019-01-19 20:37 UTC, caelaislinn requested changes

2019-01-19 20:37 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +    item_state = "wehraboo-suit_worn"
this indentation needs to be fixed

2019-01-20 05:08 UTC, Wehraboo commented on code/modules/halo/clothing/odst.dm
> +    item_state = "wehraboo-suit_worn"
How about now?

2019-01-20 05:26 UTC, caelaislinn approved these changes

2019-01-20 05:27 UTC, merged