Needle rifle. Hopefully now.
HaloSpaceStation/HaloSpaceStation13 pull request #1193
Opened 2019-01-31 12:07 UTC by mrturkeytoe

As the title suggests.
As of now the stats are as follow:
25 Damage
2 Accuracy (like the carbine)
21 Capacity
3 Shot super combine

2019-01-31 12:12 UTC, X0-11 requested changes

2019-01-31 12:12 UTC, X0-11 commented on code/modules/halo/weapons/covenant/ammo.dm
> +	caliber = "cov_carbine"
This needs a unique caliber

2019-01-31 12:12 UTC, X0-11 commented on code/modules/halo/weapons/covenant/ammo.dm
> +	caliber = "cov_carbine"
This should match the caliber of the ammo magazine

2019-01-31 12:12 UTC, X0-11 commented on code/modules/halo/weapons/covenant/ammo.dm
> +/obj/item/projectile/bullet/covenant/rifleneedle
This should be a subtype of the normal needler projectile to reduce duplication

2019-01-31 12:12 UTC, X0-11 commented on code/modules/halo/weapons/covenant/snipers.dm
> +	caliber = "cov_carbine"
This should have a unique caliber

2019-01-31 12:12 UTC, X0-11 commented on code/modules/halo/weapons/covenant/snipers.dm
> +/obj/item/weapon/gun/projectile/type31needlerifle/load_ammo(var/item/I,var/mob/user)
This shouldn't be here, it's special handling for the carbine only.

2019-01-31 12:12 UTC, X0-11 commented on code/modules/halo/weapons/covenant/snipers.dm
> +/obj/item/weapon/gun/projectile/type31needlerifle/unload_ammo(var/mob/user,var/allow_dump = 0)
Ditto.

2019-01-31 12:12 UTC, X0-11 commented on code/modules/halo/weapons/covenant/ammo.dm
> +obj/item/projectile/bullet/covenant/rifleneedle/attack_mob(var/mob/living/carbon/human/L)
This should be removed when the projectile is recoded into a subtype due to that projectile providing variables to customise these parameters in this way.

2019-02-01 00:11 UTC, mrturkeytoe commented on code/modules/halo/weapons/covenant/ammo.dm
> +	caliber = "cov_carbine"
How exactly do Calibers work?

2019-02-01 00:12 UTC, mrturkeytoe commented on code/modules/halo/weapons/covenant/ammo.dm
> +/obj/item/projectile/bullet/covenant/rifleneedle
And how do projectile subtypes work?

2019-02-01 00:25 UTC, mrturkeytoe commented on code/modules/halo/weapons/covenant/snipers.dm
> +/obj/item/weapon/gun/projectile/type31needlerifle/load_ammo(var/item/I,var/mob/user)
You mean the special reload behaviour?

2019-02-01 06:00 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/ammo.dm
> +	caliber = "cov_carbine"
Caliber is just a unique identifier for the ammo type. Rename it to the same thing as the needler ammo.

2019-02-01 06:01 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/ammo.dm
> +/obj/item/projectile/bullet/covenant/rifleneedle
They inhert procs and variables of the parent, allowing you to override specific members to customise aspects while minimising code duplication. Have a read up on inheritance tutorials in python or c#

2019-02-01 06:35 UTC, mrturkeytoe commented on code/modules/halo/weapons/covenant/ammo.dm
> +/obj/item/projectile/bullet/covenant/rifleneedle
Would it be done in a similar fashion to the relationship between plasma rifle and heavy plasma rifle?

2019-02-01 07:00 UTC, mrturkeytoe commented on code/modules/halo/weapons/covenant/ammo.dm
> +/obj/item/projectile/bullet/covenant/rifleneedle
Also if it's a subtype, wouldn't it display the unwanted homing feature? Or how would one go about making it not do that.

2019-02-03 00:18 UTC, X0-11 approved these changes

2019-02-03 17:31 UTC, merged