Permanent ship destruction system
HaloSpaceStation/HaloSpaceStation13 pull request #1299
Opened 2019-03-03 23:09 UTC by X0-11

Adds a system to allow for the permenant destruction of roundstart ships.
Ships require mapping to utilise the system: "Hull Segment" objects need to be added on-top of the inner walls of the ship.

2019-03-03 23:28 UTC, caelaislinn requested changes

2019-03-03 23:28 UTC, caelaislinn commented on code/modules/overmap/hull_segments.dm
> +	if(!isnull(om_obj))
You can just go `if(om_obj)`

2019-03-03 23:28 UTC, caelaislinn commented on code/modules/overmap/hull_segments.dm
> +	var/obj/effect/overmap/om_obj = map_sectors["[z]"]
Should this be in `Initialize()`? Where is map_sectors setup?

2019-03-03 23:28 UTC, caelaislinn commented on code/modules/overmap/sectors.dm
> +	return hull_strengths
This should just return a 0..1 scalar, not a 2d list.

2019-03-03 23:28 UTC, caelaislinn commented on code/modules/overmap/sectors.dm
> +		for(var/mob/player in GLOB.player_list)
Oof no, not in a process() loop. This is a hassle to do properly... but we need to track players on each overmap_object.

2019-03-03 23:28 UTC, caelaislinn commented on code/modules/overmap/sectors.dm
> +			to_world("An overmap object has been destroyed. Please wait as it is deleted.")
This may not be necessary. So long as `shipmap_handler.free_map` is properly optimised it can just chug away lightly in the background

2019-03-03 23:28 UTC, caelaislinn commented on code/modules/overmap/sectors.dm
> +			for(var/mob/mob in GLOB.mob_list)
Again, we should be tracking the players on this specific overmap_object

2019-03-04 09:25 UTC, X0-11 commented on code/modules/overmap/sectors.dm
> +			for(var/mob/mob in GLOB.mob_list)
mob_list will be changed to player_list.

2019-03-04 09:25 UTC, X0-11 commented on code/modules/overmap/sectors.dm
> +			to_world("An overmap object has been destroyed. Please wait as it is deleted.")
This is here more as a consistency thing. The ship-map loader and clearer already states that they are loading/clearing a map.

2019-03-04 09:25 UTC, X0-11 commented on code/modules/overmap/sectors.dm
> +		for(var/mob/player in GLOB.player_list)
player_list should always be relatively small, is tracking players really needed?

2019-03-04 09:25 UTC, X0-11 commented on code/modules/overmap/hull_segments.dm
> +	var/obj/effect/overmap/om_obj = map_sectors["[z]"]
Initialize would be better, Yes. I tend to forget that it exists.

2019-03-08 22:48 UTC, caelaislinn requested changes
Looking good. Just some last questions

2019-03-08 22:48 UTC, caelaislinn commented on code/modules/overmap/sectors.dm
> +		for(var/mob/player in GLOB.player_list)
At peak we get about 30 players. Some SS13 servers get 60-100 players. The average amount of crew on a ship is perhaps 3-10? 

Having a per ship player list will be very useful for other things such as radiation, space "sound", etc. 

I'd also suggest that line 178, which provides feedback to players on board about failing superstructure, not be done every process tick, perhaps a random delay of 2-5 seconds, and also some kind of audio cue be provided instead.

2019-03-08 22:48 UTC, caelaislinn commented on code/modules/overmap/sectors.dm
>  		src.icon_state="bombed"
Did you add "bombed" to icons/obj/overmap.dmi ? I can't find it

2019-03-08 22:48 UTC, caelaislinn commented on code/modules/overmap/ships/ship.dm
> +	GLOB.processing_objects += src
Was this a stylistic choice?

2019-03-08 23:25 UTC, X0-11 commented on code/modules/overmap/sectors.dm
> +		for(var/mob/player in GLOB.player_list)
Line 168 already checks for the superstructure_failing variable, which is set after announcing the superstructure's failure. This is to stop any potential spam of messages.

2019-03-08 23:26 UTC, X0-11 commented on code/modules/overmap/ships/ship.dm
> +	GLOB.processing_objects += src
I believe it was done when I was looking for a bug. I think most places in the code use += instead of .Add() though

2019-03-08 23:27 UTC, caelaislinn commented on code/modules/overmap/sectors.dm
> +		for(var/mob/player in GLOB.player_list)
Ah I see that now. This logic should probably be split up into a separate proc to get it out of process() for readability

2019-03-08 23:27 UTC, X0-11 commented on code/modules/overmap/sectors.dm
>  		src.icon_state="bombed"
I've not touched anything related to sector's process() besides adding a call to the parent.

2019-03-08 23:34 UTC, caelaislinn commented on code/modules/overmap/sectors.dm
>  		src.icon_state="bombed"
Ah this might be old overmap damage code then. I did a quick check and `/obj/item/projectile/overmap/on_impact(var/atom/impacted)` in code\modules\halo\machinery\overmap_projectile.dm uses var/hit. 

But then I did a check and I can't see hull_strength being reduced by damage anywhere. Can you tie this into damage code?

2019-03-12 00:34 UTC, BDpuffy420 approved these changes

2019-03-18 04:54 UTC, caelaislinn approved these changes
Here we go boys

2019-03-18 05:05 UTC, caelaislinn requested changes
Something is terribly wrong with travis

2019-03-18 05:22 UTC, caelaislinn commented
Merge https://github.com/X0-11/HaloSpaceStation13/pull/1 first

2019-03-18 14:18 UTC, caelaislinn commented
#1223

2019-03-19 07:42 UTC, caelaislinn commented on code/game/jobs/job_controller.dm
> +				continue
These and a bunch of other files shouldn't be showing up as tracked changes... they were merged in #1303

2019-03-19 07:45 UTC, caelaislinn commented on code/game/jobs/job_controller.dm
> +				continue
Nevermind figured it out. It was showing the changes to the branch specific to the merge commits... github wasn't merging them across

2019-03-19 07:48 UTC, caelaislinn commented
The Travis timeout due to runtime spam is confusing and worrying. Looks like the globals checksum failure is back... I thought I fixed it but apparently not.

2019-03-19 11:29 UTC, caelaislinn approved these changes
Looks good. The Travis failure is the Geminus stairs kerfluffle

2019-03-21 20:39 UTC, BDpuffy420 requested changes
Failing travis

2019-03-21 21:22 UTC, caelaislinn commented
Restarting travis

2019-03-21 23:13 UTC, X0-11 commented
Closing until I can figure out a critical issue

2019-03-21 23:13 UTC, closed without merging