makes flood combat forms revive only once
HaloSpaceStation/HaloSpaceStation13 pull request #1396
Opened 2019-04-01 20:10 UTC by X0-11

Ensures that flood combat forms don't revive infinitely.
Examining a flood combat form will tell you if it can be revived once it dies.

2019-04-01 22:16 UTC, BDpuffy420 approved these changes

2019-04-02 06:01 UTC, caelaislinn requested changes

2019-04-02 06:01 UTC, caelaislinn commented on code/modules/halo/flood/flood.dm
> +	var/corpse_pulped = 0
Where is the actual check for this?

2019-04-02 06:42 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	var/corpse_pulped = 0
Forgot to even put that in. Out of all things...

2019-04-02 07:18 UTC, caelaislinn commented on code/modules/halo/flood/flood.dm
> +	var/corpse_pulped = 0
lmao

2019-04-02 08:25 UTC, X0-11 commented
Added the check.

2019-04-02 08:35 UTC, caelaislinn approved these changes

2019-04-02 17:58 UTC, merged