Overmap Autopilot Adjustments
HaloSpaceStation/HaloSpaceStation13 pull request #1562
Opened 2019-05-26 21:54 UTC by bloxgate

Port Baystation12#23846

2019-05-26 22:06 UTC, BDpuffy420 commented
Conflict in helm.dm

2019-05-26 22:09 UTC, bloxgate commented
Marking this DNM until we're sure if #1560 was successful or not.

2019-05-31 00:57 UTC, caelaislinn requested changes

2019-05-31 00:57 UTC, caelaislinn commented on code/modules/overmap/ships/ship.dm
> +	if(((speed[1]) || (speed[2])) && can_burn())
What's the purpose of removing the call to the helper? This is identical code anyway

2019-05-31 00:59 UTC, bloxgate commented on code/modules/overmap/ships/ship.dm
> +	if(((speed[1]) || (speed[2])) && can_burn())
Ah, that seems to be something that was done in the PR on Bay. Not sure really.

The only changes I've made were to get it to merge with our helm computer, as it was slightly different.

2019-06-04 16:11 UTC, BDpuffy420 commented
#1560  has partly worked but is still an issue, would recommend merging this

2019-06-07 02:42 UTC, caelaislinn approved these changes

2019-06-07 15:57 UTC, merged