Readds Glassed KS7
HaloSpaceStation/HaloSpaceStation13 pull request #1576
Opened 2019-05-30 20:12 UTC by X0-11

Readds Glassed KS7

Adds geminus to nav-chips

2019-05-30 21:51 UTC, caelaislinn requested changes

2019-05-30 21:51 UTC, caelaislinn commented on code/modules/halo/overmap/nav_data_computer.dm
> +	known_sectors = list("Vanguard's Mantle","KS7-535","Geminus City Colony")
I'd like to experiment without Covenant knowing the location of Geminus. That will force them to explore the sector, maybe hit VT9 and KS7 first while giving time for the Innies and UNSC to fight

2019-05-30 21:51 UTC, caelaislinn commented on maps/geminus_city/geminus_city.dm
> -	#endif
The reason for this was so that multiple "base" maps could be loaded

2019-05-30 22:07 UTC, X0-11 commented on maps/geminus_city/geminus_city.dm
> -	#endif
Aye, and it caused errors when the mapdef wasn't defined as the current using_map_datum.
This still allows for the same thing, it just removes an unneeded if statement.

2019-05-30 22:08 UTC, caelaislinn requested changes
It looks like you removed instances of /area/planets/Geminus/indoor/disco from geminuscity_2.dmm so you'll need to comment those out from maps\geminus_city\areas.dm to fix travis

2019-05-30 22:09 UTC, X0-11 commented on code/modules/halo/overmap/nav_data_computer.dm
> +	known_sectors = list("Vanguard's Mantle","KS7-535","Geminus City Colony")
Currently, there's really nothing to explore but empty space.
The covenant would have to go to KS7, obtain VT9's co-ords then go to VT9. After that, they'd have to hope that they can salvage a nav-chip from a human ship without them already disposing of it.

2019-05-30 22:10 UTC, caelaislinn commented on maps/geminus_city/geminus_city.dm
> -	#endif
Oh because of a nonexistent typepath? We can add a dummy path like we have elsewhere. This way it silences the warning if we deliberately want to have Geminus along with other colony maps

2019-05-30 22:11 UTC, caelaislinn commented on code/modules/halo/overmap/nav_data_computer.dm
> +	known_sectors = list("Vanguard's Mantle","KS7-535","Geminus City Colony")
Can we add Geminus coords to KS7?

2019-05-30 22:12 UTC, X0-11 commented on maps/geminus_city/geminus_city.dm
> -	#endif
Some issue with Unexpected Token: "/", pointing towards the compared typepath.
I think the warning's fine being there, after all, having multiple base maps included should be the most common thing but if it is, it should inform the user. A lot of issues could arise from such combinations.

2019-05-30 22:13 UTC, X0-11 commented on code/modules/halo/overmap/nav_data_computer.dm
> +	known_sectors = list("Vanguard's Mantle","KS7-535","Geminus City Colony")
Easily.

2019-05-30 22:35 UTC, X0-11 commented on code/modules/halo/overmap/nav_data_computer.dm
> +	known_sectors = list("Vanguard's Mantle","KS7-535","Geminus City Colony")
This has been done.

2019-05-31 00:52 UTC, caelaislinn approved these changes

2019-05-31 00:57 UTC, bloxgate requested changes

2019-05-31 00:57 UTC, bloxgate commented on code/modules/halo/overmap/nav_data_computer.dm
> +	known_sectors = list("Camp New Hope","Asteroid","KS7-535","Geminus City Colony")
Do the UNSC not get to know about Geminus?

2019-05-31 00:59 UTC, caelaislinn requested changes
Can you readd Geminus coordinates for the UNSC nav chips?

2019-05-31 08:19 UTC, X0-11 commented on code/modules/halo/overmap/nav_data_computer.dm
> +	known_sectors = list("Camp New Hope","Asteroid","KS7-535","Geminus City Colony")
Aye, to ensure that the covenant and unsc are forced to clash on ks7 and also to remove complaints I've been getting about the unsc being spread too thin

2019-05-31 08:29 UTC, X0-11 commented
See above response for why I'd rather not.

2019-05-31 14:20 UTC, BDpuffy420 approved these changes

2019-05-31 14:22 UTC, merged