Sons of Eridanus update
HaloSpaceStation/HaloSpaceStation13 pull request #1652
Opened 2019-06-23 10:17 UTC by Delnth

Add an SOE ship, change URFC to SOE, add spawnpoints, delete the URFC Avarice.

Also biogenerators can now print advanced burn/trauma kits for 100 units of bio matter.

2019-06-23 12:04 UTC, caelaislinn requested changes
I'm not sure if that spawn will work, did you test it? Also I need you to delete the backup map files generated by the avarice-osprey mapping changes. And I'd prefer you not delete entire map files for now, just leave them unused.

2019-06-23 12:05 UTC, Delnth commented
I have tested everything. Haven't noted any problem so far, except the ship guns that refuse to work despite XO's help.

Deleting the backup files.

2019-06-23 23:08 UTC, caelaislinn requested changes
Can you also please restore second_deck.dmm ? We can leave it unused and just load the first deck

2019-06-24 13:18 UTC, BDpuffy420 approved these changes

2019-06-25 01:26 UTC, caelaislinn approved these changes

2019-06-25 01:26 UTC, merged