Updates the SoE Osprey
HaloSpaceStation/HaloSpaceStation13 pull request #1678
Opened 2019-07-09 21:50 UTC by PantasTheDank

:cl: PantasTheDank
type: This PR updates the SoE Osprey
-Adds one additional armor and weapon vendor in the armory, a making it a total of 2 weapons/gear vendors and 2 armor vendors.
-Added 6 medkits in the medical,added 3 tri-adrenaline syringes, removed a plastic table.
-Botany's south-eastern corner has been shifted to make the locker avaliable,was blocked by trays,hopefully fixed the seed vendor.
-removed two plastic tables in the workshop, as they blocked the autolathes.
-Added two shorts in the armory, on the tables with boxing gloves.
/:cl:

:cl: YourName
rscadd: Added a changelog editing system that should cause fewer conflicts and more accurate timestamps.
rscdel: Killed innocent kittens.
/:cl:

2019-07-09 22:57 UTC, bloxgate requested changes

2019-07-09 22:57 UTC, bloxgate commented on maps/URF Commando Ship/first_deck.dmm
> +"hG" = (/obj/structure/table/standard,/obj/item/weapon/reagent_containers/food/condiment/enzyme,/obj/item/weapon/material/kitchen/rollingpin,/obj/item/weapon/reagent_containers/food/condiment/small/p
This line contains both `step_x` and `step_y`. They'll need to be manually removed

2019-07-09 22:59 UTC, PantasTheDank commented on maps/URF Commando Ship/first_deck.dmm
> +"hG" = (/obj/structure/table/standard,/obj/item/weapon/reagent_containers/food/condiment/enzyme,/obj/item/weapon/material/kitchen/rollingpin,/obj/item/weapon/reagent_containers/food/condiment/small/p
Thank you, fingers crossed its gonna work

2019-07-09 23:07 UTC, bloxgate submitted a review, later dismissed
first_deck.dmm is corrupt. It looks like you removed the entire line manually instead of removing the step_x and step_y. You'll need to undo your most recent changes and redo it properly

2019-07-10 03:38 UTC, bloxgate approved these changes

2019-07-10 17:40 UTC, merged