removes plaspistol reset-on-fire
HaloSpaceStation/HaloSpaceStation13 pull request #1681
Opened 2019-07-11 19:10 UTC by X0-11

removes the plasma pistol resetting to normal-mode when fired. A sprite change is enough to clue the user into the current state of the weapon.

2019-07-11 19:15 UTC, BDpuffy420 approved these changes

2019-07-11 23:11 UTC, bloxgate commented
I may have misread this, but doesn't this mean that you can now fire multiple overcharge shots in a row? I thought that the Plasma Pistol is supposed to reset to normal fire after being used?

2019-07-12 02:31 UTC, caelaislinn requested changes
Resetting to normal after firing is intended. That's how it worked in Halo CE

2019-07-12 09:53 UTC, X0-11 commented
This is mostly due to the fact I suspect it's causing the plasma pistol's overcharge to break entirely. Firing one shot on overcharge means you can no longer switch to overcharge.

2019-07-12 15:57 UTC, merged

2019-07-12 22:34 UTC, caelaislinn commented
This would make overcharged plasma pistols capable of rapid firing. In CE there was a cooldown so you couldn't spam superpowerful stun shots

2019-07-12 22:52 UTC, X0-11 commented
Plasma pistols were capable of spamfiring for a long while before you implemented the internal batteries on covvie weapons. It was fine. Our plaspistols don't stun people.