Achlys QoL updates
HaloSpaceStation/HaloSpaceStation13 pull request #1685
Opened 2019-07-12 16:11 UTC by Desolane

This PR brings a number of QoL changes to flood and some to marine gear.

_**The gamemode itself should not be run to play on the server. This PR is to bring over QoL changes to the main repo.**_

**Players are discouraged from checking on this PR as it will ruin some of the gamemode experience.**

:cl: Desolane
rscadd: flood have various new sound barks for death and attack
rscadd: flood now decide what form to make based on armor worn
rscadd: new flood sprites have been put in for default forms
rscadd: flood have emotes and more attack verbs
rscadd: juggernauts are beefy and fixed now
rscadd: marine boots now stomp menacingly
rscadd: marine headset typo fixed
/:cl:

2019-07-12 17:35 UTC, X0-11 requested changes

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/clothing/marine.dm
> +			playsound(src, "sound/effects/jackboot.ogg", 50, 1)
This would ideally be moved to base /shoes define and generalised to allow definition of the sound to play as a variable.

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +		mob_type_spawn = /mob/living/simple_animal/hostile/flood/combat_form/prisoner
All the above code could likely be much better implemented through the use of a dictionary-style list and a for loop.

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +		else if(door.stat & BROKEN)
These two conditions would be better placed into the same if() statement, with an or ( || ) operator to combine the two conditions

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	var/obj/item/inventory = null //an item goes in this variable of the instance with the full path "in/quotes". item in var will drop upon death
Wouldn't a list work better here to allow for multiple in-inventory items?

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	health = 50 //intentionally squishy to give melee combat a chance
Melee combat already has the upside of high-damage and parrying/autocounter of simplemob melee attacks. Won't health this low make them way too easy to kill?

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	health = 60 //beefier than it's common counterpart to give a better sense of danger and urgency to encounters
This increase in health is effectively for nothing, assuming the usage of even just the normal MA5B, which does 30 damage per shot. Both the original and this form will die in two rounds.

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	icon_dead = "guard_infected1_dead"
Perhaps minor resistance could be given to these forms to account for their armour?

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	health = 200
This should probably be equal to the maxHealth variable.

2019-07-12 17:35 UTC, X0-11 commented on code/modules/halo/flood/flood_spawn_proxy.dm
> +	new /mob/living/simple_animal/hostile/flood/infestor(dest)
A for loop would be better for this purpose.

2019-07-12 17:35 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +	icon_state = "coin_gold"
Is this intended to be here?

2019-07-12 17:35 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +	access = list(666)
cursed access number

2019-07-12 17:39 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +	var/obj/item/inventory = null //an item goes in this variable of the instance with the full path "in/quotes". item in var will drop upon death
because of the way variable editing for instances in a dmm works, if multiple listings appear in the variable they cease to function at all. I could barely hotwire this function in.

2019-07-12 17:41 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +		mob_type_spawn = /mob/living/simple_animal/hostile/flood/combat_form/prisoner
I have no idea how to get that to work or how it would be written. This was made with the extent of my knowledge.

2019-07-12 17:43 UTC, Desolane commented on code/modules/halo/clothing/marine.dm
> +			playsound(src, "sound/effects/jackboot.ogg", 50, 1)
This was simply copypasta pulled from clown shoes as they are the only shoe in the entire codebase to have a step sound altogether. I don't really know the use of adding a generalized var to step sounds beyond this unless they'd be wanted universally.

2019-07-12 17:46 UTC, Desolane commented on maps/unsc_achlys/achlys_objects.dm
> +	icon_state = "coin_gold"
It is intended. Referencing a section of Dante's Inferno where a demon with the same name as one of the pelicans carries the protagonist across a river. The demon is cursed to do this because of fraud and deceit, which one of the circles of hell also carries the same price for inhabitants.

2019-07-12 17:46 UTC, Desolane commented on code/modules/halo/flood/flood_spawn_proxy.dm
> +	new /mob/living/simple_animal/hostile/flood/infestor(dest)
I don't know how I would do that.

2019-07-12 17:48 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +	icon_dead = "guard_infected1_dead"
Would work better for "armored" forms as the guards only wear a jumpsuit.

2019-07-12 17:48 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +	health = 50 //intentionally squishy to give melee combat a chance
They are fodder. They are supposed to be easy to kill. Their intended style is death by one thousand cuts.

2019-07-12 17:49 UTC, X0-11 commented on code/modules/halo/flood/flood_spawn_proxy.dm
> +	new /mob/living/simple_animal/hostile/flood/infestor(dest)
http://www.byond.com/forum/post/120895

2019-07-12 17:49 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +		else if(door.stat & BROKEN)
I did not write that line, the person that wrote door infection wrote it. I can adjust it though.

2019-07-12 17:50 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +		else if(door.stat & BROKEN)
You added the weld-check, I added the original broken-door check. I'm suggesting they be combined instead of seperated here.

2019-07-12 17:52 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +		mob_type_spawn = /mob/living/simple_animal/hostile/flood/combat_form/prisoner
http://www.byond.com/forum/post/120895
http://www.byond.com/docs/guide/chap10.html

2019-07-12 17:54 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +		else if(door.stat & BROKEN)
How would they ignore welded doors but not other types if they are combined in one line?

2019-07-12 17:55 UTC, X0-11 commented on code/modules/halo/clothing/marine.dm
> +			playsound(src, "sound/effects/jackboot.ogg", 50, 1)
even by copy-pasting this code you've created two seperate usages of the same code. Generalising it should be doable by moving the handle_movement code to the base /shoes define, alongside adding a footstep_sound variable to the define.

2019-07-12 17:57 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +		else if(door.stat & BROKEN)
You'd be combining the two conditions with an OR operator, so if the door is broken OR if it is welded, it would be skipped.
Also, "continue" should be used here instead of "return"

2019-07-12 18:00 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +	health = 60 //beefier than it's common counterpart to give a better sense of danger and urgency to encounters
The MA5B has too much dispersion to handle something in a single burst without it being point blank. You cannot fire the MA5B in semi automatic, and are forced to fire in bursts. The health of the flood are tailored around the fact that no matter how you handle them, you are at risk of using ammo or taking damage. The health could be 2 and you would still use 3-5 rounds to kill something, or risk taking a hit in melee combat. Regardless, unless changes are made to dispersion or fire rates, health is almost irrelevant at this point in time.

2019-07-12 18:02 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	health = 60 //beefier than it's common counterpart to give a better sense of danger and urgency to encounters
I was merely addressing the comment's claim of the form as "beefier". Sounds like you've got this thought out though.

2019-07-12 18:04 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +		else if(door.stat & BROKEN)
No, return is used to make infection forms ignore welded doors within 2 tiles, as was the intent?

2019-07-12 18:06 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +		else if(door.stat & BROKEN)
The check is placed within a for loop and is checking one of the elements within a list. RETURN will cause it to stop checking the list, no matter the position. CONTINUE causes it to skip the current element and start checking the next one.

2019-07-12 18:07 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +	health = 60 //beefier than it's common counterpart to give a better sense of danger and urgency to encounters
Using the term beefier was bringing up the melee combat prisoners will be forced to commit to. Even 10 more health in melee combat makes a big difference when fighting with a crowbar. The forms won't stand up to marines very well though.

2019-07-12 18:09 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	var/obj/item/inventory = null //an item goes in this variable of the instance with the full path "in/quotes". item in var will drop upon death
DMM editing should allow for editing of list() type variables. When editing the entry for the variable, did you ensure it was formatted like: list(/obj/item/blah,/obj/item/blah2) ?

2019-07-12 18:10 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +	health = 200
Fixed. Thank you.

2019-07-12 18:12 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +	var/obj/item/inventory = null //an item goes in this variable of the instance with the full path "in/quotes". item in var will drop upon death
No, the variable itself did not like list() anything, and using a comma causes issues since the object in question must be parsed like "obj/item/weapon" and requires quotations.

2019-07-12 18:13 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +		else if(door.stat & BROKEN)
Regardless, the checks were combined into a singular line.

2019-07-12 18:15 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	var/obj/item/inventory = null //an item goes in this variable of the instance with the full path "in/quotes". item in var will drop upon death
Whilst I still believe this would be able to be converted to a /list/ type variable, you don't seem to require the use of it like that. Will resolve conversation.

2019-07-12 18:18 UTC, Desolane commented on code/modules/halo/flood/flood.dm
> +	var/obj/item/inventory = null //an item goes in this variable of the instance with the full path "in/quotes". item in var will drop upon death
The use would be nice but even then, dropping multiple items can be done by making a loot distributor with the items you would like dropped in the list and then putting the distributor path into this variable of the mob. The result is that it drops everything in the list instead of picking one to drop at random. Discovered by accident.

2019-07-12 18:21 UTC, Desolane commented on maps/unsc_achlys/achlys_objects.dm
> +	access = list(666)
Is this access number already in use in an included file elsewhere? It functioned fine in game.

2019-07-12 18:32 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +	access = list(666)
Nah, just referencing the fact the access number is 666.

2019-07-12 19:03 UTC, Desolane commented on code/modules/halo/clothing/marine.dm
> +			playsound(src, "sound/effects/jackboot.ogg", 50, 1)
This has been fixed.

2019-07-13 00:19 UTC, bloxgate requested changes

2019-07-13 00:19 UTC, bloxgate commented on baystation12.dme
> -#include "code\modules\client\preference_setup\general\02_la
It looks like a failed merge conflict resolution happened somewhere in this file. You may want to give it a once over with a proper merge conflict resolver.

2019-07-13 21:09 UTC, X0-11 approved these changes

2019-07-13 21:14 UTC, merged