x52, here it comes
HaloSpaceStation/HaloSpaceStation13 pull request #1728
Opened 2019-07-22 18:38 UTC by Delnth

Add the x52 base and all of its components, assets and the like. Lighting and jobs don't work yet. Until I can address these issues, do not merge.

:cl: Koenigsegg
rscadd: Add x52 base (With doors restricted to x52 personnel)
rscadd: Add X52 Researcher and Research Director
rscadd: Add virology, R&D, Hydroponics, chemistry, surgery and integrated circuits to the base as well as a storage room with a few items of interest.
:cl:

2019-07-22 22:00 UTC, BDpuffy420 commented
Duplicated APCs in area

2019-07-22 22:59 UTC, bloxgate reviewed
Some of those `rscadd`s in your changelog should probably be changed to `maptweak`

2019-07-23 13:33 UTC, Delnth commented
Duplicate APC? There's only one in the area that I have coded in. I shoudn't need to make a new instance of said APC, since they update at round start.

As for the changelog, I'll change it.

2019-07-23 13:51 UTC, BDpuffy420 commented
That’s what’s the Travis log reading, it’s an APC underground

2019-07-23 15:42 UTC, Delnth commented
I'm fixing the APC problem. In the meantime, any idea why the jobs do not appear in the ingame list? Everything is setup correctly.

2019-07-23 17:58 UTC, BDpuffy420 commented
Is the job in the allow_spawn list?

2019-07-23 19:55 UTC, Delnth commented
Okay now I am asking a developper to look into the problem because it just seem like Travis is picking up a false alarm. Nothing's wrong with the APC. It is tested and compiled without a problem, yet some random APC is having conflicts with the X52 one. 

Again, there is absolutely **nothing wrong**, yeah it refuses to pass Travis checks for some reason. I am not going to attempt fixing the issue until I get some assistance.

2019-07-24 01:30 UTC, Delnth commented
Last commit fixes the X52 researchers faction, so they can actually open the fakewall.
The PR is ready to go.

2019-07-24 02:35 UTC, caelaislinn requested changes
One other change, go into the map and change var/faction_locked for the fakewalls to "X52". 

Although they're a subfaction of innies, my intent is for them to be mostly separate with separate objectives, and not sharing any access or comms (at least at start).

2019-07-24 02:35 UTC, caelaislinn commented on maps/geminus_city/x52_jobs.dm
> +	spawn_faction = "Insurrection"
Can you change spawn_faction to "X52"

2019-07-24 02:35 UTC, caelaislinn commented on maps/geminus_city/x52_jobs.dm
> +	spawn_faction = "Insurrection"
And here change spawn_faction to "X52"

2019-07-24 02:35 UTC, caelaislinn commented on maps/geminus_city/x52_outfits.dm
> +	l_ear = /obj/item/device/radio/headset/insurrection
Don't give them innie comms, just an ordinary colonist headset for now. I'll handle their comms separately

2019-07-24 02:35 UTC, caelaislinn commented on maps/geminus_city/x52_outfits.dm
> +		W.update_name()
Change this to 
```
/decl/hierarchy/outfit/job/colonist/equip_id(mob/living/carbon/human/H)
	var/obj/item/weapon/card/id/C = ..()
	C.assignment = "Colonist"
	H.set_id_info(C)
```
to match the innie IDs

2019-07-24 02:35 UTC, caelaislinn commented on maps/geminus_city/x52_outfits.dm
> +		W.update_name()
Change this equip_id() same as above

2019-07-24 02:47 UTC, caelaislinn requested changes
Can you go to /datum/job/geminus_innie/officer in maps\geminus_city\innie_jobs.dm and add
```
	open_slot_on_death = 1
	track_players = 1
```
This will ensure that officers can respawn, as well as basic innies

2019-07-24 02:47 UTC, caelaislinn commented on maps/geminus_city/x52_jobs.dm
> +	whitelisted_species = list(/datum/species/human)
Can you add 
```
intro_blurb = "You are X-52! Working for a top secret military research project, one day you decided to go AWOL with your secrets and expertise. Now you're out for yourselves. Just remember the UNSC will always be looking for you..."
```

2019-07-24 02:47 UTC, caelaislinn commented on maps/geminus_city/x52_jobs.dm
> +	whitelisted_species = list(/datum/species/human)
And add
```
intro_blurb = "You are X-52! Working for a top secret military research project, one day you decided to go AWOL with your secrets and expertise. Now you're out for yourselves. Just remember the UNSC will always be looking for you..."
```

2019-07-25 00:57 UTC, bloxgate commented
Travis failure is a false alarm due to #1732. I'll restart that specific test, but otherwise this is good to go once Cael is happy with it.

2019-07-25 01:05 UTC, caelaislinn approved these changes

2019-07-25 01:06 UTC, caelaislinn commented
Happy to merge. This is content for live testing and will probably go through some dramatic changes over the next week.

2019-07-25 01:07 UTC, Delnth commented
I might as well move the base elsewhere too. I'm afraid the proximity from the sewer hallways might be an easy lead for anyone willing to meta its location. We will see how it goes.

2019-07-25 01:20 UTC, merged