[WIP] Base Demolition
HaloSpaceStation/HaloSpaceStation13 pull request #1733
Opened 2019-07-23 04:48 UTC by bloxgate

Adds innie base demolition system with appropriate UNSC objective

:cl: bloxgate
wip: Base demolition system
/:cl:

2019-07-25 07:39 UTC, caelaislinn requested changes

2019-07-25 07:39 UTC, caelaislinn commented on code/game/objects/items/weapons/explosives.dm
> +				D.demolish()
Instead of doing landmarks, do a special subtype of wall that triggers destruction whenever it is deconstructed. That way would be simpler and more generalised so there are more methods of destruction than just C12

2019-07-25 07:39 UTC, caelaislinn commented on code/modules/halo/demolitions/effects.dm
> +	var/z = -1
I'm not sure about this. I was thinking at first the demolition code should be tied to the overmap object, but it doesn't destroy the overmap or an entire zlevel, only part of a zlevel. 

Can you add a faction var to this, and set it to disable spawns for that faction when it's demolished?

2019-07-25 07:39 UTC, caelaislinn commented on code/modules/halo/demolitions/effects.dm
> +				explosion(D.loc, 3, 5, 7, 5)
I'd prefer a process to a spawn. Also, probably drop devastation range and just spawn a bunch of bolders in connected areas. 

Connected areas would just be areas that the "demolish" atoms (whether landmarks or structures) are placed in.

2019-07-25 07:39 UTC, caelaislinn commented on code/modules/halo/demolitions/effects.dm
> +		map_sectors["[z]"].pre_superstructure_failing()
No need to genericize this for ships. We already have ship/station destruction code which is enough, and if it isn't working then we can fix it.

2019-07-25 07:39 UTC, caelaislinn commented on code/modules/halo/demolitions/items.dm
> +		.()
Gods this is immersion breaking, but otherwise not a bad idea.

2019-07-25 07:39 UTC, caelaislinn commented on code/modules/halo/factions/objectives/_objectives.dm
> +
Good

2019-07-25 23:36 UTC, bloxgate commented on code/modules/halo/demolitions/effects.dm
> +				explosion(D.loc, 3, 5, 7, 5)
The only definition for a `Process()` proc - the one you mentioned in Discord - is for a hud helper that immediately returns nothing.

Are you sure you're thinking of the right thing?

2019-08-11 15:47 UTC, BDpuffy420 commented
Updates on this?

2019-08-11 18:16 UTC, bloxgate commented
Need to add in the landmark that'll spawn rubble, and that's about it. As far as I know everything except that `todo` is working

2019-08-15 23:06 UTC, caelaislinn requested changes

2019-08-15 23:06 UTC, caelaislinn commented on code/modules/halo/demolitions/effects.dm
> +		GLOB.DEMOLITION_MANAGER_LIST["[map_sectors["[z]"]]"] = new/datum/demolition_manager
There should be a single controller, not multiple ones for each zlevel

2019-08-15 23:06 UTC, caelaislinn commented on code/modules/halo/demolitions/effects.dm
> +		for(var/datum/job/J)
Change this to reference the job_master for consistency's sake.

2019-08-15 23:06 UTC, caelaislinn commented on code/modules/halo/demolitions/effects.dm
> +		// TODO: Spawn rubble in area
Just use view() and have an 80% chance to spawn rocks, killing anything underneath

2019-10-01 20:37 UTC, merged