Unfucks Casings
HaloSpaceStation/HaloSpaceStation13 pull request #1743
Opened 2019-07-26 17:50 UTC by Desolane

:cl: Desolane
tweak: Spent casings now eject properly and don't land on walls and randomly surround the player.
/:cl:

2019-07-26 17:54 UTC, PantasTheDank commented
I love you deso

2019-07-26 18:51 UTC, X0-11 commented on code/modules/projectiles/guns/projectile.dm
> -			qdel(chambered)
has this been tested to not interfere with guns that use CASELESS

2019-07-26 18:52 UTC, X0-11 commented on code/modules/projectiles/guns/projectile.dm
> +	if(handle_casings == EJECT_CASINGS)
this should be inside process_chambered, or at least indented. this will runtime if it triggers with a null chambered.

2019-07-26 18:53 UTC, Desolane commented on code/modules/projectiles/guns/projectile.dm
> -			qdel(chambered)
It has now. Caseless guns do not produce casings.

2019-07-26 18:55 UTC, X0-11 commented on code/modules/projectiles/guns/projectile.dm
> -			qdel(chambered)
That's not what needs testing. Relying on BYOND's inbuiit garbage collector to ensure that the chambered is actually deleted after firing is not a good thing to do.

2019-07-27 04:34 UTC, bloxgate requested changes

2019-07-27 04:34 UTC, bloxgate commented on code/modules/projectiles/guns/projectile.dm
> +	if(handle_casings == EJECT_CASINGS)
Yeah, I'm going to revive what @X0-11 said. This should be moved into the `process_chambered()` proc.

2019-07-27 05:13 UTC, Desolane commented on code/modules/projectiles/guns/projectile.dm
> +	if(handle_casings == EJECT_CASINGS)
statement moved

2019-07-27 05:24 UTC, bloxgate approved these changes

2019-07-27 18:15 UTC, merged