Update SOE
HaloSpaceStation/HaloSpaceStation13 pull request #1750
Opened 2019-08-02 22:19 UTC by Eluxor

:cl: Eluxor
tweak: Reworked all SOE gear, berets, helmets and jumpsuits galore. "Dress your own SOE trooper" game not included. SOE armor is no longer spaceproof.
rscadd: But they get a very new spacesuit with a jetpack for breaching and capturing operations in space.
rscadd: Added two new guns that fit the newly made SOE style. The KV-32 Double barrelled custom shotgun, magazine !!FED!! with 4 rounds and the old Trusty weapon of space pirate captains... THE HANDGONNE! A 14.5mm pistol.
imageadd: Added new SoE gear sprites
:cl:

:cl: YourName
rscadd: Added a changelog editing system that should cause fewer conflicts and more accurate timestamps.
rscdel: Killed innocent kittens.
/:cl:

2019-08-03 00:19 UTC, bloxgate requested changes
Just a few suggestions. Besides these, I think the changelog would read a little better if it was reworded a bit. Maybe make it so that the entries are a bit more self contained? I.e., the second entry doesn't require you to have read the first to know what the `But` is referring to?

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +#define URF_OVERRIDE 'code/modules/halo/clothing/urf_commando.dmi'
Both of these `#define`s need to be undefined at the end of the file

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/clothing/urc_commando_variants.dm
> +//MASKS
There doesn't seem to be any masks after here?

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +	desc = "Non-Standard issue short-EVA capable helmet issued to (REDACTED) forces"
I don't really think you need to put the `(REDACTED)` in, but that's not anything major.

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +	desc = "Heavyweight,somewhat durable armour issued to (REDACTED) for increased survivability in the field."
`Heavyweight, somewhat`. And ditto the above on `(REDACTED)`

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +	slowdown_general = -0.5
Negative `slowdown_general` makes you faster. Are you sure that's what you want to do.

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +/obj/item/weapon/tank/jetpack/urfc/New()
If you make this a sub-type of the existing oxygen jetpack, you won't need to have the extra `New()` proc here.

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +/obj/item/clothing/mask/gas/soebalaclavaopen
This should probably be a subtype of the above gas mask.

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +	gas_transfer_coefficient = 0.01
This is insanely airtight for something that's supposedly open.

2019-08-03 00:19 UTC, bloxgate commented on code/modules/halo/weapons/pistols.dm
> +/obj/item/weapon/gun/projectile/heavysniper/handgonne
This already exists in #1744. There's going to be problems if either of these are merged due to that.

2019-08-03 20:27 UTC, bloxgate requested changes
Looking much better! Mainly just a few issues with the descriptions on a few items. I'm going to ask Cael to take a look over this since he's been handling a fair bit of the URF/SOE stuff lately.

2019-08-03 20:27 UTC, bloxgate commented on code/modules/halo/clothing/urc_commando_variants.dm
> +	desc = "An red beret. Weirdly made of some kind of bulletproof material."
`An` -> `A`

2019-08-03 20:27 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +	desc = "An commander hat. Weirdly made of some kind of bulletproof material."
A

2019-08-03 20:27 UTC, bloxgate commented on code/modules/halo/clothing/urf_commando.dm
> +/obj/item/weapon/tank/jetpack/urfc
Yeah... this isn't the change I asked you to make. To get rid of the `New` proc for this, it has to be a subtype of the existing oxygen jetpack. This is a subtype of the empty jetpack at the moment.

2019-08-03 20:27 UTC, bloxgate commented on code/modules/halo/weapons/pistols.dm
> +	 return
This proc does literally nothing. Are you sure you need to have it?

2019-08-03 21:01 UTC, Eluxor commented on code/modules/halo/weapons/pistols.dm
> +	 return
Yes, its due the handgonne being a subtype of the heavy sniper. I need that to remove the scope. As the heavy sniper has a scope and the handgonne doesnt.

2019-08-04 18:15 UTC, Eluxor commented on code/modules/halo/clothing/urc_commando_variants.dm
> +	desc = "An red beret. Weirdly made of some kind of bulletproof material."
fixed

2019-08-04 18:17 UTC, Eluxor commented on code/modules/halo/clothing/urf_commando.dm
> +	desc = "An commander hat. Weirdly made of some kind of bulletproof material."
fixed

2019-08-05 14:45 UTC, Eluxor commented on code/modules/halo/clothing/urf_commando.dm
> +/obj/item/weapon/tank/jetpack/urfc
I just tried to fix it? I am not following you, I am not that well versed in code.

2019-08-05 17:04 UTC, bloxgate commented
You need to make it an oxygen jetpack. Right now it's an empty jetpack. You
could only get rid of that `New()` if you changed it to be an oxygen
jetpack as well.

On Mon, Aug 5, 2019, 9:45 AM Eluxor <notifications@github.com> wrote:

> *@Eluxor* commented on this pull request.
> ------------------------------
>
> In code/modules/halo/clothing/urf_commando.dm
> <https://github.com/HaloSpaceStation/HaloSpaceStation13/pull/1750#discussion_r310641718>
> :
>
> > \ No newline at end of file
> +	)
> +
> +
> +//JETPACK
> +
> +/obj/item/weapon/tank/jetpack/urfc
>
> I just tried to fix it? I am not following you, I am not that well versed
> in code.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/HaloSpaceStation/HaloSpaceStation13/pull/1750?email_source=notifications&email_token=AAP3UXAUS2QR4ESBZZM4QJTQDA4KDA5CNFSM4IJBMSLKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCASE6KY#discussion_r310641718>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAP3UXF2X6ZTZVIM576MPADQDA4KDANCNFSM4IJBMSLA>
> .
>

2019-08-05 23:02 UTC, bloxgate approved these changes

2019-08-05 23:11 UTC, BDpuffy420 commented
It’s was still failing Travis

2019-08-05 23:21 UTC, bloxgate submitted a review, later dismissed

2019-08-05 23:21 UTC, bloxgate commented on code/modules/halo/structures/gunvendors.dm
> +	/obj/item/weapon/tank/jetpack/urfc = 6 )
This doesn't exist.

2019-08-07 00:53 UTC, BDpuffy420 approved these changes

2019-08-07 02:49 UTC, merged