Police outfits & M6B
HaloSpaceStation/HaloSpaceStation13 pull request #1914
Opened 2019-11-10 09:33 UTC by Desolane

:cl: Desolane900
rscadd: Added new GCPD outfits.
rscadd: Added new GCPD helmets.
rscadd: Added new GCPD armors.
rscadd: Added new helmet subtype: gas.
rscdel: Nukes old GCPD outfits.
/:cl:

2019-11-10 09:35 UTC, Desolane commented
This is technically merge capable as is, but I am still waiting for magazine sprites for the M6B before I want it merged. Peer review on the gasmask helmet subtype would be appreciated as it functions and works incredibly well for everything from tear gas to pepperspray, it's probably not in the ideal place nor should it be a subtype the way it currently is, but it needed done and I dunno how else I would have done it.

2019-11-10 09:51 UTC, X0-11 commented on code/modules/halo/clothing/civilian.dm
> +	armor_thickness = 35//this had zero thickness lol
no it didn't, it had 20 as per inheriting from /armor.
35 is way too high. Adding more armor thickness than 20 has a number of effects including making the person have more grace shots. If you want to make the armor "heavy" armor, increase the base armor values which act as "minimums"

2019-11-10 09:51 UTC, X0-11 commented on code/modules/halo/clothing/civilian.dm
> +	armor_thickness = 15
this should probably be the base 20 value

2019-11-10 09:51 UTC, X0-11 commented on code/modules/halo/clothing/civilian.dm
> +/obj/item/clothing/head/helmet/gas//copied code from gas masks and applied it to helmets for variability //not sure if best place for it
gasmaskhelm might not work because it's likely that the helmet doesn't get checked for filtering gases

2019-11-10 10:12 UTC, Desolane commented on code/modules/halo/clothing/civilian.dm
> +/obj/item/clothing/head/helmet/gas//copied code from gas masks and applied it to helmets for variability //not sure if best place for it
The proc checks for gas differences, it's just copypasta from actual gas masks.

2019-11-10 10:12 UTC, X0-11 commented on code/modules/halo/clothing/civilian.dm
> +/obj/item/clothing/head/helmet/gas//copied code from gas masks and applied it to helmets for variability //not sure if best place for it
yes but does the helmet ever get the filter_gas check actually called on it when processing breaths

2019-11-10 10:14 UTC, Desolane commented on code/modules/halo/clothing/civilian.dm
> +/obj/item/clothing/head/helmet/gas//copied code from gas masks and applied it to helmets for variability //not sure if best place for it
Line 122

2019-11-10 10:15 UTC, X0-11 commented on code/modules/halo/clothing/civilian.dm
> +/obj/item/clothing/head/helmet/gas//copied code from gas masks and applied it to helmets for variability //not sure if best place for it
yes the proc exists but does breathcode care or actually call it anywhere. it's likely that breathcode only calls such a proc on the maskslot

2019-11-11 22:31 UTC, X0-11 requested changes

2019-11-11 22:31 UTC, X0-11 commented on code/modules/halo/clothing/civilian.dm
> +	armor_thickness = 3
I feel like you've misunderstood armor_thickness again.
armor_thickness / 10 = multiplier to armor values
20 gives about 2 grace shots.

2019-11-12 18:30 UTC, BDpuffy420 approved these changes

2019-11-12 18:31 UTC, merged