Bugfix, Tweak, and Boxes
HaloSpaceStation/HaloSpaceStation13 pull request #1949
Opened 2019-11-14 19:21 UTC by Ashvor

:cl: Ashvor
tweak: Minor change to Pantas Donor armor. 
tweak: Donator boxes now implemented. Boxes are coded to spawn with characters based on cdkey + title.
bugfix: BR55 wielded sprite not showing. Fixed.
bugfix: Ashvor donor boots, path not correct. Fixed.
/:cl:

2019-11-14 22:07 UTC, X0-11 requested changes

2019-11-14 22:07 UTC, X0-11 commented on code/modules/halo/clothing/doneritems.dm
> +	max_storage_space = 46
apparently this has to be even bigger

2019-11-14 22:07 UTC, X0-11 commented on code/modules/halo/weapons/rifles.dm
> -	wielded_item_state = "br55-wielded"
You should probably remove this change as discussed with Eluxor.

2019-11-15 05:07 UTC, Ashvor commented on code/modules/halo/weapons/rifles.dm
> -	wielded_item_state = "br55-wielded"
I did, was just at work and couldn't access my computer. It has been restored.

2019-11-15 05:08 UTC, Ashvor commented on code/modules/halo/clothing/doneritems.dm
> +	max_storage_space = 46
That's what she said? No, I just changed the base fluff box to now support HUGE sized items instead of normal. Hopefully this will appease Travis.

2019-11-15 07:46 UTC, X0-11 approved these changes

2019-11-16 00:55 UTC, X0-11 commented on code/modules/halo/clothing/doneritems.dm
> +	uniform = /obj/item/clothing/under/mildress/Jul
Is this meant to be the name

2019-11-16 01:03 UTC, Ashvor commented on code/modules/halo/clothing/doneritems.dm
> +	uniform = /obj/item/clothing/under/mildress/Jul
Oof, knew I forgot something. Thank you.

2019-11-16 01:22 UTC, merged