Various changes
HaloSpaceStation/HaloSpaceStation13 pull request #2067
Opened 2019-12-16 20:23 UTC by X0-11

:cl: XO-11
tweak: UNSC COs rejoice, for now you have a sword and upgraded magnum.
tweak: Machetes no longer get cut in half by energy swords.
tweak: Delicious combination drawing implements and food have been added to the snack vendor.
tweak: The covenant are learning... Some of their higher ranked members now know the detestable human language
/:cl:

2019-12-16 21:59 UTC, Terror4000rus requested changes

2019-12-16 21:59 UTC, Terror4000rus commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
If you are about to make ship weaponry indestructable, maybe remap at least main ships (LB and covenant one) and add APCs in areas with weaponry? Because, at other way, almost ripped appart ship with functional bridge still can use the all of its weaponry.

2019-12-16 22:10 UTC, X0-11 commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
An unpowered firing console will fail to fire when triggered by the global console. If ships have followed my original design of banks of local consoles linked to a single global console is a mapping issue

2019-12-16 22:16 UTC, Terror4000rus commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
Covenant has 4 local consoles in bridge.
LB has consoles at fore, in port and starboard hull.
I already #2038 issued the problem with losing of power at the whole section, but with such changes it would be even more problem in case of MAC power failure due lags or illogical working of consoles - "We lost 90% of hull at fore-starboard? Meh, MAC room APC is still fine, so consoles still powered."

2019-12-16 22:17 UTC, X0-11 commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
It's certainly not ideal. It's also a mapping problem. Any weapons console will disallow firing if it's unable to draw power.

2019-12-16 22:18 UTC, Terror4000rus commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
> It's also a mapping problem.
Could you fix it before merging then?

2019-12-16 22:19 UTC, X0-11 commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
The mapmaker has stated that they have changes lined up. If I make changes, it'll conflict.

2019-12-16 22:20 UTC, Terror4000rus commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
Wait until the commit with changes and remade it then?

2019-12-16 22:24 UTC, X0-11 commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
Their changes are currently delayed due to internet connection issues.

Mapfile changes are not going to be included into this PR.

2019-12-16 22:26 UTC, Terror4000rus commented on code/modules/halo/overmap/weapons/proj_deck_gun.dm
> +
Alright, just take a note about this and do something with it, please.

2019-12-18 17:49 UTC, BDpuffy420 approved these changes

2019-12-18 17:49 UTC, merged