Rework of LB.
HaloSpaceStation/HaloSpaceStation13 pull request #2130
Opened 2020-01-22 14:36 UTC by Nanu308

:cl: Nanu308
rscadd: REWORK OF LIGHT BRIGADE.
rscadd: Moved Nuke/AI/Navcom.
rscadd: Made a new way from Briefing to ForePortside Hangar.
rscadd: Added some of that Flare
rscadd: Added better new Engines that do not need cooling
rscadd: Added an Atmos system that functions.
rscadd: Changed Medbay, All should be there. If you miss anything say so.
rscdel: Removed old atmos system
/:cl:

2020-01-22 23:41 UTC, BDpuffy420 commented
Travis mad

2020-01-23 21:58 UTC, Nanu308 commented
### **I WILL KILL THIS BOT**

2020-01-25 01:19 UTC, BDpuffy420 commented
PR still failing due to other reason not related to deso's GM

2020-01-25 01:24 UTC, caelaislinn requested changes
Fix that single indent (remove it so it aligns with the edge of the file) and it will fix all the travis failures

2020-01-25 01:24 UTC, caelaislinn commented on maps/UNSC_Halberd_Class/areas.dm
> +	/area/destroyer/unsclightbrigade
This is failing travis, there shouldn't be an indent here

2020-01-25 08:37 UTC, Nanu308 commented on maps/UNSC_Halberd_Class/areas.dm
> +	/area/destroyer/unsclightbrigade
I believe this have been fixed now

2020-01-28 18:27 UTC, X0-11 commented
set to DNM, awaiting further update to changelog

2020-01-28 20:37 UTC, Nanu308 commented
I will make a full changelogg tomorrow/today depending if all issues get removed

2020-01-28 21:56 UTC, caelaislinn approved these changes

2020-01-28 21:57 UTC, caelaislinn commented
Travis failure is achlys map

2020-01-28 21:57 UTC, merged