More minor grunt QOL changes as outlined in balance request.
HaloSpaceStation/HaloSpaceStation13 pull request #2275
Opened 2020-02-29 23:00 UTC by EpicFatGamer

I removed all armor values for hands/feet the unggoy harness had, and added it to natural armor. This should give unggoy the incredibly small advantage of keeping their hand and foot armor even when their harness is damaged, as well as very slightly stronger armor in those areas overall. The justification is that trying to cut those areas in melee would be difficult, as it's covered by barbs and is extremely hard. 
The needler change is to make more kigyar/grunts take the weapon, as it's inability to fit on a back slot along with covenant's limited storage made it so you couldn't store it without giving up a belt, which is almost downright mandatory due to the lack of backpacks.  

:cl: EpicFatGamerNuts
tweak: moved armor values to natural armor from harness
tweak: slightly buffed said armor values
tweak: needler can fit on back 
/:cl:

2020-03-02 17:41 UTC, X0-11 commented
travis angery

2020-03-05 03:52 UTC, caelaislinn requested changes
Please avoid commit messages like "Update grunt.dm" as it's uninformative and not helpful. Your commit messages like "Add armor to natural armor, remove from harness " are good. A commit message should briefly describe what the changes are. 

Also it looks like someone merged a travis failing PR that modified the globals. I've updated the global checksum in #2233 which will fix that.

2020-03-05 03:52 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS||ARMS| //Essentially, the entire body besides the head
This should be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS`

2020-03-05 03:52 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +
Try to avoid randomly adding or deleting newlines

2020-03-05 03:52 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS||ARMS|
This should be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS`

2020-03-05 03:52 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS||ARMS|
This should be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS`

2020-03-05 03:52 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS||ARMS|
This should be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS`

2020-03-06 21:07 UTC, caelaislinn requested changes

2020-03-06 21:07 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS| //Essentially, the entire body besides the head
Still not quite correct. It needs to be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS` note the bar at the end is removed. 

Note that setting it here applies this setting to all the unggoy armour, so you don't need to reapply it later in the file.

2020-03-06 21:07 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS|
I did some checking and this line can actually be deleted. For it to work it needs to be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS` but for future code maintenance it's better to remove it.

2020-03-06 21:07 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS|
This should be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS` but it can also be deleted.

2020-03-06 21:07 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS|
This should be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS` but it can also be deleted.

2020-03-06 21:07 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS|
This should be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS` but it can also be deleted.

2020-03-06 21:07 UTC, caelaislinn commented on code/modules/halo/species_items/grunt.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS|
This should be `body_parts_covered = UPPER_TORSO|LOWER_TORSO|LEGS|ARMS` but it can also be deleted.

2020-04-01 21:05 UTC, BDpuffy420 commented
going to close this

2020-04-01 21:09 UTC, closed without merging