Vehicle ammo
HaloSpaceStation/HaloSpaceStation13 pull request #2388
Opened 2020-04-16 06:45 UTC by X0-11

:cl: XO-11
tweaks: Vehicles should no longer cause self supression.
tweak: Vehicles now utilise internal ammo tracking, with rearm stations present on the flagship and troop-carrier subships.
tweak: vehicle handling has been improved, making them more responsive.
tweak: some weapons have been given a damage type that only applies to shields, to lessen the gap between shielded and unshielded foes.
tweak: vehicles colliding with a mob will now knock them down.
tweak: adds alarm buttons to various vessels.
/:cl:

2020-04-17 12:59 UTC, caelaislinn requested changes

2020-04-17 12:59 UTC, caelaislinn commented on code/modules/halo/vehicles/types/bull.dm
> +	resistances = list("brute"=80,"burn"=80,"emp"=30,"bomb"=50)
Why keep using vehicle_component to manage overall vehicle health? Just integrate that into the base object

2020-04-17 12:59 UTC, caelaislinn commented on code/modules/halo/vehicles/vehicle_component_profiles.dm
> +		return 0
A better way to do this than snowflake variables is to actually track damage on the weapons themselves. That's how a component system should work

2020-04-17 12:59 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase_weaponry.dm
> +	mag_use = locate(magazine_type) in linked_vehicle.ammo_containers
Why not just insert the magazine directly into the weapon? If there are multiple options, let players choose which weapon.

2020-04-17 12:59 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase.dm
> +		hit_mob.Weaken(1) //No damage for now, let's just knock them over.
You know people will be ramming with the intent to do damage. Why not add some?

2020-04-17 12:59 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/melee.dm
> +	sharp = 1
I always hated how these two variables were separate. From memory, sharp induces bleeding while edge has a chance to sever external organs.

2020-04-17 13:02 UTC, X0-11 commented on code/modules/halo/vehicles/types/bull.dm
> +	resistances = list("brute"=80,"burn"=80,"emp"=30,"bomb"=50)
the one reason I saw was that pelicans and air vehicles in general seem to use it heavily because of the fact basic air vics and overmap air vics are two different things due to travel-handling, yet use the same stats.

2020-04-17 13:02 UTC, X0-11 commented on code/modules/halo/vehicles/vehicle_component_profiles.dm
> +		return 0
I'll make sure to keep this in mind when the component system is fully integrated. Such a thing is what Initially planned to eventually happen

2020-04-17 13:04 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase_weaponry.dm
> +	mag_use = locate(magazine_type) in linked_vehicle.ammo_containers
the weapon doesn't actually exist until it's created in the gunner's hand. I did do it as a permenant weapon that is returned to the vehicle but that had issues with the item getting stuck elsewhere and also doesn't support multiple firers with the same weapon on the same position.
Example for when such a thing would happen: Phantom side-guns

2020-04-17 13:05 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase.dm
> +		hit_mob.Weaken(1) //No damage for now, let's just knock them over.
A stun is powerful enough. I am considering damage for the future, I would just rather not implement damage-on-hit just yet.

2020-04-17 13:05 UTC, X0-11 commented on code/modules/halo/weapons/covenant/melee.dm
> +	sharp = 1
edge also allows for throat slitting, which is why I had to change it here.

2020-04-18 01:17 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase_weaponry.dm
> +	mag_use = locate(magazine_type) in linked_vehicle.ammo_containers
That sounds like its users weren't being tracked correctly.

2020-04-18 07:04 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase_weaponry.dm
> +	mag_use = locate(magazine_type) in linked_vehicle.ammo_containers
Manually loading magazines into the weapon also makes it harder to control the flow of ammunition and leaves the system open to stockpiling and abuse.

2020-04-18 07:11 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase.dm
> +		hit_mob.Weaken(1) //No damage for now, let's just knock them over.
Ok. But I think it would be unintuitive, and may leave players disappointed.

2020-04-18 07:11 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase_weaponry.dm
> +	mag_use = locate(magazine_type) in linked_vehicle.ammo_containers
Well, not if the ammo is tracked properly. There will always be edge cases which we don't anticipate and can address in future PRs

2020-04-18 09:48 UTC, caelaislinn approved these changes
Ok I'm going to merge this, partially because #2386 is waiting for it. I know it's not fun or sexy to do refactors and rewrite old code and clean it up, compared to writing new features. But it is still important that it gets done

2020-04-18 09:48 UTC, merged