Ship combat tweak
HaloSpaceStation/HaloSpaceStation13 pull request #2408
Opened 2020-04-26 18:53 UTC by X0-11

:cl: YourName
rscadd: Added a changelog editing system that should cause fewer conflicts and more accurate timestamps.
rscdel: Killed innocent kittens.
/:cl:

2020-04-27 00:25 UTC, caelaislinn requested changes

2020-04-27 00:25 UTC, caelaislinn commented on code/game/turfs/simulated/walls.dm
> +	spawn(100 * (max_health()/wallmat.integrity))
It would be good if there was some player feedback on how long was left. This always irritated me about thermite

2020-04-27 00:25 UTC, caelaislinn commented on maps/UNSC_With_Noble_Cause/presets.dm
> +	req_access = list(786676)
reee magic numbers

2020-04-29 11:33 UTC, X0-11 commented on maps/UNSC_With_Noble_Cause/presets.dm
> +	req_access = list(786676)
😔

2020-04-29 11:33 UTC, X0-11 commented on code/game/turfs/simulated/walls.dm
> +	spawn(100 * (max_health()/wallmat.integrity))
How'd you recommend doing that?

2020-04-29 11:46 UTC, caelaislinn commented on code/game/turfs/simulated/walls.dm
> +	spawn(100 * (max_health()/wallmat.integrity))
Just a to_chat() would be fine and you could probably make it approximate eg rounded to the nearest minute

2020-04-29 11:46 UTC, caelaislinn commented on maps/UNSC_With_Noble_Cause/presets.dm
> +	req_access = list(786676)
I've moved the relevant access defines to code/modules/halo/unsc/access.dm

2020-04-29 16:59 UTC, X0-11 commented
requested changes made

2020-04-30 01:11 UTC, caelaislinn approved these changes

2020-04-30 01:11 UTC, merged