cassius station and the ODP
HaloSpaceStation/HaloSpaceStation13 pull request #2418
Opened 2020-05-05 15:41 UTC by X0-11

:cl: XO-11
Replaces the unsc flagship with Cassius ODP station, refitted to act as a main base of operations.
/:cl:

2020-05-06 10:55 UTC, caelaislinn requested changes

2020-05-06 10:55 UTC, caelaislinn commented on maps/faction_bases/ODP_Cassius/cassius_jobs.dm
> +/decl/hierarchy/outfit/job/cassius_job
I'm trying to standardise jobs, so we have less redundant jobs defined across different map definitions. Are you able to move these into the modules/halo/unsc folder?

2020-05-06 17:45 UTC, X0-11 commented on maps/faction_bases/ODP_Cassius/cassius_jobs.dm
> +/decl/hierarchy/outfit/job/cassius_job
done

2020-05-07 08:47 UTC, caelaislinn approved these changes

2020-05-07 09:56 UTC, merged