Reclamation tweaks and fixes
HaloSpaceStation/HaloSpaceStation13 pull request #2434
Opened 2020-05-21 13:42 UTC by caelaislinn

Various changes as discussed. See commit log. WIP

New Covenant objective list:
- Protect ship
- Protect leader
- Destroy ODP
- Capture colony
- Retrieve artifact

New UNSC objective list:
- Protect leader
- Capture Innies
- Destroy Covenant ship
- Capture colony
- Prevent colony destruction
- Destroy Innie ship

New Innie objective list:
- Protect leader
- Kill UNSC leader
- Destroy ODP
- Capture colony
- Protect Innie ship

:cl: CaelAislinn
rscadd: The ODP Cassius has returned into orbit around Geminus Colony. Unfortunately, the UNSC navy warship no longer patrols this system. 
bugfix: The ODP's automated fire control for the SMAC now applies a cooldown to manually firing the SMAC. 
/:cl:

2020-05-21 15:23 UTC, X0-11 commented on code/modules/halo/overmap/weapons/auto_mac_program.dm
> +		var/obj/machinery/overmap_weapon_console/mac/M = locate() in range(7, host)
couldn't it just do this once and store a reference to the MAC console?

2020-05-21 15:25 UTC, X0-11 commented on code/modules/halo/vehicles/types/boarding_pod.dm
> +	pod_range = 14
Is a buff to supply pod range needed too?

2020-05-21 15:25 UTC, X0-11 commented on code/modules/halo/vehicles/types/boarding_pod.dm
> +	return potential_om_targ
No more boarding beacons? Bold move.

2020-05-21 15:27 UTC, bloxgate requested changes

2020-05-21 15:27 UTC, bloxgate commented on code/modules/halo/vehicles/types/boarding_pod.dm
> +/obj/vehicles/drop_pod/overmap/boarding_pod/get_overmap_targets()
This is a subtype of `/obj/vehicles/drop_pod/overmap`, and appears to be doing the exact same thing as the proc in the parent type. We can probably remove this definition.

2020-05-21 15:28 UTC, X0-11 commented on code/modules/halo/vehicles/types/boarding_pod.dm
> +/obj/vehicles/drop_pod/overmap/boarding_pod/get_overmap_targets()
Does the parent pod search for *all* objects or just ships, because this one seems to be ship limited.

2020-05-21 22:31 UTC, caelaislinn commented on code/modules/halo/overmap/weapons/auto_mac_program.dm
> +		var/obj/machinery/overmap_weapon_console/mac/M = locate() in range(7, host)
This is my concession to trying to switch all consoles over to programs running on modular computers, which needs to handle for being constructed/deconstructed/moved.

2020-05-21 22:32 UTC, caelaislinn commented on code/modules/halo/vehicles/types/boarding_pod.dm
> +	pod_range = 14
No, supply pods are a nice benefit for when you have orbital control.

2020-05-21 22:32 UTC, caelaislinn commented on code/modules/halo/vehicles/types/boarding_pod.dm
> +	return potential_om_targ
Oops I didn't realise that would be an effect of this

2020-05-21 22:33 UTC, caelaislinn commented on code/modules/halo/vehicles/types/boarding_pod.dm
> +/obj/vehicles/drop_pod/overmap/boarding_pod/get_overmap_targets()
This makes boarding pods search explicitly for /ship while all other types search for /sector (ie planets).

2020-05-21 22:34 UTC, bloxgate commented on code/modules/halo/vehicles/types/boarding_pod.dm
> +/obj/vehicles/drop_pod/overmap/boarding_pod/get_overmap_targets()
So it does. My mistake.

2020-05-22 01:20 UTC, bloxgate approved these changes

2020-05-22 18:44 UTC, merged