Reworks phase 2 of Reclamation
HaloSpaceStation/HaloSpaceStation13 pull request #2461
Opened 2020-05-25 17:11 UTC by X0-11

:cl: XO-11
tweak: The ODP has had its windows replaced with the correct, projectile resistant, variant.
tweak: Budget dedicated to drop-pods, boarding pods and supply pods has increased, allowing them their own minature guidance systems.
tweak: The ODP has been secured. Southern umbilicals are one-way, and can only initiated connection, not be connected to.
tweak: Phase two for Reclamation has changed. Covenant forces must deploy and defend scanners, which the unsc will attempt to destroy. The artifact is concealed until the scanner completes, and destruction of a single scanner greatly reduces the scan progress. Destruction of 4 scanners will be marked against the covenant faction's objectives and can contribute towards the reasons for a round-end.
/:cl:

2020-05-26 06:54 UTC, caelaislinn commented
What were the changes here to Geminus?

2020-05-26 06:57 UTC, caelaislinn requested changes

2020-05-26 06:57 UTC, caelaislinn commented on code/modules/halo/covenant/invasion_scanner.dm
> +		gm:unregister_scanner()
Better to grab the current gamemode and do a typecheck

2020-05-26 06:57 UTC, caelaislinn commented on code/datums/repositories/mobs.dm
> +		return INITIALIZE_HINT_QDEL
This has no effect in New() it has to be returned in Initialize()

2020-05-26 06:57 UTC, caelaislinn commented on code/modules/halo/covenant/invasion_scanner.dm
> +	icon_state = "comms"
Can you do a placeholder codersprite instead of using the battlenet transmitter?

2020-05-26 07:30 UTC, X0-11 commented on code/modules/halo/covenant/invasion_scanner.dm
> +		gm:unregister_scanner()
already outdated, it's gm. instead of gm: now

2020-05-26 07:30 UTC, X0-11 commented on code/datums/repositories/mobs.dm
> +		return INITIALIZE_HINT_QDEL
I see. How am I meant to make it delete itself then?

2020-05-26 07:31 UTC, X0-11 commented on code/modules/halo/covenant/invasion_scanner.dm
> +	icon_state = "comms"
the battlenet transmitter works fairly well for the intended thing anyway

2020-05-26 07:31 UTC, X0-11 commented
geminus changes were the addition of scanning points

2020-05-27 00:28 UTC, caelaislinn commented on code/datums/repositories/mobs.dm
> +		return INITIALIZE_HINT_QDEL
Just put the return in Initialize()

2020-05-27 00:29 UTC, caelaislinn commented on code/modules/halo/covenant/invasion_scanner.dm
> +	icon_state = "comms"
The battle transmitter sprite is already being used for the battlenet transmitter sprite

2020-05-27 00:30 UTC, caelaislinn commented on maps/faction_bases/ODP_Cassius/spawnpoint.dm
> +		/datum/job/unsc/oni/research,
Can you fix the indnt?

2020-05-27 06:53 UTC, X0-11 commented on code/modules/halo/covenant/invasion_scanner.dm
> +	icon_state = "comms"
Yeah but it works really well as a deployable scanning array.

2020-05-27 08:11 UTC, caelaislinn approved these changes

2020-05-27 08:34 UTC, merged