fix duplicate ME emote
HaloSpaceStation/HaloSpaceStation13 pull request #253
Opened 2017-04-28 15:44 UTC by bloc97

in /mob/proc/custom_emote,
/atom/proc/visible_message and 
/atom/proc/audible_message
were being duplicated as code

2017-04-29 00:16 UTC, caelaislinn requested changes
Note: Bay12 has more optimised visible_message and audible_message procs which I haven't ported, and it may be good to look into those. There was a critical bug with these procs a while back which I did a hacky fix for and was never satisfied with.

2017-04-29 00:16 UTC, caelaislinn commented on code/modules/mob/say.dm
> +	//world << message //Debug purposes
After you've finished debugging, it's generally better to prevent code clutter by deleting the debug messages than just comment them out

2017-04-29 00:16 UTC, caelaislinn commented on code/modules/mob/emote.dm
> +
Everything from line 35 down looks like duplicate code, and should just be deleted. If an invalid m_type (ie anything that isn't audible or visible) gets passed in, then just quietly fail will be fine.

2017-04-29 00:16 UTC, caelaislinn commented on code/modules/mob/emote.dm
> +				return //Add return to prevent double sending with M.show_message?
Just as a note, switches in byond don't "fall though" ie you dont need a break or return, they will automatically break after resolving the first true case.

2017-04-29 01:58 UTC, bloc97 commented on code/modules/mob/emote.dm
> +				return //Add return to prevent double sending with M.show_message?
yea the return was more to prevent the bottom half of running

2017-05-22 05:11 UTC, caelaislinn approved these changes
ok im happy

2017-05-22 05:11 UTC, caelaislinn commented on code/modules/mob/say.dm
> -
tsk unnecessary line changes :P

2017-05-22 05:11 UTC, merged