less nade choice
HaloSpaceStation/HaloSpaceStation13 pull request #2557
Opened 2020-06-15 07:01 UTC by X0-11

:cl: XO-11
tweak: UNSC NPCs have been informed that players like to both see and hear, sometime this century.
/:cl:

2020-06-15 18:14 UTC, bloxgate approved these changes

2020-06-15 20:00 UTC, bloxgate approved these changes

2020-06-17 08:34 UTC, caelaislinn commented on code/_helpers/unsorted.dm
> +		GLOB.dview_mob = new /mob/dview
:tired_face:

2020-06-17 08:35 UTC, X0-11 commented on code/_helpers/unsorted.dm
> +		GLOB.dview_mob = new /mob/dview
i have no idea what's deleting them and this makes sure it doesn't stay deleted

2020-06-17 08:35 UTC, caelaislinn requested changes

2020-06-17 08:35 UTC, caelaislinn commented on code/modules/halo/unsc/simple_mobs.dm
> +	possible_grenades = list(/obj/item/weapon/grenade/frag/m9_hedp)
Can you make them throw flashbangs on legendary

2020-06-17 08:35 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/ammo.dm
> +#undef FUEL_ROD_MAX_OVERSHOOT
God damn it no things need to be in their own files for readability

2020-06-17 08:36 UTC, X0-11 commented on code/modules/halo/weapons/covenant/ammo.dm
> +#undef FUEL_ROD_MAX_OVERSHOOT
all ammo goes in the ammo file damn it

2020-06-17 08:36 UTC, X0-11 commented on code/modules/halo/unsc/simple_mobs.dm
> +	possible_grenades = list(/obj/item/weapon/grenade/frag/m9_hedp)
yes

2020-06-18 02:47 UTC, merged