Replaces armoury lockers with Gun and Ammo Vendors.
HaloSpaceStation/HaloSpaceStation13 pull request #259
Opened 2017-05-23 15:23 UTC by X0-11

Heavy weapons and normal weapons have been split into 2 vendors.

2017-05-25 03:43 UTC, bloxgate commented
Is this ready for review and merge? Or is there still more coming?

2017-05-25 06:20 UTC, X0-11 commented
Besides alternate sprites for heavy weapons vendors, it's ready for merge.

2017-05-25 07:09 UTC, bloxgate commented
Great I may have to add this soon. We've had quite a bit of lag from the armory lockers being opened.

2017-05-25 21:12 UTC, bloxgate commented
Going to give this a quick once over, then merge it and open an issue for updated sprites if everything is good.

2017-05-25 21:23 UTC, bloxgate requested changes
Mind moving the vending machines into the halo module? It'll help us if we ever merge any future bay updates to vending machines.

2017-05-26 09:56 UTC, caelaislinn approved these changes
I'm not a fan of gun vendors from a gameplay perspective but we don't necessarily have to use them. LGTM

2017-05-26 09:56 UTC, caelaislinn commented on code/game/machinery/vending.dm
> +	//everything after the power cell had no amounts, I improvised.  -Sayu
Unnecessary line change

2017-05-26 10:01 UTC, caelaislinn commented
Map conflict with #260 needs to be resolved now that that one is merged

2017-05-26 10:41 UTC, X0-11 commented
I'll resolve the map conflict once I get home.

2017-05-26 15:17 UTC, X0-11 commented
Not too sure how I'm meant to fix the conflict. I've remapped it using the map from alpha

2017-05-26 16:44 UTC, X0-11 commented
I've borked something. Will open another once I get it to work

2017-05-26 16:44 UTC, closed without merging