Jetpacks and various small changes
HaloSpaceStation/HaloSpaceStation13 pull request #2607
Opened 2020-07-02 14:53 UTC by X0-11

:cl: XO-11
tweak: Donor item boxes have been added. If your box has broken or incorrect gear inside, please contact devs.
rscadd: The concussion rifle has now appeared in the covenant sangheili armory. It relies mostly on direct damage, with a minor AOE damage burst and a concussive impact.
tweak: misplaced armour define on unsc undersuits has been amended
tweak: rocket launchers are now more accurate
rscadd: Jetpacks have now appeared in equipment armories. Ensure a close eye is kept on the power remaining in the jetpack. Whilst it recharges over time when inactive, running out of power whilst mid-air will lead to a heavily damaging fall.
tweak: the covenant Shadow is now slightly faster
tweak: Drones are now slightly slower, as their speed was never lowered to match new elite speeds.
tweak: snipers now have projectile travel time.
/:cl:

2020-07-05 09:40 UTC, caelaislinn requested changes

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/rifles.dm
> +	. = ..()
Did you test this? The parent proc will override any changes if the ..() is at the end of the child proc

2020-07-05 09:40 UTC, caelaislinn commented on code/game/mecha/combat/Hrunting.dm
> -	return
Why was this cut?

2020-07-05 09:40 UTC, caelaislinn commented on code/game/turfs/turf.dm
> +	var/natural_elevation_mod = 0 //People stepping on this turf just get their elevation modified by this amount.
:rolling_eyes: is this necessary?

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/clothing/clothing.dm
> -	playsound(src,stepsound, 15, 1,0,0,1)
Why was this cut?

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/abilities/flight.dm
> +			fall()
We really need a sprite for yanmee when they are using their wings

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/clothing/donor_covenant.dm
> +
Honestly I would prefer the path be the other way round... so grav hammer is a subtype of non-grav hammer.

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/clothing/jetpacks.dm
> +	var/flight_ticks_curr
Initialize at 0 to prevent type change runtimes

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/clothing/jetpacks.dm
> +	action_button_name = "Activate Jump-Jet"
Shouuld we have 2 different types of jetpacks... one is the hover platform from halo 2 rangers, and the other is the jump packs used in reach?

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/abilities/flight.dm
> +	var/flight_ticks_remain = 0 //Movement and life() ticks degrade this. Set by Yanme'e flight and jump-packs
No, this should be controlled by the flight_item not the mob. If you need to, add a helper proc to the mob to get the active flight item

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/abilities/flight.dm
> +		flight_item.flight_bar.update(flight_ticks_remain)
This should also be in flight_item I think

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/clothing/jetpacks.dm
> +	var/active = 0
You can use TRUE and FALSE defines as 1 and 0 for boolean vars

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/clothing/jetpacks.dm
> +	GLOB.processing_objects -= src
Why does this stop processing here? Is it supposed to let the mob take over processing?

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/clothing/jetpacks.dm
> +		flight_bar = new(user,flight_ticks_max,src)
Love it. Consider doing a obj/hud and putting it at the top of the screen underneath where a shield bar would be if I stopped being lazy

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/clothing/jetpacks.dm
> +		activate(usr)
Good

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/clothing/jetpacks.dm
> +		GLOB.processing_objects -= src
Shouldn't this trigger a deactivation or something? Also consider doing a fall() in case the user is over open space

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/weapon/grav_hammer/gravless = 6,
Perhaps just 1 for captains, considering in lore they are traditional weapons and only given to great warriors

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/flight_item/covenant_pack = 2,
BTW did you check for sprite offsets looking ok on all the different cov races? Grunts with jetpacks is a scary thought

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/weapons/ammo.dm
> +		src.fragmentate(get_turf(loc), 50, 7, list(/obj/item/projectile/bullet/pellet/fragment = 1)) //Loc not target, we don't explode *in* them we explode *on* them
This is awful. Explosive ammo should be purely extra damage, not an aoe. SRS is already strong

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/ammo.dm
> +			mob.adjustFireLoss(aoe_damage)
This is going to mean that anyone hit by the projectile gets damaged twice... once by direct impact and a second time by aoe damage. Is that intended?

2020-07-05 09:40 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/brute.dm
> +	if(!special_afterattack)
This should just be a proc override, not a new var

2020-07-05 09:42 UTC, X0-11 commented on code/modules/clothing/clothing.dm
> -	playsound(src,stepsound, 15, 1,0,0,1)
system genericised to a /living mob Move() effect

2020-07-05 09:43 UTC, X0-11 commented on code/game/mecha/combat/Hrunting.dm
> -	return
Tankier mechs = no need for speed

2020-07-05 09:43 UTC, X0-11 commented on code/modules/halo/weapons/covenant/rifles.dm
> +	. = ..()
thanks for catching that

2020-07-05 09:43 UTC, X0-11 commented on code/game/turfs/turf.dm
> +	var/natural_elevation_mod = 0 //People stepping on this turf just get their elevation modified by this amount.
probably not?

2020-07-05 09:43 UTC, X0-11 commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/flight_item/covenant_pack = 2,
they're passable on most species, and can be tweaked further if needed

2020-07-05 09:44 UTC, X0-11 commented on code/modules/halo/weapons/ammo.dm
> +		src.fragmentate(get_turf(loc), 50, 7, list(/obj/item/projectile/bullet/pellet/fragment = 1)) //Loc not target, we don't explode *in* them we explode *on* them
this is a frag underslung grenade

2020-07-05 09:44 UTC, X0-11 commented on code/modules/halo/weapons/covenant/ammo.dm
> +			mob.adjustFireLoss(aoe_damage)
yes, the AOE damage is incredibly low, and this damage is applied directly to the mob instead of factoring in armour etc

2020-07-05 09:44 UTC, X0-11 commented on code/modules/halo/weapons/covenant/brute.dm
> +	if(!special_afterattack)
good point

2020-07-05 09:46 UTC, X0-11 commented on code/modules/halo/abilities/flight.dm
> +			fall()
I don't think player mobs really support that

2020-07-05 09:47 UTC, X0-11 commented on code/modules/halo/clothing/jetpacks.dm
> +	action_button_name = "Activate Jump-Jet"
I don't think it's really needed

2020-07-05 09:47 UTC, X0-11 commented on code/modules/halo/abilities/flight.dm
> +	var/flight_ticks_remain = 0 //Movement and life() ticks degrade this. Set by Yanme'e flight and jump-packs
This is to support non-human-mob flight

2020-07-05 09:47 UTC, X0-11 commented on code/modules/halo/clothing/jetpacks.dm
> +	GLOB.processing_objects -= src
When they take off, they should stop regenerating fuel

2020-07-05 09:49 UTC, X0-11 commented on code/modules/halo/clothing/jetpacks.dm
> +		GLOB.processing_objects -= src
No, this is regenerating fuel, not depleting

2020-07-05 09:50 UTC, X0-11 commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/weapon/grav_hammer/gravless = 6,
I can give captains an actual grav-hammer if you'd like, I think the gravless ones should be fine as melee options

2020-07-05 09:53 UTC, X0-11 commented on code/modules/halo/clothing/donor_covenant.dm
> +
Is there anything that'd stop me from swapping the paths easily?

2020-07-05 09:54 UTC, caelaislinn commented on code/game/mecha/combat/Hrunting.dm
> -	return
It's still a nice customisation feature, maybe we could add upgraded legs that let you overload it

2020-07-05 10:03 UTC, X0-11 commented on code/game/mecha/combat/Hrunting.dm
> -	return
I don't think it's a good idea unless it comes with a hefty armour nerf too. Mechs can resist a fair bit of gunfire, don't slow down from any damage and all "internal" damage caused to them can iirc be fixed from inside the mech, so no exposure to gunfire. Destruction of a mech also leaves the occupant unharmed.

2020-07-05 11:22 UTC, Delnth commented on code/modules/halo/abilities/flight.dm
> +			fall()
Animated mask, perhaps?

2020-07-05 12:44 UTC, caelaislinn commented on code/game/mecha/combat/Hrunting.dm
> -	return
Can you change it to a proc instead so that it's inaccessible, but the code is still there in case we want to readd it later?

2020-07-05 12:45 UTC, X0-11 commented on code/game/mecha/combat/Hrunting.dm
> -	return
Sure.

2020-07-05 15:01 UTC, caelaislinn commented on code/modules/halo/abilities/flight.dm
> +			fall()
It would be easy enough to do via the mob overlay code for external organs

2020-07-05 15:02 UTC, caelaislinn commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/weapon/grav_hammer/gravless = 6,
They should be rare though, and visually there is no easy cue for UNSC players whether it is a gravhammer or not and it's a rare special weapon in the lore

2020-07-05 15:07 UTC, X0-11 commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/weapon/grav_hammer/gravless = 6,
fair, it could do with a different sprite. Want me to remove them until I get one?

2020-07-05 15:11 UTC, caelaislinn commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/weapon/grav_hammer/gravless = 6,
Could you do a codersprite with active and inactive overlay? Like blue lights or something

2020-07-05 15:13 UTC, X0-11 commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/weapon/grav_hammer/gravless = 6,
Could do. I'll see if I can get a better sprite first

2020-07-05 17:54 UTC, X0-11 commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> +	/obj/item/weapon/grav_hammer/gravless = 6,
Glowy bits removed from sprite for the grav-less version

2020-07-05 17:55 UTC, X0-11 commented on code/modules/halo/abilities/flight.dm
> +			fall()
Best choice would to be integrating it with the chest sprite then, I think

2020-07-06 01:56 UTC, caelaislinn approved these changes

2020-07-06 01:59 UTC, merged