Adds Covie Weapons
HaloSpaceStation/HaloSpaceStation13 pull request #262
Opened 2017-05-25 19:11 UTC by X0-11

With fire sounds:
Needler
Plasma Pistol

Fire sounds needed:
Plasma Rifle

Plasma Pistol has a way to switch between normal and overcharge, doing increased damage.
Energy Sword has a deploy sound.

2017-05-26 10:02 UTC, caelaislinn requested changes

2017-05-26 10:02 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/ammo.dm
> +	accuracy = 1
Add placeholder sprites please

2017-05-26 10:02 UTC, caelaislinn commented on code/modules/projectiles/gun.dm
> +u/*
Compile error from mis-key

2017-05-26 10:02 UTC, caelaislinn commented on code/modules/projectiles/gun.dm
> +
Unnecessary line change

2017-05-26 10:53 UTC, X0-11 commented on code/modules/halo/weapons/covenant/ammo.dm
> +	accuracy = 1
Will do. I'll do it once home.

2017-05-26 15:15 UTC, X0-11 commented
Sprites added for projectiles

2017-05-27 01:05 UTC, caelaislinn approved these changes

2017-05-27 01:05 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/ammo.dm
> +	desc = "A searing hot bolt of plasma."
I dislike leaving "ghost" objects like this in SS13. C++ calls this an abstract virtual class but in Byond we don't have any protections against other people misusing it plus it clutters up the path tree. 

What I do it instead is choose a base object (usually the simplest and most commonly reused subtype of the object) then descend children off it. This is just a coding convention though so it won't block merging

2017-05-27 01:06 UTC, merged