various vehicle fixes and tweaks
HaloSpaceStation/HaloSpaceStation13 pull request #2629
Opened 2020-07-08 13:55 UTC by X0-11

:cl: XO-11
tweak: Banshees and sparrowhawks now have the correct faction assigned.
tweak: vehicles remember to update your last known z-level, so you don't get deleted due to previously being on a ship / on the odp after exiting via vehicle
/:cl:

2020-07-08 14:53 UTC, caelaislinn requested changes

2020-07-08 14:53 UTC, caelaislinn commented on code/modules/halo/vehicles/types/banshee.dm
> +	faction = "covenant"
Needs capitals

2020-07-08 14:53 UTC, caelaislinn commented on code/modules/halo/vehicles/types/sparrowhawk.dm
> +	faction = "unsc"
Needs capitalised

2020-07-08 14:59 UTC, X0-11 commented on code/modules/halo/vehicles/types/sparrowhawk.dm
> +	faction = "unsc"
doesn't, the pelican doesn't have it and this is directly copied

2020-07-08 15:01 UTC, caelaislinn commented
A destroyed hawk (presumably banshee as well) also doesnt reset view range

2020-07-08 15:03 UTC, X0-11 commented
Last I checked they reset when you exit the vehicle

2020-07-08 15:03 UTC, caelaislinn commented
This is a report from the server just now

2020-07-09 01:13 UTC, caelaislinn requested changes
Brute beards should also be in a separate PR

2020-07-09 01:13 UTC, caelaislinn commented on maps/_gamemodes/firefight/subtypes/crusade.dm
> +		"T-Vaoan Champion")
This is still broken, it will need to be changed to `"T\'vaoan Champion"`

2020-07-09 01:14 UTC, caelaislinn requested changes

2020-07-09 01:14 UTC, caelaislinn commented on code/modules/halo/covenant/jobs/sangheili.dm
> +	spawn_positions = 4
Can you leave these uncapped please

2020-07-09 06:10 UTC, X0-11 commented on code/modules/halo/covenant/jobs/sangheili.dm
> +	spawn_positions = 4
This isn't an oversight? Isn't infinite elites very powerful?

2020-07-09 06:25 UTC, X0-11 commented on maps/_gamemodes/firefight/subtypes/crusade.dm
> +		"T-Vaoan Champion")
The job uses the - version because in testing even the escaped ' version broke the system

2020-07-09 07:06 UTC, caelaislinn commented on code/modules/halo/covenant/jobs/sangheili.dm
> +	spawn_positions = 4
I think it's fine. I'd rather have consistent access to a "leader" throughout the round rather than only a few which die then aren't seen again

2020-07-09 07:11 UTC, X0-11 commented on code/modules/halo/covenant/jobs/sangheili.dm
> +	spawn_positions = 4
I feel like infinite elites is very powerful. Couldn't we set the cap low( say, 2?) and make them re-open on death? Should I do that for brutes too?

2020-07-09 07:24 UTC, caelaislinn commented on code/modules/halo/covenant/jobs/sangheili.dm
> +	spawn_positions = 4
There's practically no difference right now, but that's fine. If you do, then also change brute minors to match for consistency's sake

2020-07-10 03:01 UTC, caelaislinn requested changes

2020-07-10 03:01 UTC, caelaislinn commented on code/modules/halo/covenant/jobs/jiralhanae.dm
> +	open_slot_on_death = 1 //Lowest rank of a leader caste can respawn indefinitely although still capped low
Job slot changes should be in a separate commit

2020-07-10 03:01 UTC, caelaislinn commented on maps/faction_bases/complex046/complex046.dmm
> +aafhacacadafafagafafaafpalaqacacacaiajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajaa
What's this for?

2020-07-10 03:01 UTC, caelaislinn commented on maps/geminus_city/geminuscity_1.dmm
> +coaaaaaaaaaaaaaaaacjcjcjcjcjcjcjcjcjcjcjcjcjcjcjcjcjcjcjcjcjbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgcjcjcjcjcjcjcjcjbgbgbgbgbbbxbxbxbxbxbxbxbxbxbxbxbxbbbbbbbbbbadbXaebYafaibIadadadaddqadadada
Yeah I honestly don't know why the open space-stairs unit test was pinging on this one. I have a vague theory it was related to zlevel connection but I dug through it a dozen times now and found nothing

2020-07-10 03:02 UTC, caelaislinn commented on code/modules/halo/vehicles/types/sparrowhawk.dm
> +	faction = "unsc"
The convention in all the faction code is to use capitals, so it will fail the faction checks. Why are you giving vehicles a faciton anyway?

2020-07-10 06:05 UTC, X0-11 commented on maps/faction_bases/complex046/complex046.dmm
> +aafhacacadafafagafafaafpalaqacacacaiajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajaa
Tweaking the unsc armory a bit

2020-07-10 06:06 UTC, X0-11 commented on code/modules/halo/vehicles/types/sparrowhawk.dm
> +	faction = "unsc"
To decide what waypoints the vehicle is allowed to fly to

2020-07-10 06:23 UTC, X0-11 commented on code/modules/halo/covenant/jobs/jiralhanae.dm
> +	open_slot_on_death = 1 //Lowest rank of a leader caste can respawn indefinitely although still capped low
My bad, sorry

2020-07-10 06:39 UTC, caelaislinn commented on maps/faction_bases/complex046/complex046.dmm
> +aafhacacadafafagafafaafpalaqacacacaiajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajaa
Oh the great Sofa Update:tm:

2020-07-10 06:39 UTC, caelaislinn commented on code/modules/halo/covenant/jobs/jiralhanae.dm
> +	open_slot_on_death = 1 //Lowest rank of a leader caste can respawn indefinitely although still capped low
It's ok it's just when you put a million different changes in one PR they all get held up if there is an issue or question about any of them

2020-07-10 06:40 UTC, caelaislinn commented on code/modules/halo/vehicles/types/sparrowhawk.dm
> +	faction = "unsc"
Hmm, does the waypoint code use capitalised version or lowercase?

2020-07-10 06:42 UTC, X0-11 commented on code/modules/halo/vehicles/types/sparrowhawk.dm
> +	faction = "unsc"
Lowercase, these faction defines are copied straight from relevant vehicles

2020-07-10 06:44 UTC, caelaislinn commented on code/modules/halo/vehicles/types/sparrowhawk.dm
> +	faction = "unsc"
Ok well leave it as lowercase for now then, but at some point we'll need to standardise vehicles and factions to use upper case

2020-07-10 06:45 UTC, caelaislinn approved these changes

2020-07-10 06:45 UTC, merged