Overmap radio communications and miscellaneous tweakfixes
HaloSpaceStation/HaloSpaceStation13 pull request #265
Opened 2017-05-27 11:41 UTC by caelaislinn

This is a major PR with a large amount of content. In a professional workflow it would be split up into at least 2 separate pull requests. 

The new radio features are: 

- Radio signals no longer require tcomms machinery and instead have an overmap send and receive range set on a per radio basis. As signals approach the maximum distance, the signal quality decreases linearly. 
- Numerous Earth languages have been added with fake text based on common syllables. Some tweaks to help languages work better over the radio. 
- Radio channels and encryptions are now linked via the encryption key. This lays the groundwork for both custom radio channels later and hacking/decrypting/listening in to radio channels

Tweakfixes: 
- HUD button while in a fighter to remotely cycle airlocks
- Latespawn now properly announces over radio and is forced to cryo
- Fixes misc sprite issues, adds some sprites and cleans up some sprite folders
-  Potentially addresses some issues with sensors and observing space while in fighters. 
- People can't hide in wall lockers

2017-05-27 20:34 UTC, bloxgate requested changes

2017-05-27 20:34 UTC, bloxgate commented on code/game/machinery/telecomms/broadcaster.dm
> +		var/part_a = "<span class='[message_css]'><b>\[[freq_text]\]</b> <span class='name'>"
This breaks CI. You need to have all your tags actually closed in the same string as I understand it.

2017-05-27 20:34 UTC, bloxgate commented on code/game/machinery/telecomms/broadcaster.dm
> +		var/part_a = "<span class='radio'><b>\[[display_freq]\]</b> <span class='name'>"
Breaks CI

2017-05-28 06:48 UTC, caelaislinn commented on code/game/machinery/telecomms/broadcaster.dm
> +		var/part_a = "<span class='[message_css]'><b>\[[freq_text]\]</b> <span class='name'>"
Radio message strings are split up into parts for modular formatting and content. This is legacy code and Travis has an exception for it... i think...

2017-05-28 07:13 UTC, caelaislinn commented on code/game/machinery/telecomms/broadcaster.dm
> +		var/part_a = "<span class='[message_css]'><b>\[[freq_text]\]</b> <span class='name'>"
Ok so there's no exception but the way the <span> tags are left open is deliberate and safe so failing travis over them isn't an issue (the closing </span> tag is added to the radio message string in another proc which Travis didn't pick up because it's probably unchanged).

2017-05-28 08:37 UTC, bloxgate commented on code/game/machinery/telecomms/broadcaster.dm
> +		var/part_a = "<span class='[message_css]'><b>\[[freq_text]\]</b> <span class='name'>"
I'm still against adding any code that would break CI like this does. I have a feeling it'll cause problems in the future.

2017-05-29 11:22 UTC, caelaislinn commented on code/game/machinery/telecomms/broadcaster.dm
> +		var/part_a = "<span class='[message_css]'><b>\[[freq_text]\]</b> <span class='name'>"
This is functional legacy code that predates the existence of Travis. To "fix" it I would have to restructure the system and potentially introduce new bugs. Travis helps by highlighting potential issues. It is not a replacement for maintainers making a judgement call on the code in question.

2017-05-30 00:59 UTC, bloxgate commented on code/game/machinery/telecomms/broadcaster.dm
> +		var/part_a = "<span class='[message_css]'><b>\[[freq_text]\]</b> <span class='name'>"
I think if you just add a variable with 4 </span>'s in it, it'll make travis happy.

2017-06-03 22:28 UTC, bloxgate approved these changes

2017-06-03 22:29 UTC, bloxgate commented
I don't know that much about the comms code in the first place, but from what I've seen and heard this has been working without errors, so LGTM.

2017-06-03 23:48 UTC, caelaislinn commented
Adding an unused var holding 4 closing span tags is not an appropriate fix. Let's get a merge so I can update the trackers

2017-06-04 03:16 UTC, merged