Elite mobs, Elite combat harnesses and shields. Many other misc tweaks/fixes.
HaloSpaceStation/HaloSpaceStation13 pull request #268
Opened 2017-05-31 23:14 UTC by X0-11

Adds elite mobs.
Adds Elite Combat Harnesses, with inbuilt shields.
Adds Sangheili species.
Adds Sangheili language.
Tweaks needler to do less damage, but cause an explosion when embedded 5 times.
Adds an EMP effect to the plasma pistol's overcharge shot.
Fixes Energy Sword inhands.
Plasma rifles have higher damage, lower amount of shots. Restricted to 3 shot burstfire.
Attack sounds for Energy swords.
Moves Mk V Helm to misc folder.

2017-05-31 23:19 UTC, bloxgate requested changes
You're missing a define for the Sangheili language. Take a look at the language defines file for some examples.

2017-05-31 23:27 UTC, bloxgate requested changes

2017-05-31 23:27 UTC, bloxgate commented on code/__defines/species_languages.dm
> +#define LANGUAGE SANGHEILI "Sangheili"
That shouldn't have a space

2017-05-31 23:28 UTC, X0-11 commented on code/__defines/species_languages.dm
> +#define LANGUAGE SANGHEILI "Sangheili"
Done. Sorry.

2017-05-31 23:34 UTC, bloxgate requested changes

2017-05-31 23:34 UTC, bloxgate commented on code/modules/halo/clothing/misc.dm
> +	armor = list(melee = 50,bullet = 15,laser = 50,energy = 10,bomb = 25,bio = 0,rad = 0)
Is this actually better than the marine one? I thought the marine one was stronger than this.

2017-05-31 23:34 UTC, bloxgate commented on code/modules/mob/living/carbon/human/species/outsider/sangheili.dm
> +	radiation_mod = 0.6 //Covie weapons emit beta radiation. Resistant to 1/3 types of radiation.
That's not how this works. SS13 only has one type of radiation, 33% resistance only means they take 66% of normal radiation damage. They could still get poisoned.

2017-05-31 23:34 UTC, bloxgate commented on code/modules/halo/misc/sangheili.dm
> +		heart.damage = 0;src.name = "Used Secondary Heart";used = 1
Not really sure how I feel about this. Are there other ways that might work better?

2017-05-31 23:39 UTC, X0-11 commented on code/modules/halo/clothing/misc.dm
> +	armor = list(melee = 50,bullet = 15,laser = 50,energy = 10,bomb = 25,bio = 0,rad = 0)
Just copied the stats from the old one.

2017-05-31 23:39 UTC, X0-11 commented on code/modules/mob/living/carbon/human/species/outsider/sangheili.dm
> +	radiation_mod = 0.6 //Covie weapons emit beta radiation. Resistant to 1/3 types of radiation.
I know. Just wanted to give my reasoning behind the number

2017-05-31 23:41 UTC, X0-11 commented on code/modules/halo/misc/sangheili.dm
> +		heart.damage = 0;src.name = "Used Secondary Heart";used = 1
The secondary heart isn't vital, it could always just be deleted.

2017-06-01 07:38 UTC, caelaislinn requested changes
/datum/harnessspecials needs to be expanded into a complete interface pattern, some other tweaks

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/armourspecials.dm
> +/datum/harnessspecials/cloaking
If you leave blank definitions like this, it's generally a good idea to leave a comment explaining why they're a placeholder.

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	"'Zusov","'Srangam","'Wakam","'Hantakee","'Muramai","'Haham","'Waram","'Ronam")
These need to transferred to a txt file and loaded following the conventions in code\names.dm

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	syllables = list("nnse","nee","kooree","keeoh","cheenoh","rehmah","nnteh","hahdeh","nnrah","kahwah","ee","hoo","roh","usoh","ahnee","ruh","eerayrah","sohruh","eesah")
WORT WORT WORT

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	if(/datum/harnessspecials/shields in specials)
This isn't the ideal to do this. Check out the interface design pattern and poke me on discord if you need help implementing it

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	if(/datum/harnessspecials/shields in specials)
Should be interfaced

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	if(/datum/harnessspecials/shields in specials) //Needed to set the shield capacity.
Should be interfaced

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	if(/datum/harnessspecials/shields in specials)
Should be interfaced

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +		heart.damage = 0;src.name = "Used Secondary Heart";used = 1
You are probably going to tweak the medical code to handle multiple oxygen -> blood processing organs. Anything else would be a hack

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	if(m.vessel.get_reagent_amount("blood") < m.vessel.total_volume)
proc/add_reagent() already does this check

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/ammo.dm
> +			explosion(L.loc,0,1,2,5)
Halo 1 PTSD full clip of needles stronker than frag grenade...

... we'll see how it goes ;D

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +		heart.damage = 0;src.name = "Used Secondary Heart";used = 1
Check out code\modules\mob\living\carbon\human\life.dm and proc/handle_heartbeat()

2017-06-01 07:38 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/melee.dm
> +		clean_blood()
Set src.flags & NOBLOODY because the code can already handle this

2017-06-01 08:42 UTC, bloxgate commented on code/modules/halo/misc/sangheili.dm
> +		heart.damage = 0;src.name = "Used Secondary Heart";used = 1
This organ doesn't really convert oxygen to blood though. It heals the real heart, and replaces blood lost to cuts.

2017-06-01 09:47 UTC, X0-11 commented on code/modules/halo/misc/sangheili.dm
> +		heart.damage = 0;src.name = "Used Secondary Heart";used = 1
Yeah. It's not meant to actually act as a second heart.

2017-06-01 10:04 UTC, caelaislinn requested changes

2017-06-01 10:04 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	processing_objects += src // Needed for the shield recharge.
To minimise CPU usage, only add it to processing_objects when it needs to recharge, and remove it when its finished.

2017-06-01 11:12 UTC, X0-11 commented on code/modules/halo/weapons/covenant/ammo.dm
> +			explosion(L.loc,0,1,2,5)
The embed chance isn't 100%, so it does take more than 5 shots to cause an explosion

2017-06-02 09:11 UTC, caelaislinn commented on code/modules/halo/misc/armourspecials.dm
> +			shieldstrength = totalshields/2
This will behave unintuitively for the player. It's probably better to just reduce it by a flat amount regardless of current shield levels eg 50% of max.

2017-06-02 09:18 UTC, X0-11 commented on code/modules/halo/misc/armourspecials.dm
> +			shieldstrength = totalshields/2
It does...

2017-06-02 09:26 UTC, caelaislinn requested changes
Still some snowflake checks for /harnessspecials/shields

2017-06-02 09:26 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	name += pick(last_names_sangheili)
Just a lore point here, all Sangheili warriors sworn to the Covenant (required for males when they come of age) gain the honorary suffix 'ee' at the end of their surnames. For now we can just assume with all gamemodes that all Sangheili are part of the Covenant so all Sangheili surnames will need the 'ee' suffix

2017-06-02 09:26 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	syllables = list("wort","nnse","nee","kooree","keeoh","cheenoh","rehmah","nnteh","hahdeh","nnrah","kahwah","ee","hoo","roh","usoh","ahnee","ruh","eerayrah","sohruh","eesah")
Blocker: needs REEEEEEEEEEEEEEEEEEEE here

2017-06-02 09:26 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +			sh = new i(totalshields,src)
This doesn't need a custom type check. Pass in src here to the New() for every single instance of /harnessspecials and let the ones that don't need it just ignore it. Then in /harnessspecials/shields just grab the var/totalshields from the combatharness

2017-06-02 09:26 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +		return sh.handle_shield(m,damage,damage_source)
Pass this to all instances of /harnessspecial and let the ones that don't need it just ignore it

2017-06-02 09:26 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +	if(sh)
Let the /harnessspecials handle their own processing, there is no need for the /combatharness to do it for them

2017-06-02 09:26 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +		sh.tryemp(severity)
Loop over all instances of /harnessspecial because we want EMPs to affect cloak and jetpack as well

2017-06-02 09:26 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
>  	var/datum/harnessspecials/shields/sh
Remove this variable and rewrite it so that it's not needed

2017-06-02 09:30 UTC, X0-11 commented on code/modules/halo/misc/sangheili.dm
>  	var/datum/harnessspecials/shields/sh
were it so easy... :)

2017-06-03 14:34 UTC, X0-11 commented
Oh. I think I see what I did... I forgot to switch branches before updating my alpha fork. Let me just redo this PR.

2017-06-03 14:34 UTC, closed without merging

2017-06-03 14:39 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +		testvar = "true"
?

2017-06-03 14:39 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +		specials += new i (src)
Good thinking but this is generally a little risky. I prefer to split spawn types into a separate list just in case.