adds a few more calls to update_occupant_z_level()
HaloSpaceStation/HaloSpaceStation13 pull request #2686
Opened 2020-07-18 16:55 UTC by X0-11

should help with vehicles deleting all their occupants for fun and profit

2020-07-25 09:52 UTC, caelaislinn commented on code/modules/emotes/definitions/audible.dm
> -	emote_message_3p = "USER worts, three times.!"
triggered

2020-07-25 09:53 UTC, X0-11 commented on code/modules/emotes/definitions/audible.dm
> -	emote_message_3p = "USER worts, three times.!"
*wort

2020-07-25 09:53 UTC, caelaislinn commented on code/modules/halo/emotes/emotes.dm
> +	emote_message_3p = "USER worts, three times.!"
STILL TRIGGERED

2020-07-25 09:53 UTC, X0-11 commented on code/modules/halo/emotes/emotes.dm
> +	emote_message_3p = "USER worts, three times.!"
*wort2

2020-07-25 09:54 UTC, caelaislinn requested changes
why did you pull shit out of the armoury?

2020-07-25 09:55 UTC, X0-11 commented
they were placed into loadout boxes but the vendors are still there to hold minor nonrestricted stuff

2020-07-25 09:56 UTC, caelaislinn commented on code/modules/halo/emotes/emotes.dm
> +	emote_message_3p = "USER worts, three times.!"
.!

2020-07-25 09:56 UTC, X0-11 commented on code/modules/halo/emotes/emotes.dm
> +	emote_message_3p = "USER worts, three times.!"
oh that's what you were triggered at

2020-07-25 10:08 UTC, X0-11 commented
errant punctuation fixed

2020-07-27 03:53 UTC, caelaislinn commented
Where are the loadouts actually defined? I don't like the idea

2020-07-27 03:54 UTC, caelaislinn commented
#2684 #2685

2020-07-27 09:12 UTC, X0-11 commented
I would rather provide greater weapon variety overall through loadouts whilst restricting OP weapon combos form forming than just placing the weapons in the vendors.

2020-07-28 11:28 UTC, caelaislinn submitted a review, later dismissed
Can you remove the loadout stuff from this PR, then put it into a new PR by itself?

2020-07-28 11:38 UTC, X0-11 commented
Would rather not, it addresses a problem that the covenant has brought up multiple times recently and thus seems fairly critical to address.

2020-07-28 11:40 UTC, caelaislinn commented
It's a significant feature, and a significant change to the existing system as well. I'd like to go through it without holding up the other stuff in this PR

2020-07-28 11:45 UTC, X0-11 commented
Multiple changes were made to the mapfile which have had further changes layered ontop of them. I'm unsure how to cleanly decouple the two without flat out redoing it all.

2020-07-28 11:51 UTC, caelaislinn commented
What are the other changes you made to the CRS?

2020-07-28 11:53 UTC, X0-11 commented
various map modifications to add and move some stuff that's pod related iirc. Those are the changes I remember, but I'm not entirely sure.

2020-07-28 12:02 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase.dm
> +	update_occupant_z_level(newloc.z)
This should only be necessary when moving up or down a zlevel, or when doing an overmap move

2020-07-28 12:30 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase.dm
> +	update_occupant_z_level(newloc.z)
What about when traversing z-levels through bumptele?

2020-07-28 12:35 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase.dm
> +	update_occupant_z_level(newloc.z)
Add something in the bumptele code to tell the vehicle to update their passenger zlevel

2020-07-28 12:36 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase.dm
> +	update_occupant_z_level(newloc.z)
Will do.

2020-07-31 08:49 UTC, caelaislinn approved these changes

2020-07-31 08:49 UTC, merged