Elite mobs, Elite combat harnesses and shields. Many other misc tweaks/fixes.
HaloSpaceStation/HaloSpaceStation13 pull request #275
Opened 2017-06-03 16:06 UTC by X0-11

Adds elite mobs.
Adds Elite Combat Harnesses, with inbuilt shields.
Adds Sangheili species.
Adds Sangheili language.
Tweaks needler to do less damage, but cause an explosion when embedded 5 times.
Adds an EMP effect to the plasma pistol's overcharge shot.
Plasma rifles have higher damage, lower amount of shots. Restricted to 3 shot burstfire.
Attack sounds for Energy swords.
Moves Mk V Helm to misc folder.
Fixes floorsign layers. Because it annoyed me.
-----Fixing mistakes in previous PRs------
Stops armoury APC from losing power.
Add light to medical staircase.
Removes stray light from armoury front.

2017-06-04 00:00 UTC, caelaislinn commented on code/modules/halo/misc/armourspecials.dm
> +/datum/harnessspecials/shields/New(var/obj/item/clothing/suit/armor/combatharness/c) //Needed the type path for typecasting to use the totalshields var.
A note about conventions here: in other languages you will need to declare this specific combination of proc name and arguments (called an "overload") in the parent object /datum/harnessspecials. 

Don't worry about doing it here because Byond handles it fine this way and we get to cut down on code bloat a little.

2017-06-04 00:27 UTC, caelaislinn requested changes

2017-06-04 00:27 UTC, caelaislinn commented on code/modules/halo/misc/armourspecials.dm
> +	user = m
This should be set elsewhere, we shouldn't need to reset it every time our shields take a ding

2017-06-04 00:27 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +		specials += new i (src)
This is fine but just bear in mind it will behave unintuitively and may introduce a memory leak if you are playing around var editting it at runtime.

2017-06-04 00:55 UTC, caelaislinn approved these changes

2017-06-04 00:55 UTC, caelaislinn commented on code/modules/halo/misc/sangheili.dm
> +		return
There's a chance future bugs will be introduced by not unsetting this when the armour is unequipped, but far as I can tell it's safe for now.

2017-06-04 02:48 UTC, bloxgate requested changes

2017-06-04 02:48 UTC, bloxgate commented on code/modules/halo/clothing/misc.dm
> +	icon = 'code/modules/halo/icons/Mrk V Spartan Helmet.dmi'
This really won't work well. There is a reason that all the other clothing doesn't use their own files.

2017-06-04 02:48 UTC, bloxgate commented on code/modules/halo/misc/sangheili.dm
> +	syllables = list("ree","wort","nnse","nee","kooree","keeoh","cheenoh","rehmah","nnteh","hahdeh","nnrah","kahwah","ee","hoo","roh","usoh","ahnee","ruh","eerayrah","sohruh","eesah")
wort wort wort? Why just a single wort?

2017-06-04 02:48 UTC, bloxgate commented on code/modules/halo/misc/sangheili.dm
> +	if(damage>=min_broken_damage)
I don't think this is necessary. Isn't the decision to call process() handled somewhere else in mob code?

2017-06-04 02:48 UTC, bloxgate commented on code/modules/halo/weapons/covenant/melee.dm
> +		throwforce = 12
So do we have code for chucking this like a throwing knife as a last ditch attack?

2017-06-04 07:30 UTC, X0-11 commented on code/modules/halo/weapons/covenant/melee.dm
> +		throwforce = 12
I can either have it deactivate when thrown, or allow it to function like a normal thrown object. Embec chance included.

2017-06-04 07:40 UTC, X0-11 commented on code/modules/halo/misc/sangheili.dm
> +	if(damage>=min_broken_damage)
We need specialised effects for this organ though.

2017-06-04 08:01 UTC, X0-11 commented on code/modules/halo/clothing/misc.dm
> +	icon = 'code/modules/halo/icons/Mrk V Spartan Helmet.dmi'
You sure? I've had it work for me.

2017-06-04 08:25 UTC, bloxgate commented on code/modules/halo/misc/sangheili.dm
> +	if(damage>=min_broken_damage)
Well looks like I was wrong. But the code is still unnecessary there are is_bruised() and is_broken() procs available.

2017-06-04 08:26 UTC, bloxgate commented on code/modules/halo/weapons/covenant/melee.dm
> +		throwforce = 12
Ah yeah, swords turn off when dropped don't they. Never mind then.

2017-06-04 08:26 UTC, bloxgate commented on code/modules/halo/clothing/misc.dm
> +	icon = 'code/modules/halo/icons/Mrk V Spartan Helmet.dmi'
Yeah. In previous tests when the clothing icons were not in the exact right place they'd often not show up in a lot of situations. Such as showing on the ground fine, but having placeholder icons from 2007 and such if you tried to wear them.

2017-06-04 09:07 UTC, X0-11 commented on code/modules/halo/weapons/covenant/melee.dm
> +		throwforce = 12
Nah, these one's don't. Only Eswords have that as a feature

2017-06-04 09:18 UTC, caelaislinn commented on code/modules/halo/clothing/misc.dm
> +
Watch out for these unnecessary line changes

2017-06-05 01:25 UTC, bloxgate commented on code/modules/halo/weapons/covenant/melee.dm
> +		throwforce = 12
In H1 the swords would turn off/self destruct if dropped.

2017-06-05 01:26 UTC, bloxgate requested changes

2017-06-05 01:26 UTC, bloxgate commented on code/modules/halo/clothing/misc.dm
> +	icon_override = 'code/modules/halo/icons/Mrk V Spartan Helmet.dmi' // This seems to make it work. Dunno why.
Please do this properly. If you need help ask one of the coders who added marine helmets.

2017-06-05 06:20 UTC, X0-11 commented on code/modules/halo/weapons/covenant/melee.dm
> +		throwforce = 12
Wasn't that a failsafe only found on those swords?

2017-06-05 06:56 UTC, bloxgate commented on code/modules/halo/weapons/covenant/melee.dm
> +		throwforce = 12
[No.](https://www.halopedia.org/Type-1_energy_sword#Design_details) It isn't on all the swords, but officially its not only the ones in the game that do it. If I remember, in one of the books it states that a lot of covie tech is designed to make itself non-functional if the enemy could get their hands on it.

2017-06-05 08:57 UTC, bloxgate requested changes

2017-06-05 08:57 UTC, bloxgate commented on code/modules/halo/misc/sangheili.dm
> +	if(heart.is_broken())
Why are we returning if the heart is broken? Isn't this still supposed to work then?

2017-06-05 16:17 UTC, bloxgate requested changes

2017-06-05 16:17 UTC, bloxgate commented on code/modules/halo/misc/sangheili.dm
> +	if(heart.is_broken())
Uh no. I don't think you understood what I said here. The original position was correct, but you were checking if the wrong thing was broken.

2017-06-05 17:20 UTC, X0-11 commented on code/modules/halo/misc/sangheili.dm
> +	if(heart.is_broken())
Sorry about that. I was making changes quickly, mostly focusing on the gamemode pr

2017-06-05 17:25 UTC, bloxgate approved these changes

2017-06-06 08:49 UTC, caelaislinn requested changes
I forgot to add, the following changes will require a changelog entry: floor sign fixes, elite mobs + elite language + shielded elite combat harnesses, covenant weapons, map fixes

2017-06-06 19:39 UTC, bloxgate requested changes
Please run the scripts to update the real changelog.

2017-06-06 19:50 UTC, bloxgate approved these changes

2017-06-07 08:49 UTC, caelaislinn commented on html/changelogs/XO-11 - PR #275 .yml
> +  - maptweak: Rewires armoury to stop it losing power.
Generally we dont want to put in an entry for every single change. For tweaks you can summarise or skip them, for balances you can group them by category eg all weapon changes (all balances, fixes, additions), armour changes (all balances, fixes, additions) etc

2017-06-07 08:49 UTC, caelaislinn approved these changes

2017-06-07 08:50 UTC, merged