Changing game year and making languages lore-friendly
HaloSpaceStation/HaloSpaceStation13 pull request #2759
Opened 2020-08-11 06:19 UTC by Terror4000rus

Removed standart BS12 languages from selection list and added some from language.dm in halo category.
English, Mandarin, French and Germany for now.
I can go further and remove sol common, gutter and other legacy languages, but I don't know devs reaction for now, so did a minimal work.

2020-08-11 11:30 UTC, caelaislinn requested changes
Looking good. This has been on my todo list after I looked at them about 1-2 years ago, but it's been low priority. The other B12 languages can go except for tradeband and gutter, which could be interesting background languages to add more flavour to the setting.

2020-08-11 11:30 UTC, caelaislinn commented on code/__defines/species_languages_halo.dm
> +#define LANGUAGE_LEKGOLO    "Lekgolo"
If you are putting Covenant languages here, there is a bunch of others including Unggoy, Sanshyuum, Brute etc

2020-08-11 11:34 UTC, caelaislinn requested changes
Changes needed to be Travis compatible: It looks like you gave English, Mandarin and German conflicting keys (1, 2 and 3) as those are already taken by galcom, tradeband and gutter. You'll need to move tradeband and gutter onto different non-conflicting keys and probably ditch galcom. 

As an idea for a future language related project, you could have a go at the Covenant language symbols I was experimenting with. You can see the remains of my attempt in `code/modules/halo/covenant/_language.dm`

2020-08-11 12:24 UTC, bloxgate commented
As a suggestion on the Covenant language symbols, we have gained support for Unicode since that was attempted. One option may be to render it as one of the non-Latin alphabets we now have access to. While it might not be the most lore friendly, rendering the syllables as IPA symbols or something similar makes a bit more sense in my head than having people know the actual symbols that correspond to the sounds in Sangheili.

2020-08-11 16:11 UTC, Terror4000rus commented
Updated

2020-08-11 16:11 UTC, Terror4000rus commented on code/__defines/species_languages_halo.dm
> +#define LANGUAGE_LEKGOLO    "Lekgolo"
Done.

2020-08-11 16:12 UTC, bloxgate submitted a review, later dismissed
Automated changelogs should go into the PR description, in the format given in the PR template.

2020-08-11 16:26 UTC, Terror4000rus commented
Updated

2020-08-18 05:43 UTC, caelaislinn approved these changes

2020-08-18 05:43 UTC, caelaislinn commented on code/datums/trading/ai.dm
> +	name_language = LANGUAGE_ENGLISH
These traders are unused by our code, but changing this is mostly harmless (except for making it a little harder to update from recent baycode)

2020-08-18 05:44 UTC, merged