reqpoint system tweaks
HaloSpaceStation/HaloSpaceStation13 pull request #2775
Opened 2020-08-29 10:04 UTC by X0-11

:cl: XO-11
tweak: Increases the points cap slightly, from 10 to 11
tweak: provides brutes with grenades
/:cl:

2020-08-29 13:52 UTC, caelaislinn commented on code/modules/halo/machinery/gunvendors.dm
> -
So this means no more magazine replenishment?

2020-08-29 13:52 UTC, caelaislinn approved these changes

2020-08-29 14:02 UTC, X0-11 commented on code/modules/halo/machinery/gunvendors.dm
> -
it's old leftover code that iirc doesn't even function

2020-08-31 01:33 UTC, caelaislinn requested changes
Resolve map conflicts before it can be merged

2020-09-01 20:41 UTC, caelaislinn approved these changes

2020-09-01 20:41 UTC, merged