Rudimentary slayer gamemode. Maps required.
HaloSpaceStation/HaloSpaceStation13 pull request #281
Opened 2017-06-04 15:30 UTC by X0-11

Slayer gamemode. Currently uses manual respawn with a 30 second timer on each respawn point. 

Ghosts players at roundstart and teleports them to a random spawnpoint. This is to allow for loading alternate maps for the slayer GM itself.

2017-06-05 04:37 UTC, caelaislinn requested changes

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	round_description = "Free for all"
Can you rewrite the various descriptions and stuff to specify it's "team deathmatch" and not a free for all? Or at least make 2 separate gamemodes, one as TDM and the other as FFA.

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	for(var/obj/effects/spawnpoint/s in world)
Can you make a custom spawnpoint types for slayer team 1 and slayer team 2? This will be a bit nicer than reusing job spawnpoints from other gamemodes

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +		if(/mob/living in s.loc.contents)
/mob/living is a type path, and Byond will never have type paths in atom/var/contents therefore this will always return false

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +				h.ghostize() // We don't want any players right now.
No-one should have spawned before we setup the round. If you need to, use /datum/game_mode/proc/pre_setup() which occurs before the round has started

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +				o.loc = pick(spwnpts) //Move all the ghosts to a spawnpoint.
Some people may legitimately want to observe and not play. We shouldn't force them to play

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	if(world.time >= respawnwhen)
I presume you want to do spawn waves, and not individual respawn counters? It  might be good to allow a voteable option for players to switch between them later down the track

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			if(/mob/living in range(5))
We should probably allow friendlies to spawn near each other... so only check for enemy players nearby.

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +				for(var/mob/dead/observer/o in range(0,i)) //This doesn't seem to work.
Again we don't want to force observers to play, and dead players waiting to respawn probably shouldn't be observing anyway. Give the gamemode a list variable to track people waiting to respawn then just loop over that when it comes time to respawn them

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +				var/obj/effects/spawnpoint = pick(spwnpts)
Need a way of checking if the spawnpoints are valid aka no enemies nearby... or maybe some spawnpoints can be captured by each team over the round

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	if(i == "Yes" && world.time >= nextspawn)
Manual respawns? Probably better to keep it random and automatic, but let players specify a specific spawnpoint if they want

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	del(src)//Not needed anymore.
Do qdel so the datum gets pooled

2017-06-05 04:37 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +/datum/slayernormal/New(var/mob/living/carbon/human/h)
Later on we'll want to add loadouts (preset and customisable) but this is good for now

2017-06-05 15:16 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	round_description = "Free for all"
I'm planning on finishing the FFA before moving on the the TDM.

2017-06-06 19:49 UTC, bloxgate requested changes

2017-06-06 19:49 UTC, bloxgate commented on baystation12.dme
> +#include "code\modules\halo\gamemodes\Slayer-Team Slayer\gamemode.dm"
Uh.... I know it probably doesn't matter at all, but I'd feel better if this was all lowercase, no spaces just to be safe on *nix platforms.

2017-06-06 19:49 UTC, bloxgate commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	processing_objects += src // Doesn't seem to normally process. Suggestions for a better way to do this would be appreciated.
I think that is actually the recommended way. I could be wrong though. @caelaislinn?

2017-06-06 19:49 UTC, bloxgate commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			break
I presume this is so you don't spawn too close to someone else? If so that should be a continue not a break.

2017-06-06 19:49 UTC, bloxgate commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			if(m.type == /mob/dead/observer) // This is checked first so people can quit playing and observe.
Won't this still prompt people who have hit the not for this round button?

2017-06-06 19:49 UTC, bloxgate commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +				if(m.stat == 2 && m.ckey in players) //Autorespawn for dead players
You should probably use the define for the DEAD status here, just in case it is ever changed.

2017-06-07 06:06 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			if(m.type == /mob/dead/observer) // This is checked first so people can quit playing and observe.
Good point. I'll switch the order.

2017-06-07 06:07 UTC, X0-11 commented on baystation12.dme
> +#include "code\modules\halo\gamemodes\Slayer-Team Slayer\gamemode.dm"
fine with me. I'll change it.

2017-06-07 06:17 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			break
Yeah. That's right. Isn't that what I want it to do? Stop the current iteration of the loop and let it go on to the next.

2017-06-07 07:46 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	processing_objects += src // Doesn't seem to normally process. Suggestions for a better way to do this would be appreciated.
pre_setup() and post_setup() exist for different things. If the gamemode isn't processing properly then that means it isn't being set and ran properly so this means there is a problem elsehwere.

2017-06-07 08:47 UTC, caelaislinn requested changes
Some tweaks... the main change is to refactor teams into datums

2017-06-07 08:47 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			break
You are doing this check wrong anyway. You need to do var/mob/living/carbon/human/H = locate() in view(5,i) and then check of H is null... right now it is checking if there is any *type paths* inside the contents  list of some atoms which is impossible

2017-06-07 08:47 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
>  		if(i.faction == h.faction)
Spawn lists need to be split into separate lists for each faction. Each faction should probably be its own datum as well... that way we can potentially have multiple factions. I've setup a basic faction system with overmap which you can use which will aid with overmap integration later

2017-06-07 08:47 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
>  		if(m.ckey in players)
This is what we in the business call a "sanity check" ie a check to see if the programming language still obeys it's documentation. Sanity checks should never make it to live code unless there is a major problem :P

2017-06-07 08:47 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +					break
I think we should allow people who spawn in as observers at roundstart to latejoin. This isn't a blocking issue for me though, so make it possible if you can.

2017-06-07 08:47 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +/datum/slayernormal/New(var/mob/living/carbon/human/h) // I did have a single grenade in here, but I think it broke the respawning. Don't know why.
? do you know what the issue was?

2017-06-07 08:47 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	var/team2[0]
setup the teams as datums instead of lists so they arent hardcoded

2017-06-07 08:47 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			h <<"Assigned To Blue Team"
This kind of snowflakey hardcoding can easily introduce bugs, it's better to abstract it away into a datum

2017-06-07 08:54 UTC, bloxgate commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			break
To clear up what I said, break stops the entire loop, it does **NOT** move on to the next iteration.

2017-06-07 09:16 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +/datum/slayernormal/New(var/mob/living/carbon/human/h) // I did have a single grenade in here, but I think it broke the respawning. Don't know why.
No idea. It may have just been coincidental. I can always add it back later.

2017-06-07 09:17 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +					break
They can. Anyone who spawns normally will have to ghost though. Normal latejoin observers function correctly

2017-06-07 09:19 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	var/team2[0]
Yeah. That was my next objective. It was hardcoded just to make it work. I'm still working on assigning objectives on spawn

2017-06-07 09:49 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
>  		if(i.faction == h.faction)
I think I saw the overmap factions a while back. "Insurrection", "UNSC" and "Covenant".

2017-06-07 09:51 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +			break
Alright, I'll replace the check and change the break to a continue.

2017-06-07 09:52 UTC, X0-11 commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
> +	processing_objects += src // Doesn't seem to normally process. Suggestions for a better way to do this would be appreciated.
I'm not getting any runtimes. Suggestions?

2017-06-07 12:28 UTC, caelaislinn commented on code/modules/halo/gamemodes/Slayer-Team Slayer/gamemode.dm
>  		if(i.faction == h.faction)
Yeah the first 2 are ones setup for the Innie gamemode, the third is a placeholder. You should be able to setup your own teams - OPFOR and BLUFOR (for wargame or sim themed stuff) or even reuse UNSC and Innies.

2017-06-09 00:49 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +			if(i.faction == h.faction) //TODO: Fix this. Seems to spawn people without taking spawnpoint faction into consideration
Yes that's because spwn always contains the spawn points in spwnpts. You probably mean to start with having var/spwn be an empty list.

2017-06-09 01:01 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +					break
This should probably be a continue. We don't want to stop spawning everyone because we had a single dude in the lobby.

2017-06-09 01:01 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +					break
That break isn't needed at all.

2017-06-09 06:38 UTC, X0-11 commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +			if(i.faction == h.faction) //TODO: Fix this. Seems to spawn people without taking spawnpoint faction into consideration
I can't believe I missed that.

2017-06-14 23:31 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
>  /datum/game_mode/slayer/post_setup()
```DM
/datum/game_mode/slayer/post_setup()
    return ..()
```

2017-06-20 08:30 UTC, caelaislinn commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> -	. = ..()
Yeah this redefinition is redundant

2017-06-20 08:34 UTC, caelaislinn commented on code/modules/halo/weapons/covenant/melee.dm
> +		item_icons = list(slot_l_hand_str ='code/modules/halo/icons/Energy Sword_inhand Human.dmi',slot_r_hand_str = 'code/modules/halo/icons/Energy Sword_inhand Human.dmi')
Yeah I was actually getting some intermittent issues with the inhand sprite not toggling in some cases. I did a quick code dive and couldn't see anything immediately wrong. Did you get a similar issue?

2017-06-20 08:36 UTC, X0-11 commented on code/modules/halo/weapons/covenant/melee.dm
> +		item_icons = list(slot_l_hand_str ='code/modules/halo/icons/Energy Sword_inhand Human.dmi',slot_r_hand_str = 'code/modules/halo/icons/Energy Sword_inhand Human.dmi')
Yep, it was hand dependent. It only appeared in the right hand. I didn't set the icons, so I fixed that here.

2017-06-23 20:52 UTC, bloxgate requested changes
Looks good. Just a few minor questions/concerns left from me.

2017-06-23 20:52 UTC, bloxgate commented on baystation12.dme
> +#include "maps\TeamSlayer1.dmm"
Are we sure we want to have this always included, rather than have it only load during slayer matches?

2017-06-23 20:52 UTC, bloxgate commented on code/modules/halo/clothing/misc.dm
> +	item_flags = STOPPRESSUREDAMAGE | THICKMATERIAL | AIRTIGHT
Would it be possible for air-tightness to be toggleable? I recall some stuff in lore about it being more like a gas mask with actual filters and such.

2017-06-23 20:52 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +	votable = 0
Are people not going to be able to have this an an option during the lobby?

2017-06-23 20:52 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +	antag = MODE_INNIE
I'm wondering if it'd be too much to make our own antags for the gamemode with their own antag indicators and such.

2017-06-23 21:09 UTC, X0-11 commented on baystation12.dme
> +#include "maps\TeamSlayer1.dmm"
It's always there for things like insurrection too. There shouldn't be any issues with things like atmos anyway due to the only way to access that map being the two slayer gamemodes.

2017-06-23 21:10 UTC, X0-11 commented on code/modules/halo/clothing/misc.dm
> +	item_flags = STOPPRESSUREDAMAGE | THICKMATERIAL | AIRTIGHT
It'd be possible. What would it do besides toggle the airtight flag?

2017-06-23 21:10 UTC, X0-11 commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +	votable = 0
Whoops, my bad.

2017-06-23 21:12 UTC, X0-11 commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +	antag = MODE_INNIE
Custom antags aren't crucial to the system working, but it would allow for the removal of a little bit of code. I can work on it if this gets merged, unless it's too much of an issue to merge with.

2017-06-23 21:30 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +	antag = MODE_INNIE
Ah, I was just thinking that custom icons would be nice. It'll be fine as is for now.

2017-06-23 21:33 UTC, bloxgate commented on code/modules/halo/clothing/misc.dm
> +	item_flags = STOPPRESSUREDAMAGE | THICKMATERIAL | AIRTIGHT
Perhaps have it act like the existing hardsuits? Takes a second or two to seal, but can be unsealed and such in oxygenated environments. See what they're doing and do that I guess.

2017-06-24 06:39 UTC, caelaislinn commented on baystation12.dme
> +#include "maps\TeamSlayer1.dmm"
Yeah haven't decided how best to handle this yet. I'm starting to think a recompile for different mapsets might be in order.

2017-06-24 09:14 UTC, X0-11 commented on code/modules/halo/clothing/misc.dm
> +	item_flags = STOPPRESSUREDAMAGE | THICKMATERIAL | AIRTIGHT
I'm unsure if those features should be added in this PR.

2017-06-24 19:05 UTC, bloxgate commented on baystation12.dme
> +#include "maps\TeamSlayer1.dmm"
Something like the watchdog that multimap servers use to recompile/restart on a map vote? Have a gamemode vote at the end instead of the beginning?

2017-06-28 21:15 UTC, BDpuffy420 commented
updates?

2017-06-29 07:17 UTC, X0-11 commented
I think we're waiting for the potential rebase.

2017-06-29 07:30 UTC, caelaislinn commented
I'm going to merge this then port it over after the codeswitch

2017-06-29 07:30 UTC, merged