Fixes ODST Officer Ranks being enlisted
HaloSpaceStation/HaloSpaceStation13 pull request #2812
Opened 2020-09-26 13:44 UTC by Joe44445

Makes the ODST Officer Ranks the actual Officer ranks and not enlisted

:cl: Joe4444
bugfix: Fixes the ranks assigned to ODST Officer alt titles
rscdel: Fixes the rank pins given to ODST Officer alt titles
/:cl:

2020-09-27 12:56 UTC, bloxgate requested changes
There's a rank pin of type `/decl/hierarchy/outfit/job/unsc/odst/e8` placed on the UNSC Yolotanker in operation_trebuchet. You'll need to replace that with the `o3` one. You should get a box that'll let you make that change if you try and open the map.

You should also consider changing your changelog a bit. I think this might better be expressed as just a single `tweak` rather than a `bugfix` and a `rscdel`

2020-11-05 22:57 UTC, BDpuffy420 commented
never updated

2020-11-10 20:58 UTC, bloxgate commented
@Joe44445 just a heads up, this will likely be closed due to inactivity soon. If you want this in, please make the required changes.

2020-11-23 16:02 UTC, bloxgate commented
Closing due to inactivity

2020-11-23 16:02 UTC, closed without merging