20200928 Fixes - 40mms, Vendors, Weapon Fixes
HaloSpaceStation/HaloSpaceStation13 pull request #2819
Opened 2020-09-28 09:38 UTC by 5crownik007

#2815 
🆑 5crownik007
rscadd: 40mm available for purchase in cargo shuttle
bugfix: 40mm illumination shells now illuminate point of impact
bugfix: ODST vendors now vend M6S mags instead of M6D mags
bugfix: body scanners now function
bugfix: covenant now have ample supply of armourkits
bugfix: ma3 fixed finally
bugfix: unsc plasma weapons have damage parity with their ballistic counterparts
/🆑

2020-09-28 11:51 UTC, X0-11 commented on code/modules/halo/weapons/ammo_g40mm.dm
> +	on = 1
better to make the code that spawns this flare activate it normally

2020-09-28 13:53 UTC, 5crownik007 commented on code/modules/halo/weapons/ammo_g40mm.dm
> +	on = 1
why? This works just fine from testing

2020-09-28 13:53 UTC, 5crownik007 commented on code/modules/halo/weapons/ammo_g40mm.dm
> +	on = 1
Eh there are probably unintended consequences I didn't account for you're right

2020-09-28 13:55 UTC, X0-11 commented on code/modules/halo/weapons/ammo_g40mm.dm
> +	on = 1
flarecode activation may have special handling effects of it's own or have them added later. Utilising the generalised method of activation would be better

2020-09-28 14:15 UTC, 5crownik007 commented on code/modules/halo/weapons/ammo_g40mm.dm
> +	on = 1
done

2020-09-30 22:43 UTC, bloxgate requested changes

2020-09-30 22:43 UTC, bloxgate commented on code/modules/halo/unsc/supply/ammo.dm
> +	name = "M301 40mm HE crate(1 box)"
Personally, I'd add a space before the `(1 box)`

2020-09-30 22:43 UTC, bloxgate commented on code/modules/halo/weapons/unsc_plasma.dm
> +	shield_damage = -5
Is this supposed to be negative?

2020-09-30 22:43 UTC, bloxgate commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> -		/obj/item/weapon/armor_patch/mini/cov = 10,
Unless I'm missing something about how this works, doesn't this mean the covenant now have no armor kits, with the exception of in the Kig-Yar vendors?

I was under the impression that the issue was them having too few, not too many.

2020-10-01 03:22 UTC, 5crownik007 commented on code/modules/halo/weapons/unsc_plasma.dm
> +	shield_damage = -5
Yes

2020-10-01 03:23 UTC, 5crownik007 commented on code/modules/halo/covenant/structures_machines/covvendors.dm
> -		/obj/item/weapon/armor_patch/mini/cov = 10,
pointbased vendors default to 100 in a pool iirc if amount is not set, you are missing something

2020-10-01 03:45 UTC, 5crownik007 commented on code/modules/halo/unsc/supply/ammo.dm
> +	name = "M301 40mm HE crate(1 box)"
done

2020-10-01 16:15 UTC, bloxgate approved these changes

2020-10-05 14:20 UTC, merged