ERT Loadouts [WIP]
HaloSpaceStation/HaloSpaceStation13 pull request #2852
Opened 2020-11-23 03:19 UTC by Max-023

Adds ERT loadouts that automatically come with weapons and equipment suited for battle, allowing admins to quickly make a team of soldiers of a specific faction. Currently WIP and only has insurrectionist loadouts.

:cl: Guprei
rscadd: Adds SOE ERT Loadouts.
rscadd: Adds Insurrectionist ERT Loadouts.
/:cl:

2020-11-23 11:05 UTC, bloxgate requested changes

2020-11-23 11:05 UTC, bloxgate commented on code/modules/halo/insurrection/innie_outfits.dm
> +	r_hand = /obj/item/weapon/storage/box/m7_m443/rnd48
Possible typo in this path here?

2020-11-23 11:05 UTC, bloxgate commented on code/modules/halo/insurrection/innie_outfits.dm
> +/decl/hierarchy/outfit/job/geminus_innie_leader/ert(mob/living/carbon/human/H, rank, assignment)
This should be `/decl/hierarchy/outfit/job/geminus_innie_leader/ert/equip_id(...)`

2020-11-23 11:05 UTC, bloxgate commented on code/modules/halo/insurrection/innie_outfits.dm
> +/decl/hierarchy/outfit/job/zeal_team_rifleman/ert(mob/living/carbon/human/H, rank, assignment)
`/decl/hierarchy/outfit/job/zeal_team_rifleman/ert/equip_id(...)`

2020-11-23 11:05 UTC, bloxgate commented on code/modules/halo/insurrection/innie_outfits.dm
> +/decl/hierarchy/outfit/job/innie_colossus/ert(mob/living/carbon/human/H, rank, assignment)
`/decl/hierarchy/outfit/job/innie_colossus/ert/equip_id(...)`

2020-11-23 11:05 UTC, bloxgate commented on code/modules/halo/insurrection/innie_outfits.dm
> +/decl/hierarchy/outfit/job/geminus_innie/ert/equip_id(mob/living/carbon/human/H, rank, assignment)
Given that we seem to be just setting the same ID for all of these ERT roles, perhaps it'd be advantageous to have a single parent innie ERT type that has this method defined and then just have the subtypes all inherit from it, so we don't have to duplicate this method 8 times?

Granted, I do see that the file did it this way for all of the subtypes of geminus_innie anyway, so perhaps there's some BYOND specific reason for this. Anyone know if it'd be bad to remove some of the duplicates @HaloSpaceStation/developers?

2020-11-23 11:17 UTC, X0-11 commented on code/modules/halo/insurrection/innie_outfits.dm
> +/decl/hierarchy/outfit/job/geminus_innie/ert/equip_id(mob/living/carbon/human/H, rank, assignment)
i believe geminus innie does actually do the equip_id stuff already, so at least this one doesn't need to be duplicated

2020-11-23 11:19 UTC, bloxgate commented on code/modules/halo/insurrection/innie_outfits.dm
> +/decl/hierarchy/outfit/job/geminus_innie/ert/equip_id(mob/living/carbon/human/H, rank, assignment)
Yes, the ERT ones can probably be deduplicated. The separate `innie` and `innie_leader` ones for the normal roles IDs should stay, unless we want to have to do a fair bit of reorganizing.

2020-11-23 19:33 UTC, Max-023 commented on code/modules/halo/insurrection/innie_outfits.dm
> +	r_hand = /obj/item/weapon/storage/box/m7_m443/rnd48
its a copy paste from the M7 dm, but I also made the rnd48 a custom box itself, so I likely need to fix it there to fix it here.

2020-11-28 00:08 UTC, bloxgate reviewed
Looking much better! It seems like there's just a couple issues with a few jobs having the same name for the outfits now.

Interestingly a couple of the impacted outfits don't seem to have been touched by this PR so I'm not sure why they're suddenly conflicting. I wouldn't expect any of the names to already have `ERT` in them.

2020-12-18 18:51 UTC, BDpuffy420 commented
uh update?

2020-12-21 23:16 UTC, bloxgate commented
I spoke to them about this a week or two ago on Discord. They mentioned they're busy with finals but should take another look once they get on break for the holidays.

2021-01-09 00:20 UTC, bloxgate commented
Hey @Max-023 it's been a while, any chance on an update for this?

2021-01-15 03:19 UTC, closed without merging