Adds a new base assault variant that places the URF in an attacking role against the unsc
HaloSpaceStation/HaloSpaceStation13 pull request #2865
Opened 2020-12-03 13:14 UTC by X0-11

:cl: XO-11
rscadd: A new base assault variant is available in the mapswitch vote list. The urf attacks the UNSC moonbase.
tweak: Modifies a wide range of vehicle stats to make them more responsive and less painful to utilise.
/:cl:

2020-12-03 14:24 UTC, enkidienne commented
this looks like a lot of stuff in a single PR. touching a lot of stuff that isn't necessarily related to the gamemode?

2020-12-03 19:30 UTC, bloxgate commented
Yes, this seems to contain commits from a previous PR. Can you update your local branch to match our current alpha branch?

2020-12-03 20:52 UTC, X0-11 commented
Don't seem to be able to clean it up. I can make sure I update my alpha branch for later PRs though.

2020-12-03 21:13 UTC, X0-11 commented
ignore that, i just hadn't recieved an updated view so it still looked like it had the previous PR things as commits

2020-12-06 21:15 UTC, BDpuffy420 approved these changes

2020-12-07 23:21 UTC, Shadowtail117 requested changes
Some grammatical fixes. As an aside, given this PR touches a lot more than simply URF base assault consider changing the title.

2020-12-07 23:21 UTC, Shadowtail117 commented on code/modules/halo/weapons/M6D.dm
> +	desc = "A common UNSC sidearm and one of the variants of Misriah Armory's M6 handgun series. Takes 12.7mm calibre magazines. The relatively small size and low weight makes it unencumbering and allow
```suggestion
	desc = "A common UNSC sidearm and one of the variants of Misriah Armory's M6 handgun series. Takes 12.7mm calibre magazines. The relatively small size and low weight make it unencumbering and allow for faster movement than when utilising full rifles."
```

2020-12-07 23:21 UTC, Shadowtail117 commented on code/modules/halo/weapons/M6S.dm
> +	desc = "The M6C/SOCOM is a special operations variant of the popular M6C but with a whole host of inbuilt attachments. Takes 12.7mm calibre magazines.The relatively small size and low weight makes i
```suggestion
	desc = "The M6C/SOCOM is a special operations variant of the popular M6C but with a whole host of inbuilt attachments. Takes 12.7mm calibre magazines. The relatively small size and low weight make it unencumbering and allow for faster movement than when utilising full rifles."
```

2020-12-07 23:21 UTC, Shadowtail117 commented on code/modules/halo/weapons/M7.dm
> +	desc = "The M7/Caseless Submachine Gun is a fully automatic close quarters infantry and special operations weapon. Takes 5mm calibre magazines.The relatively small size and low weight makes it unenc
```suggestion
	desc = "The M7/Caseless Submachine Gun is a fully automatic close quarters infantry and special operations weapon. Takes 5mm calibre magazines. The relatively small size and low weight make it unencumbering and allow for faster movement than when utilising full rifles."
```

2020-12-07 23:21 UTC, Shadowtail117 commented on code/modules/halo/weapons/covenant/pistols.dm
> +	desc = "A dual funtionality pistol: It fires bolts of plasma, and when overcharged is capable of emitting a small emp burst at the point of impact.The relatively small size and low weight makes it u
```suggestion
	desc = "A dual funtionality pistol: It fires bolts of plasma, and when overcharged is capable of emitting a small emp burst at the point of impact. The relatively small size and low weight make it unencumbering and allow for faster movement than when utilising full rifles."
```

2020-12-07 23:21 UTC, Shadowtail117 commented on code/modules/halo/weapons/covenant/pistols.dm
> +	desc = "This weapon fire razor-sharp crystalline shards which can explode violently when embedded into targets.The relatively small size and low weight makes it unencumbering and allows for faster m
```suggestion
	desc = "This weapon fire razor-sharp crystalline shards which can explode violently when embedded into targets. The relatively small size and low weight make it unencumbering and allow for faster movement than when utilising full rifles."
```

2020-12-07 23:21 UTC, Shadowtail117 commented on maps/base_assault_unsc_defend_vs_urf/urf_unsc_gm.dm
> +	attackers = " The URF"
```suggestion
	attackers = "The URF"
```

2020-12-13 19:50 UTC, merged