Add special reloads for projectile weapons
HaloSpaceStation/HaloSpaceStation13 pull request #2867
Opened 2020-12-07 18:01 UTC by Shadowtail117

Players can now perform special reloads for weapons with magazines (e.g., the assault rifle or the magnum, or technically needle weaponry). Tactical reloads take 1.5 seconds to perform and will exchange the magazine in your hand for the one in the gun (it will put the old mag directly into your hand), allowing you to save a half-full clip. Speed reloads are only 1 second and drop the old magazine on the floor, useful for quickly getting rid of a spent magazine.

Obviously, not every gun should be able to be tactically reloaded, so all projectile-based weapons have a `can_special_reload` variable that defaults to TRUE and allows tactical and speed reloads. I've disallowed the plasma carbine since that has its own magazine system separate from the default code, but other unconventional weapons like needlers and rocket launchers have it. I'm not well-versed in every weapon and how feasible this would be (especially UNSC weapons) so, this is something that can easily be changed.

Overall this allows for much more fluid magazine handling instead of having to empty the gun, drop the old magazine, click on the new magazine, then click on the gun (which can be difficult to do in a stressful situation). The Weapons Expertise skill was not factored into this since skills appear largely vestigial.

:cl: Shadowtail117
rscadd: You can now tactically reload a projectile weapon by clicking on it with an appropriate magazine while on grab intent.
rscadd: You can now speed reload a projectile weapon by clicking on it with an appropriate magazine while on harm intent.
/:cl:

2020-12-07 18:03 UTC, Shadowtail117 commented
Just a note that the bulk of the code for this was borrowed from https://github.com/Baystation12/Baystation12/pull/29291, which I also authored.

2020-12-07 18:20 UTC, X0-11 requested changes

2020-12-07 18:20 UTC, X0-11 commented on code/modules/projectiles/guns/projectile.dm
> +							if(!speed_reload_time == -1)
i don't think the ! should be there

2020-12-07 18:20 UTC, X0-11 commented on code/modules/projectiles/guns/projectile.dm
>  				if(ammo_magazine)
Putting this here just because I want to address the way this is approached.
I feel like preexisting procs for magazine ejection and insertion should be followed here rather than doing it in a special way.

2020-12-07 18:21 UTC, Shadowtail117 commented on code/modules/projectiles/guns/projectile.dm
> +							if(!speed_reload_time == -1)
oops

2020-12-09 20:54 UTC, X0-11 requested changes

2020-12-09 20:54 UTC, X0-11 commented on code/modules/projectiles/guns/projectile.dm
> +							specialreloaded = TRUE
this variable isn't needed, the reloadmessage variable should be able to pull double duty, using a direct comparison to "speed reload" where you check for this variable

2020-12-09 20:57 UTC, Shadowtail117 commented on code/modules/projectiles/guns/projectile.dm
> +							specialreloaded = TRUE
done

2020-12-09 20:59 UTC, X0-11 approved these changes

2020-12-13 21:35 UTC, merged