Add executions
HaloSpaceStation/HaloSpaceStation13 pull request #2873
Opened 2020-12-09 20:51 UTC by Shadowtail117

Adds executions to the game following most of the roadmap from https://github.com/HaloSpaceStation/HaloSpaceStation13/discussions/2872. Species barriers were not implemented and anyone can do them with the right weapon.

You can now execute someone who is on the ground with a combat knife, machete, energy sword, energy dagger, and blamite weapon. You do this by targeting an appropriate body part (for most it is either the chest or head) and on grab intent while within arms' reach (or you can leap at them). They have to still be alive (no repeatedly executing a dead guy) and it takes two seconds; if they or you move during that time, it will be canceled. Executing deals fatal damage to the appropriate body part and instantly kills the brain.

Every `obj/item/weapon` now has three new variables: `executions_allowed`, `start_execute_messages`, and `stop_execute_messages`. `executions_allowed` is self-explanatory; the latter two are associative lists for targeting zones. The index is the body part, the key is the message to be shown. Include "USER", "VICTIM", and "WEAPON" in these messages and they will automatically be converted to the appropriate names. These messages themselves are entirely flavor (except for the blamite weapons, which _do_ explode) and the damage type and flags are derived from the weapon that was used.

:cl: Shadowtail117
rscadd: Added executions. Target a downed but still alive player with an appropriate weapon on grab intent and the correct zone to deliver a killing blow.
rscadd: Made the following weapons appropriate for executions: Combat knife (head, chest), machete (head, chest), energy sword/dagger (chest), blamite weapon (head, chest).
/:cl:

2020-12-09 21:06 UTC, X0-11 approved these changes

2020-12-10 02:55 UTC, bloxgate requested changes, later dismissed

2020-12-10 02:55 UTC, bloxgate commented on code/modules/halo/misc/executions.dm
> +#define EXECUTION_TIME 2 SECONDS
Can we get a matching `#undef` for this? Either at the end of this file if you're not using it somewhere else, or in an `~defines.dm` file in the same folder.

2020-12-10 19:30 UTC, Shadowtail117 commented on code/modules/halo/misc/executions.dm
> +#define EXECUTION_TIME 2 SECONDS
Done.

2020-12-13 19:50 UTC, merged