Add biofoam reagent + syringe with combat meds.
HaloSpaceStation/HaloSpaceStation13 pull request #295
Opened 2017-07-07 22:18 UTC by X0-11

Combat medical syringe includes biofoam, tricordrazine, triadrenaline and tramadol.

TODO: 
Biofoam overdose effect.
Combat syringe dispensing system on armour.

2017-07-07 22:46 UTC, bloxgate requested changes

2017-07-07 22:46 UTC, bloxgate commented on code/modules/halo/chemicals/containers.dm
> +		mode = SYRINGE_INJECT
You need to update the icon after you do this.

2017-07-07 22:46 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +			o.owner << "<span class = 'notice'>You feel the bleeding in your [o.name] slow.</span>"
Maybe only do that if it's a bleeding wound?

2017-07-07 22:46 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +/datum/reagent/triadrenaline
If we're moving this, maybe we should move reactions into the halo module too?

2017-07-07 22:55 UTC, X0-11 commented on code/modules/halo/chemicals/medicine.dm
> +/datum/reagent/triadrenaline
The reactions?

2017-07-07 23:54 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +/datum/reagent/triadrenaline
No, the reactions that create the chems. I think the file is called chemical-reactions

2017-07-08 14:23 UTC, bloxgate commented on code/modules/halo/chemicals/recipes.dm
> +	required_reagents = list()
No ingredients?

2017-07-12 00:08 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +				if(dam >= 20)
Perhaps check if it's greater than or equal to the broken point instead of 20. Not all the organs would be broken at 20.

2017-07-12 17:34 UTC, X0-11 commented on code/modules/halo/chemicals/recipes.dm
> +	required_reagents = list()
I couldn't really think of any at the time, So I left it blank. Any suggestions?

2017-07-12 18:25 UTC, bloxgate commented on code/modules/halo/chemicals/recipes.dm
> +	required_reagents = list()
The foaming agent stuff + tricord + bicard?

2017-07-12 18:28 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +				M <<"<span class ='userdanger'>You feel [dam ? "your [O.name] collapse" : "immense pressure on your [O.name]" ].</span>"
I think you're setting dam the wrong way around. Right now, if the organ isn't broken it'll use the collapse message, if it is broken it'll use the pressure message. Are you sure that's what you want?

2017-07-12 18:40 UTC, X0-11 commented on code/modules/halo/chemicals/medicine.dm
> +				M <<"<span class ='userdanger'>You feel [dam ? "your [O.name] collapse" : "immense pressure on your [O.name]" ].</span>"
Ah! Thanks for catching that.

2017-07-19 16:16 UTC, X0-11 commented on code/modules/halo/chemicals/medicine.dm
> +/datum/reagent/triadrenaline
Done.

2017-08-07 23:44 UTC, merged