Achlys Compiles
HaloSpaceStation/HaloSpaceStation13 pull request #2956
Opened 2021-05-21 01:38 UTC by Desolane

Achlys compiles.

Achlys now has snowflake MRE's that fit in pockets and marine suit storage.

2021-05-21 06:35 UTC, bloxgate requested changes
It looks like some of the code for this is being included even when we're not running this map. Here's the compiler output from the crusade map:
```
DM compiler version 513.1536
loading baystation12.mdme
loading interface/skin.dmf
code/modules/halo/flood/types/achlys.dm:45:error: /obj/item/weapon/gun/projectile/shotgun/pump/m45_ts/achlys: undefined type path
code/modules/halo/flood/types/achlys.dm:45:error: /obj/item/weapon/gun/projectile/ma37_ar/achlys: undefined type path
code/modules/halo/flood/types/achlys.dm:46:error: /obj/item/weapon/gun/projectile/m6d_magnum/police/achlys: undefined type path
code/modules/halo/flood/types/achlys.dm:46:error: /obj/item/weapon/gun/projectile/shotgun/pump/m45_ts/police/achlys: undefined type path
code/modules/halo/flood/types/achlys.dm:77:error: /obj/item/weapon/card/id/the_gold: undefined type path
code/modules/halo/flood/types/achlys.dm:87:error: /obj/item/weapon/card/id/the_silver: undefined type path
```

I think you'll want to change things so that your flood subtypes file only gets included by the gamemode/map file rather than by default.

2021-05-21 14:33 UTC, X0-11 requested changes

2021-05-21 14:33 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +	icon_state = "spawntrigger" //changes from a pink X for ease of mapping to completely invisible in game
try putting Invisibility = 101 in the initial definition above instead

2021-05-21 14:33 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +	if(uses == 0)	 //this is so noisemakers are in different places
I believe I already created a system to somewhat randomly distribute elements across the map. I think it's even used in achlys.

2021-05-21 14:33 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +/obj/structure/splish_splash/process()
Try setting a time-to-splash at the initialisation of the item (world.time + 3 SECONDS) or something like that rather than this

2021-05-21 14:33 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +	var/gun_type_spawn = pick(/obj/item/weapon/gun/projectile/shotgun/pump/m45_ts/achlys, /obj/item/weapon/gun/projectile/ma37_ar/achlys,\
I believe flood mobs at least already now have a system to do all this. Might be in my PR atm though.

2021-05-21 14:39 UTC, Desolane commented on maps/unsc_achlys/achlys_objects.dm
> +	if(uses == 0)	 //this is so noisemakers are in different places
That is for randomly distributing a few items, spores, and biomass spawners across the multiple Z levels after a time limit, which is handled in the gamemode code. These noisemakers will be distributed through the 5th Z level, the bilges, in static locations I can more readily have a hands-on approach to building. The qdel at round start is simply to help break up any monotony of sound sources across multiple breakthroughs. Just more smoke and mirrors.

2021-05-21 14:40 UTC, Desolane commented on maps/unsc_achlys/achlys_objects.dm
> +/obj/structure/splish_splash/process()
I don't follow.

2021-05-21 14:44 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +/obj/structure/splish_splash/process()
There's no need to use a constantly decrementing counter here when you could just log down a time-to-splash when the item is initialised, then checking the time against that, I think.

2021-05-24 02:31 UTC, Desolane commented on maps/unsc_achlys/achlys_objects.dm
> +	var/gun_type_spawn = pick(/obj/item/weapon/gun/projectile/shotgun/pump/m45_ts/achlys, /obj/item/weapon/gun/projectile/ma37_ar/achlys,\
Flood now have a variable for spawning with a gun, though if I added that variable to the base mobs it would result in compile errors because the guns they would spawn with are snowflaked into the achlys folder.

2021-05-24 08:48 UTC, X0-11 commented on maps/unsc_achlys/achlys_objects.dm
> +	var/gun_type_spawn = pick(/obj/item/weapon/gun/projectile/shotgun/pump/m45_ts/achlys, /obj/item/weapon/gun/projectile/ma37_ar/achlys,\
You don't have to add a variable for it, just do something like:
/mob/living/simple_animal/hostile/flood/combat_form/prisoner/guard
    spawn_with_gun = list(/obj/item/weapon/gun/projectile/shotgun/pump/m45_ts/achlys, etc, etc)
in the achlys files

2021-05-28 16:40 UTC, bloxgate requested changes
Yes, the compiler is correct that having a `pick(...)` in the definition isn't constant. You'd be best off having a list of what it could spawn with, and then doing the actual `pick()` in the `New()` proc. A good rule of thumb is that complicated initialization shouldn't be done in the definition.

2021-05-28 16:40 UTC, bloxgate commented on maps/unsc_achlys/achlys_flood.dm
> +	spawn_with_gun = pick(list(/obj/item/weapon/gun/projectile/shotgun/pump/m45_ts/achlys),list(/obj/item/weapon/gun/projectile/m6d_magnum/police/achlys),
How you had this before this commit is closer to how this should look. See http://www.byond.com/docs/ref/#/proc/pick for details.

2021-06-13 05:04 UTC, closed without merging