Modifies the code handling huragok regeneration
HaloSpaceStation/HaloSpaceStation13 pull request #2958
Opened 2021-05-22 11:43 UTC by X0-11

Makes components in huragoks self-re-install when they're damaged to destruction but the huragok themselves aren't killed.

2021-05-28 16:13 UTC, bloxgate requested changes

2021-05-28 16:13 UTC, bloxgate commented on code/modules/halo/covenant/species/huragok/robot.dm
> +			if(isnull(init_ex_type) || (!isnull(initial(C.external_type)) && !C.wrapped))
As init_ex_type is initial(C.external_type), we get [A ∨ (¬A ∧ ¬B)](https://www.wolframalpha.com/input/?i=A+OR+%28NOT+A+AND+NOT+B%29), which simplifies to A ∨ ¬B. So I think this can be simplified to
```dm
if(isnull(init_ex_type) || !C.wrapped)
```

2021-05-30 21:01 UTC, X0-11 commented on code/modules/halo/covenant/species/huragok/robot.dm
> +			if(isnull(init_ex_type) || (!isnull(initial(C.external_type)) && !C.wrapped))
change made

2021-05-30 22:40 UTC, bloxgate approved these changes

2021-05-30 22:41 UTC, merged