Adds many new species and their respective armour / items.
HaloSpaceStation/HaloSpaceStation13 pull request #296
Opened 2017-07-17 16:25 UTC by X0-11

Species added:
Spartans
Jackals
Brutes (TODO)
Species icons modified:
Sangheili.

Blocking Error:

2017-07-17 18:24 UTC, bloxgate commented on code/modules/halo/weapons/covenant/ammo.dm
> +	icon_state = "Plasmapistol Shot"
Plasma pistol is two words

2017-07-17 18:24 UTC, bloxgate commented on code/modules/halo/weapons/covenant/ammo.dm
> +	icon_state = "Plasmarifle Shot"
Two words

2017-07-17 23:21 UTC, TheScreamingStar commented
Later on I will finish up the rest on I will finish on the rest of the stuff for my sprites on this PR (higher rank armor, furred brutes, species aesthetics for them).

2017-07-24 04:41 UTC, bloxgate requested changes
Looking great so far XO! Just a couple questions though. Shouldn't the other covie species have some radiation resistance like the elites too? They are going to be using the same weapons after all.

Also, what does setting the species eyes to null do?

2017-07-24 04:41 UTC, bloxgate commented on code/modules/halo/species_items/kig-yar.dm
> +/obj/item/clothing/head/helmet/kigyar/proc/tryequipNV()
Could you put some underscores between the words in that proc name please?

2017-07-24 04:41 UTC, bloxgate commented on code/modules/mob/living/carbon/human/species/outsider/brutes.dm
> +	icobase = 'code/modules/halo/icons/species/r_Augmented_Human.dmi' //The DMI needed modification to fit the usual format (see other species' dmis)
This is temporary, I hope?

2017-07-24 07:32 UTC, X0-11 commented on code/modules/mob/living/carbon/human/species/outsider/brutes.dm
> +	icobase = 'code/modules/halo/icons/species/r_Augmented_Human.dmi' //The DMI needed modification to fit the usual format (see other species' dmis)
Yep. My copypasta for species has been revealed!

2017-07-24 07:33 UTC, X0-11 commented
eyes = null stops the species sprite assembler from drawing an eye overlay. Don't have one for those species yet.

2017-08-07 23:48 UTC, caelaislinn commented
There's a couple of .tmp files there I'm not sure about, but this branch is getting deprecated shortly so we can just skip them when we come back to port them over.

2017-08-07 23:48 UTC, caelaislinn commented
Manual merging this...

2017-08-07 23:48 UTC, closed without merging