Changes the way slayer distributes weapons.
HaloSpaceStation/HaloSpaceStation13 pull request #2972
Opened 2021-07-25 08:32 UTC by X0-11

:cl: XO-11
tweak: Slayer now distributes weapons around the map differently and consistently respawns them allowing for longer and more interesting slayer matches.
/:cl:

2021-07-29 22:58 UTC, bloxgate requested changes

2021-07-29 22:58 UTC, bloxgate commented on code/modules/halo/vehicles/vehiclebase.dm
> +	/*
This should probably get a changelog entry too

2021-07-29 22:58 UTC, bloxgate commented on code/modules/halo/weapons/forerunner/snipers.dm
> +	accuracy = -9
Might also want to consider a CL entry for this as well

2021-07-29 22:58 UTC, bloxgate commented on maps/slayer/slayer_itemspawn_markers.dm
> +/obj/effect/itemspawn_marker/process()
Just want to double check, these are added to processing_objects and stay there? I don't seem to see a default process proc for `/obj/effect` and the one for `/obj` will remove itself from processing_objects when called.

I also don't see any code for the default effect that actually puts it in processing_objects, but I may just be searching for the wrong term.

2021-07-30 17:46 UTC, X0-11 commented on maps/slayer/slayer_itemspawn_markers.dm
> +/obj/effect/itemspawn_marker/process()
Ah, thanks for catching that. They're meant to sit there in processing objects yes.

2021-07-30 17:46 UTC, X0-11 commented on code/modules/halo/weapons/forerunner/snipers.dm
> +	accuracy = -9
The change is minor enough that I didn't even recall making it. I don't think it'll have a player facing effect.

2021-07-30 17:46 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase.dm
> +	/*
Added.

2021-07-30 19:29 UTC, bloxgate approved these changes

2021-07-30 19:41 UTC, bloxgate commented on baystation12.dme
> -#include "code\modules\halo\leader_support\supply_drop_evac.dm"
Actually just noticed this. This file doesn't seem to be removed by this PR, but is unincluded. I just want to make sure that that is intentional.

2021-07-30 19:42 UTC, X0-11 commented on baystation12.dme
> -#include "code\modules\halo\leader_support\supply_drop_evac.dm"
Yeah that's unincluded on purpose. I'm pretty sure it's broken in every mode right now and i may fix it at a later date.

2021-07-30 19:47 UTC, merged