A variety of vehicle tweaks (And some minor CnH changes)
HaloSpaceStation/HaloSpaceStation13 pull request #2978
Opened 2021-07-28 19:20 UTC by X0-11

:cl: XO-11
tweak: Vehicle weapon burst sizes have been modified to take advantage of click-drag aim.
tweak: Lekgolo are practically vehicles so: Slight changes to turn speed and weapon fire rate.
tweak: Lekgolo are now immune to the confusion effect of explosions.
rscadd: Most vehicles can now deploy smoke countermeasures to obscure an attack / retreat. Smoke deploys to the front of the vehicle.
/:cl:

2021-07-29 23:11 UTC, bloxgate requested changes

2021-07-29 23:11 UTC, bloxgate commented on code/modules/halo/vehicles/vehicle_action_buttons.dm
> +#define ACTION_USE_BRAKE "Toggle Brake"
There should be some matching `#undef`s somewhere

2021-07-29 23:11 UTC, bloxgate commented on code/modules/halo/machinery/gunvendors.dm
> +		/obj/item/weapon/grenade/smokebomb = 15,
Might be worth at least mentioning there were some vendor amound tweaks in CL?

2021-07-30 17:53 UTC, X0-11 commented on code/modules/halo/machinery/gunvendors.dm
> +		/obj/item/weapon/grenade/smokebomb = 15,
Will do.

2021-07-30 17:54 UTC, X0-11 commented on code/modules/halo/vehicles/vehicle_action_buttons.dm
> +#define ACTION_USE_BRAKE "Toggle Brake"
Added.

2021-07-30 19:26 UTC, bloxgate approved these changes

2021-07-30 19:26 UTC, merged