20210730 Fixes - Spawnpoints and URF Bugfixes
HaloSpaceStation/HaloSpaceStation13 pull request #2990
Opened 2021-08-04 09:06 UTC by 5crownik007

Closes #2818
Closes #2900
🆑 5crownik007
bugfix: URF Mission shuttle and URF Ship Req Console are FIXED finally
bugfix: colonists should no longer spawn in the covenant ship on KS7 or Geminus maps
rscadd: SOE are now available in UNSCvsURF base assault
/🆑

2021-08-04 09:11 UTC, X0-11 requested changes, later dismissed

2021-08-04 09:11 UTC, X0-11 commented on maps/base_assault_neutral_base/neutral_city.dmm
> +"hJ" = (/obj/structure/table/steel,/obj/item/weapon/scalpel,/obj/machinery/light{dir = 8},/obj/item/weapon/circular_saw{step_y = 0},/turf/simulated/floor/tiled/white,/area/planets/neutralcity/inside/
This step y will cause tile teleport instead of smooth animation. Ensure you don't accidently use the nudge command when placing things in the map editor

2021-08-04 09:26 UTC, 5crownik007 commented on maps/base_assault_neutral_base/neutral_city.dmm
> +"hJ" = (/obj/structure/table/steel,/obj/item/weapon/scalpel,/obj/machinery/light{dir = 8},/obj/item/weapon/circular_saw{step_y = 0},/turf/simulated/floor/tiled/white,/area/planets/neutralcity/inside/
should be fixed

2021-08-09 09:07 UTC, 5crownik007 commented
Fellas can we review this again please @X0-11

2021-08-09 22:16 UTC, bloxgate requested changes

2021-08-09 22:16 UTC, bloxgate commented on code/modules/halo/factions/quest/shuttle_instance.dm
>  	offsite_shuttle_area_type = /area/shuttle/offsite_berth_transport
This is causing a compilation error: `code/modules/halo/factions/quest/shuttle_instance.dm:59:error: /area/shuttle/offsite_berth_transport: undefined type path`. 

Please make sure you have that path defined too - you likely need to uncomment some other stuff for this to work.

2021-09-11 22:02 UTC, 5crownik007 commented
@X0-11 can we get this in or do I still need to make changes?

2021-09-11 22:57 UTC, bloxgate requested changes
This is still failing the unit tests:
```
 ## UNIT_TEST ##: [AREA: Areas shall be used]: Offsite Berth (/area/shuttle/offsite_berth_transport) ([0x4000008]) (0,0,0) is unused.
## UNIT_TEST ##: [AREA: Areas shall be used]: Rabbit Hole Berth (/area/shuttle/innie_berth_transport) ([0x4000009]) (0,0,0) is unused.
## UNIT_TEST ##: [AREA: Areas shall be used]: Rabbit Hole Shuttle (/area/shuttle/innie_shuttle_transport) ([0x400000a]) (0,0,0) is unused.
## UNIT_TEST ##: [AREA: Areas shall be used]: Geminus Outskirts (/area/planets/Geminus/indoor/quest_instance) ([0x400000b]) (0,0,0) is unused.
## UNIT_TEST ##: [AREA: Areas shall be used]: The Geminus NPC Factory (/area/planets/Geminus/indoor/npc_factory) ([0x400000c]) (0,0,0) is unused.
## UNIT_TEST ##: [AREA: Areas shall be used]: Geminus Outskirts (/area/planets/Geminus/indoor/quest_instance) ([0x400000b]) (0,0,0) is unused.
## UNIT_TEST ##: [AREA: Areas shall be used]: Geminus Outskirts (/area/planets/Geminus/indoor/quest_instance) ([0x400000b]) (0,0,0) is unused.
## UNIT_TEST ##: !!! FAILURE !!! [AREA: Areas shall be used]: Found 7 unused areas.
```
occurs during Stranded.

2021-09-25 01:14 UTC, bloxgate approved these changes
LGTM

2021-09-25 19:35 UTC, merged