toggle flight verb
HaloSpaceStation/HaloSpaceStation13 pull request #3032
Opened 2021-12-27 02:35 UTC by PotatoTheDeveloper

Adds a verb that activates and deactivates jetpacks and wings, to be able to create macros and such.

:cl: Patata
rscadd: Adds Toggle-Flight verb to jetpacks and wings.
/:cl:

2021-12-27 09:23 UTC, X0-11 requested changes

2021-12-27 09:23 UTC, X0-11 commented on code/modules/halo/clothing/jetpacks.dm
> +/obj/item/flight_item/verb/toggle_flight()
This is bypassing the checks normally done when you press the UI Button. Go move the usual UI button code into a seperate proc and then use that proc for both of these to ensure the checks are consistent.

2021-12-27 17:20 UTC, PotatoTheDeveloper commented on code/modules/halo/clothing/jetpacks.dm
> +/obj/item/flight_item/verb/toggle_flight()
Aight done

2021-12-31 21:46 UTC, X0-11 approved these changes

2021-12-31 21:46 UTC, merged