Porting code/modules/halo from alpha2.0 to alpha.
HaloSpaceStation/HaloSpaceStation13 pull request #304
Opened 2017-08-13 20:18 UTC by X0-11

This also incorporates and ports #296 and #295 .
I am unsure how certain elements were to be included later on. Those files have been left unincluded in the DMB.

2017-08-13 22:22 UTC, bloxgate requested changes
I'm sure there will be more issues from just straight porting this, but I've marked everything travis has complained about, plus one or two I saw.

I've marked any bad occurrences of << that I saw too. I'm sure I've missed several though.

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +					G << "Return to your body to be revived!"
We'll need to replace << occurrences with to_chat. I believe using it for bit-shifts which I saw somewhere else in this will be fine.

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +		H << "You feel a sudden stabbing pain in your chest"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +		H << "You feel your heart thundering in your chest"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +		o.owner << "<span class = 'notice'>You feel the biofoam stop the bleeding in your [o.name]</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +				H <<"<span class = 'notice'>You feel your [o.name] knitting itself back together</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +				H <<"<span class = 'notice'>You feel your [I.name] knitting itself back together</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +				o.owner << "<span class = 'notice'>You feel the bleeding in your [o.name] slow.</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +				M <<"<span class ='userdanger'>You feel [dam ? "your [O.name] collapse" : "immense pressure on your [O.name]" ].</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +			M <<"<span class ='danger'>You feel your [O.name] being crushed.</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +		world << "No Team Spawnpoints found. Falling back to Free For All spawns."
I'm sure there's a to_world along with to_chat, so that needs to be looked into.

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/gamemodes/slayer-team-slayer/gamemode.dm
> +	world <<"<span classs = 'danger'>Scores: \n [team1.name] : [team1.score] \n [team2.name] : [team2.score]</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/insurrection/gamemode.dm
> +		world << "<span class='danger'>Loading Insurrectionist base, please stand by...</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/insurrection/gamemode.dm
> +			world << "<span class='danger'>Done ([(world.time - starttime)/10]s).</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/insurrection/gamemode.dm
> +		world << "<span class='danger'>Could not load Insurrectionist base!</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/insurrection/gamemode.dm
> +	world << "<span class='danger'>Spawning random Insurrectionist shuttles...</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/insurrection/gamemode.dm
> +	world << "<span class='danger'>	Done spawning innie shuttles ([(world.time - starttime)/10]).</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/insurrection/gamemode.dm
> +		world << sound('sound/AI/commandreport.ogg')
<< ?

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/insurrection/gamemode.dm
> +	world << "<span class='info'>UNSC score: [unsc_score] points, Insurrection score: [innie_score] points</span>"
<< * 3

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/jobs/UNSC_ship/_access.dm
> +/var/const/access_unsc_bridge = 300
Apparently some of these accesses conflict with vanilla ones. That'll need to be fixed to make travis happy.

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/jobs/UNSC_ship/_defines.dm
> +var/const/OPSCO				=(1<<4)
Don't suppose this could have some uniform formatting?

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/misc/tools_items_gear.dm
> +/obj/item/weapon/storage/firstaid/erk
This isn't actually big enough to hold the mask and tank. That'll need to be fixed.

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/power/cooling_manifold.dm
> +		usr << "<span class='notice'>You cannot rotate [src] as it is bolted down.</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/power/cooling_manifold.dm
> +			world << "coolant flow modified reactor heat by [energy_transfer]"
<< * 4

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/power/fuel_packet.dm
> +	user << "It has [fuel_left] out [max_fuel] units of fuel left ([100 * fuel_left/max_fuel]%)."
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/power/reactor.dm
> +			user << "<span class='warning'>There is already a fuel packet in there.</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/species_items/kig-yar.dm
> +		u <<"<span class = 'notice'>Night Vision deactivated.</span>"
<<

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/species_items/sangheili.dm
> +	m.vessel.add_reagent("blood",30) // 30 blood should be enough to resist a shallow cut at max damage for that type.
Won't that always run, eventually filling their entire bloodstream to the point that medicine can't be used? Or cause bad effects if high blood pressure actually does something in game.

2017-08-13 22:22 UTC, bloxgate commented on code/modules/halo/species_items/sangheili.dm
> +/datum/language/sangheili
Apparently the key for this (x) conflicts with that of the cortical borer's. We should probably see if s is taken, and if not give that to this.

2017-08-13 22:24 UTC, X0-11 commented on code/modules/halo/species_items/sangheili.dm
> +	m.vessel.add_reagent("blood",30) // 30 blood should be enough to resist a shallow cut at max damage for that type.
I remember checking for maximum capacity of the blood holder, but I was told that the add_reagent proc already did that.

2017-08-15 02:04 UTC, bloxgate commented on code/modules/halo/species_items/sangheili.dm
> +	m.vessel.add_reagent("blood",30) // 30 blood should be enough to resist a shallow cut at max damage for that type.
Even if it does, this is still a bad idea. At best that'd only leave 30 units in blood stream for **any** additional reagents at some point. You should only do that if blood level is below normal.

2017-08-15 02:10 UTC, bloxgate requested changes
Looking better.

Still a lot of <<'s that need taking care of.

2017-08-15 02:10 UTC, bloxgate commented on code/modules/halo/misc/tools_items_gear.dm
> +/obj/item/weapon/storage/firstaid/erk
Still too small. Needs to hold size 4 items.

2017-08-19 12:29 UTC, X0-11 commented on code/modules/halo/species_items/sangheili.dm
> +	m.vessel.add_reagent("blood",30) // 30 blood should be enough to resist a shallow cut at max damage for that type.
I'm unsure if the blood holder is a separate thing from the normal reagent holder.

2017-08-19 12:29 UTC, caelaislinn commented
From Travis: 

29 world<< uses (expecting 1 or less)

Should be easy to fix up

2017-08-19 13:09 UTC, caelaislinn commented on code/modules/halo/species_items/sangheili.dm
> +	m.vessel.add_reagent("blood",30) // 30 blood should be enough to resist a shallow cut at max damage for that type.
Get the blood holder by doing
`var/datum/reagent/blood/B = owner.get_blood(owner.vessel)`
it looks like its part of the normal reagent holder but use this helper. It looks like by default the liver regenerates 0.1 blood per tick or more if iron pills have been ingested.

2017-08-19 18:32 UTC, X0-11 commented
It appears that the regex which checks for <<'s doesn't exclude bitshifts. I have added the amount of bitshifts in halo/jobs/unsc_ship.dm to the allowed amount, bringing it to 772.

2017-08-22 01:34 UTC, caelaislinn commented on code/game/jobs/jobs.dm
> +var/const/MED               =(1<<2)*/
????

2017-08-22 01:37 UTC, caelaislinn commented
Not really happy with the amount of changes partly because it's so difficult to review and partly because the increased number of additions means higher chances of bugs and performance issues slipping through. I'm going to make an issue for someone to replace the shiftout operators in the chemicals with a to_chat proc or somesuch

2017-08-22 01:37 UTC, merged

2017-08-22 04:53 UTC, bloxgate commented on code/game/jobs/jobs.dm
> +var/const/MED               =(1<<2)*/
I believe this was to fix an access conflict issue with our jobs and those on board the Torch.

2017-08-22 07:21 UTC, caelaislinn commented on code/game/jobs/jobs.dm
> +var/const/MED               =(1<<2)*/
Ahh hardcoded job defines are a sucky way to do it. We'll need to rethink about this when we get around to revisiting overmap

2017-08-22 07:48 UTC, caelaislinn commented
Weapon sprites appear to be working but none of the clothing. I'm going to try and fix enough to get team slayer gear working