Finally, Kig-Yar Shield Fixes
HaloSpaceStation/HaloSpaceStation13 pull request #3075
Opened 2022-01-16 04:25 UTC by PotatoTheDeveloper

Fixes the kigyar gauntlet shields so they dont suck every projectile and their after-effects like black hole.

:cl: Patata
rscadd: Kig-Yar gauntlet shields now can be destroyed with EMP, and no longer swallow explosives.
/:cl:

2022-01-16 04:54 UTC, Stingray540 commented
Has this actually been confirmed as a bug by XO? I'm not sure if it's an "intended feature" or not. I'm for this though, about time.

2022-01-16 04:56 UTC, PotatoTheDeveloper commented
> Has this actually been confirmed as a bug by XO? I'm not sure if it's an "intended feature" or not. I'm for this though, about time.

if it is a feature, its a poorly though out one, no one wants this, this is awful in every way possible and just makes the shield too damn strong, they can tank even scorpion shots, spnkrs do nothing against them

2022-01-16 04:57 UTC, Stingray540 commented
> > Has this actually been confirmed as a bug by XO? I'm not sure if it's an "intended feature" or not. I'm for this though, about time.
> 
> if it is a feature, its a poorly though out one, no one wants this, this is awful in every way possible and just makes the shield too damn strong, they can tank even scorpion shots, spnkrs do nothing against them

I agree, though XO may just hit this with "skill issue". We'll see.

2022-01-16 06:04 UTC, Sgtwok commented
I agree with this.

2022-01-17 20:26 UTC, X0-11 requested changes

2022-01-17 20:26 UTC, X0-11 commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +		if(istype(projectile, /obj/item/projectile))
Can't you do the checking beforehand

2022-01-17 20:26 UTC, X0-11 commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +/obj/item/clothing/gloves/shield_gauntlet/emp_act(severity) //basically how body shields handle emp but without the feedback messages because that is already handled by drain_shield
no emp is intended as the shields are meant to be harder to brute force

2022-01-17 20:31 UTC, PotatoTheDeveloper commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +/obj/item/clothing/gloves/shield_gauntlet/emp_act(severity) //basically how body shields handle emp but without the feedback messages because that is already handled by drain_shield
Unsc has no EMP tool to use against these shields, like with elite shields, this is here just in case for special moments, i believe it changes nothing balance-wise

2022-01-17 20:33 UTC, PotatoTheDeveloper commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +		if(istype(projectile, /obj/item/projectile))
Before what? Like when the drain_shields is executed? Because i think that would give problems because the shields can also block melee weapons and things completely unrelated to projectiles

2022-01-17 20:37 UTC, X0-11 requested changes

2022-01-17 20:37 UTC, X0-11 commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +		if(istype(projectile, /obj/item/projectile))
You're already checking if it's a projectile or not anyway. Drain shields doesn't need to handle this.

2022-01-17 20:37 UTC, X0-11 commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +/obj/item/clothing/gloves/shield_gauntlet/emp_act(severity) //basically how body shields handle emp but without the feedback messages because that is already handled by drain_shield
Then, really, is there a need to change it?

2022-01-17 20:40 UTC, PotatoTheDeveloper commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +/obj/item/clothing/gloves/shield_gauntlet/emp_act(severity) //basically how body shields handle emp but without the feedback messages because that is already handled by drain_shield
The same can be said about elite shields tho, but yea i agree it has no effects on the actual game, unless some grunt misfires and friendly fires a kigyar shield, lemme just take it off the pr

2022-01-17 21:29 UTC, PotatoTheDeveloper commented
Aight emp removed, changed where its handled and its now a one line PR, also updated the changelog to remove the EMP line.

2022-01-17 21:31 UTC, X0-11 requested changes

2022-01-17 21:31 UTC, X0-11 commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +		P.on_impact(src)
this should be above this if statement, and should be checking if it's a projectile before calling on_impact

2022-01-17 21:33 UTC, PotatoTheDeveloper commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +		P.on_impact(src)
Ok im actually confused, moving the code there will basically make the on_impact happen two times, because what happens if there is no shield connected AND the projectile hits the target normally?

2022-01-17 21:36 UTC, X0-11 commented on code/modules/halo/weapons/covenant/shield_gauntlet.dm
> +		P.on_impact(src)
good catch, just keep it where it is and make it check projectile then. Should just be a simple if(istype(p))

2022-01-20 21:26 UTC, X0-11 approved these changes

2022-01-20 21:26 UTC, merged