WIP DO NOT MERGE YET Eluxor's new brutes'"
HaloSpaceStation/HaloSpaceStation13 pull request #3076
Opened 2022-01-16 15:17 UTC by Eluxor

:cl: Eluxor
rscadd: Added prettier brutes.
tweak: DO NOT LEWD THE NEON BRUTE.
/:cl:

2022-01-20 21:30 UTC, X0-11 requested changes

2022-01-20 21:30 UTC, X0-11 commented on code/modules/mob/new_player/preferences_setup.dm
> +	preview_icon.Blend(stamp, ICON_OVERLAY, 55, 1)
Explain these changes?

2022-01-20 21:30 UTC, X0-11 commented on code/modules/halo/weapons/covenant/brute.dm
> +#define JIRALHANAE_WEAPONS 'code/modules/halo/covenant/species/jiralhanae/jiralhanae_weapons_big.dmi'
Why'd you define this if you never used it anywhere? You should replace all occurances of that file-path with JIRALHANAE_WEAPONS

2022-01-20 21:33 UTC, Eluxor commented on code/modules/mob/new_player/preferences_setup.dm
> +	preview_icon.Blend(stamp, ICON_OVERLAY, 55, 1)
Just a small fix to make the dolls of the character more separated and the window bigger. Because nowdays its quite small and barely visible for the bigger races.

2022-01-20 21:33 UTC, Eluxor commented on code/modules/halo/weapons/covenant/brute.dm
> +#define JIRALHANAE_WEAPONS 'code/modules/halo/covenant/species/jiralhanae/jiralhanae_weapons_big.dmi'
I was going to, but it seems I forgot, I will fix it now.

2022-01-21 16:05 UTC, X0-11 approved these changes

2022-01-21 16:05 UTC, merged