Slayer Changes.
HaloSpaceStation/HaloSpaceStation13 pull request #313
Opened 2017-09-07 15:51 UTC by X0-11

Fixes weapons. #310 
Adds spartan helm light 
Adds shields to slayer spartan suits 
Makes needler more effective at embedding 
Adds medical dispensing system to slayer spartan suits. 
Lowers pain from biofoam application.
Auto-allows respawn for all ghosts every 30 seconds.

2017-09-07 20:55 UTC, X0-11 commented
Note: Bloxgate noted something weird going on with Travis in the code test. Still passes though.

2017-09-08 08:12 UTC, caelaislinn commented
Your commit messages need to be more descriptive and ideally each different changeset needs to be a separate commit (what's called "atomic" commits"). I think I'll have time for a review tonight if not bug me on discord.

2017-09-08 10:17 UTC, X0-11 commented
Sorry, I'm prone to commiting changes in large chunks. I've put a bit more into the descriptions of the commits.

2017-09-08 22:23 UTC, bloxgate commented
If you're comfortable enough with rebasing, it's simple enough to change your commit messages since this hasn't been merged in yet.

2017-09-09 08:18 UTC, X0-11 commented
With the amount of changes per commit, it's kinda hard to summarise in the title. Info on the changes have been placed into the descriptions of the commits.

2017-09-10 08:11 UTC, caelaislinn commented
If you have too many changes per commit to describe them all in the commit msg, you aren't doing enough commits

2017-09-10 08:36 UTC, X0-11 commented
I'll try to commit correctly in the future then.

2017-09-11 05:06 UTC, caelaislinn requested changes
The main changes I'd like to see are the commits reapplied with descriptive messages. I can sit down with you and guide you through the process if you like. We should probably also get a bugfix for the mode_on_mob_death hook runtiming.

2017-09-11 05:06 UTC, caelaislinn commented on code/modules/halo/gamemodes/slayer-team-slayer/death_asteroid_spawns.dm
> +
Unnecessary line changes

2017-09-11 05:06 UTC, caelaislinn commented on code/modules/halo/gamemodes/slayer-team-slayer/mode_slayer.dm
> +#define RESPAWN_TIME 300
Was going to comment that this seems a bit high without observing but then saw you have death observing lower down. Looks good. I'd suggest making this a var in the gamemode so it can edited for testing... or maybe players could even vote for shorter/longer respawn times. It might also be an idea to test different respawn times for different player counts (shorter respawns on smaller maps/less players to ensure the action stays high).

2017-09-11 05:06 UTC, caelaislinn commented on code/modules/halo/gamemodes/slayer-team-slayer/mode_slayer.dm
> +		scores_with_names[killer.name] += 1 */
There was a bug with score outputting from my code in testing. Keep an eye on it for now and see if it's good.

2017-09-11 05:06 UTC, caelaislinn commented on code/modules/halo/gamemodes/slayer-team-slayer/slayer_outfits.dm
> +	flags = OUTFIT_HAS_JETPACK //Not a jetpack, but I think it does the same thing. Stops backpack from spawning on char's back.
By default it is flags = OUTFIT_HAS_BACKPACK so just change it to flags = 0 should do this

2017-09-11 05:06 UTC, caelaislinn commented on code/modules/halo/weapons/ammo.dm
> -#define CASELESS		3
Why cut these out?

2017-09-11 06:11 UTC, X0-11 commented on code/modules/halo/weapons/ammo.dm
> -#define CASELESS		3
The defines don't match up with the ones in the actual files.

2017-09-12 08:22 UTC, X0-11 commented
Closing this to re-open with more descriptive commits.

2017-09-12 08:22 UTC, closed without merging