Slayer changes
HaloSpaceStation/HaloSpaceStation13 pull request #314
Opened 2017-09-12 08:26 UTC by X0-11

Fixes weapons. #310
Adds spartan helm light
Adds shields to slayer spartan suits
Makes needler more effective at embedding
Adds medical dispensing system to slayer spartan suits.
Lowers pain from biofoam application.
Auto-allows respawn for all ghosts every 30 seconds. #312
Add a simple shield level display

2017-09-12 08:45 UTC, X0-11 commented
Hm. Merge confilcts with the changelog.

2017-09-12 11:17 UTC, caelaislinn requested changes
How did you go with the on death runtime? I can have a look at that one for you if you like

2017-09-12 11:17 UTC, caelaislinn commented on code/modules/halo/gamemodes/slayer-team-slayer/mode_slayer.dm
> +	for(var/mob/living/carbon/human/i in GLOB.player_list)
Aargh this is a bad thing to put in a process() tick. Did you look at mucking around with life or creating a new species?

2017-09-12 12:44 UTC, X0-11 commented on code/modules/halo/gamemodes/slayer-team-slayer/mode_slayer.dm
> +	for(var/mob/living/carbon/human/i in GLOB.player_list)
Perhaps sleep() it? I'll look into what could be used instead.

2017-09-12 13:31 UTC, caelaislinn approved these changes

2017-09-12 15:06 UTC, X0-11 commented
I have no idea what's causing the fail/runtime. Tried making it return 1, still fails/runtimes.

2017-09-15 12:46 UTC, X0-11 commented
Besides the runtime which was present before my changes, this should be ready to merge.

2017-09-18 17:50 UTC, X0-11 commented
Can't believe I didn't check that. Should be ready for merge now then

2017-09-18 22:18 UTC, merged