Base Insurrection GM
HaloSpaceStation/HaloSpaceStation13 pull request #315
Opened 2017-09-29 17:40 UTC by X0-11

A gamemode that incorporates the multi-z insurrectionist asteroid base and a UNSC staging area that utilises drop pods to attempt to destroy or take over the base.

TODO: Create the Insurrectionist GM itself.

2017-10-01 11:28 UTC, X0-11 commented
Just insurrection map travis checks now.

2017-10-02 05:46 UTC, bloxgate commented on code/modules/halo/clothing/marine.dm
> +#undef MARINE_OVERRIDE
Shouldn't both of those defines be undefined?

2017-10-02 05:46 UTC, bloxgate commented on code/modules/halo/misc/payload.dm
> +	anchored = onoff
I don't think a proc called toggle_anchor should let you set the state directly.

Something like
```dm
anchored = !anchored
```
feels like it would be more appropriate.

2017-10-02 05:46 UTC, bloxgate commented on code/modules/halo/misc/tools_items_gear.dm
> -		/obj/item/weapon/storage/pill_bottle/inaprovaline,
At the very least you should keep inaprovaline as well. I don't think biofoam replaces its function.

On that note, does biofoam fix burns as well?

2017-10-02 06:08 UTC, X0-11 commented on code/modules/halo/misc/tools_items_gear.dm
> -		/obj/item/weapon/storage/pill_bottle/inaprovaline,
Bandages and salves, it's a slower heal than applying medicine directly but yes.

2017-10-02 06:08 UTC, X0-11 commented on code/modules/halo/misc/payload.dm
> +	anchored = onoff
Yeah, I wasn't really thinking properly about the name. Only needed it as an overridable proc for the innie variant of the bomb.

2017-10-02 06:11 UTC, X0-11 commented on code/modules/halo/clothing/marine.dm
> +#undef MARINE_OVERRIDE
Yep. Good catch.

2017-10-17 11:54 UTC, caelaislinn requested changes
uncommit the backup maps, also instead of "UNSC Assault" I think you meant "ODST"?

2017-10-17 15:14 UTC, X0-11 commented
Changes applied

2017-10-19 01:56 UTC, bloxgate requested changes
Could you make a YML changelog at least?

2017-10-19 07:07 UTC, bloxgate approved these changes

2017-10-20 23:29 UTC, caelaislinn commented on code/modules/halo/misc/payload.dm
>  	anchored = onoff
I try to avoid ambiguous var naming like this because it's unclear what a value in the var actually means. Instead do something like var/is_anchored where 1 clearly means anchored, and 0 clearly means unanchored

2017-10-20 23:29 UTC, caelaislinn approved these changes

2017-10-20 23:30 UTC, merged