restructures the way the code handles popbalance deadlocks
HaloSpaceStation/HaloSpaceStation13 pull request #3178
Opened 2022-03-20 15:34 UTC by X0-11

2022-03-20 20:49 UTC, bloxgate requested changes, later dismissed

2022-03-20 20:49 UTC, bloxgate commented on code/game/jobs/job/job.dm
>  									if(!(f_type in last_checked_lock))
Unless I'm misreading the indentation here, this will remove `my_faction.type` from `last_checked_lock` if there's any faction that should be balanced that's not already in `last_checked_lock`, rather than all factions being in the list. That feels like that's not what you're intending here.

2022-03-22 00:24 UTC, ilikesaying commented
does the unsc shotgun really need the nerf? will it even get any shield damage to compensate its lack of raw damage compared to the mauler?

2022-03-22 01:15 UTC, ilikesaying commented
Needle deals the same hit-damage as the smg now...

2022-04-02 09:32 UTC, X0-11 commented on code/game/jobs/job/job.dm
>  									if(!(f_type in last_checked_lock))
I think I need to restructure that, Yeah.

2022-04-02 09:32 UTC, X0-11 commented on code/game/jobs/job/job.dm
>  									if(!(f_type in last_checked_lock))
I think I need to restructure that, yeah.

2022-04-15 23:11 UTC, BDpuffy420 commented
update on this please so it can get merged

2022-04-15 23:58 UTC, BDpuffy420 approved these changes

2022-04-15 23:59 UTC, merged