Update Tri-Adrenaline
HaloSpaceStation/HaloSpaceStation13 pull request #319
Opened 2017-10-28 05:25 UTC by bloxgate

Ports a simplified form of the new defibrillator code into tri-adrenaline
Fixes brain deaths getting stuck in a revive loop.

Fixes #318

2017-11-01 17:55 UTC, X0-11 approved these changes

2017-11-04 06:53 UTC, caelaislinn commented on code/modules/halo/chemicals/medicine.dm
> +		if(H.stat != DEAD)
Why was this inverted? What's the relation between stat and whether the organ/heart has stopped?

2017-11-04 07:45 UTC, caelaislinn requested changes
Confused over H.stat implications

2017-11-04 11:33 UTC, X0-11 commented on code/modules/halo/chemicals/medicine.dm
> +		if(H.stat != DEAD)
I believe DEAD is set only when your brain is irrepairable, which has in the past caused revive spam due to the person instantly dying after revive. I don't think organ damage has any bearing on the DEAD stat.

2017-11-05 00:56 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +		if(H.stat != DEAD)
Yes, @X0-11 is correct. Once H.stat reaches dead, the player is braindead and cannot be revived by any means. If this check isn't inverted the player will be constantly revived and then insta-killed as it was doing previously.

2017-11-06 08:29 UTC, caelaislinn commented on code/modules/halo/chemicals/medicine.dm
> +		if(H.stat != DEAD)
How does this interact with the issue of brain asphyxiating being the only way to die?

2017-11-06 16:11 UTC, X0-11 commented on code/modules/halo/chemicals/medicine.dm
> +		if(H.stat != DEAD)
Brain damage is the only way to die, whether it be direct or through other means like asphyxiation. This stops the chemical from attempting to continually revive people who are unrecoverable. The chem no longer brings people back from full death, it just makes people conscious again after taking enough damage to collapse into a critical condition.

2017-11-06 21:08 UTC, bloxgate commented on code/modules/halo/chemicals/medicine.dm
> +		if(H.stat != DEAD)
@X0-11 is on the right track, but doesn't have it exactly. Large amounts of brute damage, hypovolemic shock, or a few other situations can cause cardiac arrest now. This quite quickly increases the rate at which you take brain damage due to low oxygen. CPR only has a small chance of restarting a patient's heart.

Tri-adrenaline is now guaranteed to restart the heart of a patient if they still have brain activity. This will in theory help stabilize them until proper treatment can be done.

2017-11-07 09:36 UTC, caelaislinn commented on code/modules/halo/chemicals/medicine.dm
> +		if(H.stat != DEAD)
Sure. Baymed ¯\_(ツ)_/¯

2017-11-07 09:36 UTC, caelaislinn approved these changes

2017-11-07 13:49 UTC, merged