Insurrection fixes and additions
HaloSpaceStation/HaloSpaceStation13 pull request #320
Opened 2017-10-30 14:52 UTC by X0-11

Adds innie-unique armor
Fixes duplicate comms messages
Adds ODST assault pod autolaunch
Buffs biofoam to allow for quick removal of embedded objects.

2017-11-01 17:58 UTC, bloxgate requested changes

2017-11-01 17:58 UTC, bloxgate commented on code/modules/halo/clothing/insurrectionists.dm
> +#define INNIE_OVERRIDE 'code/modules/halo/clothing/inniearmor.dmi'
You're missing an #undef

2017-11-01 17:58 UTC, bloxgate commented on code/modules/halo/power/reactor.dm
> +	//	explosion(get_turf(src), max_damage - 6, max_damage - 3, max_damage - 1, max_damage + 1) These explosions seem to cause widespread devastation on the innie_base maps. Commenting out for now.
I would leave these in and simply make a non-explody version, or use subspace reactors for maps where we don't want people setting up power, such as insurrection.

2017-11-01 17:58 UTC, bloxgate commented on maps/insurrection/insurrection.dm
> +	var/autolaunchtime = 10 MINUTES //At runtime, this stores the time in ticks after roundstart will launch at.
What about latejoins?

2017-11-01 17:58 UTC, bloxgate commented on nano/templates/fusion_reactor.tmpl
> +<h3>Mark II Hanley-Messer Deuterium Fusion Drive</h3>
Uh.... wasn't this file already a thing?

2017-11-01 18:47 UTC, X0-11 commented on maps/insurrection/insurrection.dm
> +	var/autolaunchtime = 10 MINUTES //At runtime, this stores the time in ticks after roundstart will launch at.
Once all pods are launched, the UNSC assault area is locked down, and respawns are made unavailable.

2017-11-01 18:47 UTC, X0-11 commented on nano/templates/fusion_reactor.tmpl
> +<h3>Mark II Hanley-Messer Deuterium Fusion Drive</h3>
I don't think it was ported over, and if it was, it wasn't working for the reactor.

2017-11-01 18:48 UTC, X0-11 commented on code/modules/halo/power/reactor.dm
> +	//	explosion(get_turf(src), max_damage - 6, max_damage - 3, max_damage - 1, max_damage + 1) These explosions seem to cause widespread devastation on the innie_base maps. Commenting out for now.
It's only a temp thing to stop mapwide destruction when they explode. There's still an underlying issue with explosions, it seems.

2017-11-01 20:01 UTC, X0-11 commented on code/modules/halo/clothing/insurrectionists.dm
> +#define INNIE_OVERRIDE 'code/modules/halo/clothing/inniearmor.dmi'
Fixed

2017-11-03 01:01 UTC, BDpuffy420 commented
Are the changes good?

2017-11-03 06:01 UTC, bloxgate reviewed
Don't know enough about comms code to really comment much on that.

One thing though. Are you sure the bullet proofing values on those armors are good? Some of them feel a little low to me.

2017-11-03 07:49 UTC, X0-11 commented
Innie armor is actually better at stopping bullets than ODST armor, but it's also worse in every other capacity.

2017-11-03 18:08 UTC, bloxgate commented
Uh... that doesn't make much sense IMO.

Shouldn't the innies have worse or equal equipment since they're using **old** UNSC gear?

2017-11-03 18:14 UTC, X0-11 commented
It's there to provide a small edge to the innies. I'd justify it with the innie gear being specialised towards bullet resistance, after all, that's mostly what they have to contend with, whilst ODST gear is slightly more broad in it's resistances. The difference between the armours is small.

2017-11-03 19:08 UTC, bloxgate commented
Alright then. I'll approve, but @BDpuffy420 please don't merge until someone who knows more about comms looks at the code for that.

2017-11-03 19:09 UTC, bloxgate approved these changes

2017-11-04 07:10 UTC, caelaislinn commented on code/modules/halo/power/reactor.dm
> +	//	explosion(get_turf(src), max_damage - 6, max_damage - 3, max_damage - 1, max_damage + 1) These explosions seem to cause widespread devastation on the innie_base maps. Commenting out for now.
Are they too strong? Or are they just exploding every round because people don't know the mechanics and it's disrupting gameplay?

2017-11-04 07:11 UTC, caelaislinn commented on code/modules/halo/comms/commsitems.dm
> +		recieving_frequencies.Add(halo_frequencies.innie_freq)
These comms changes will need to be tested with 2-3 people. Easiest way is to get the code live and test it there, or @X0-11 you/we can organise an adhoc test running of your dev computer to make sure it works.

2017-11-04 07:44 UTC, caelaislinn approved these changes
Feedback from live comms test needed

2017-11-04 07:44 UTC, merged