Innie gear tweaks
HaloSpaceStation/HaloSpaceStation13 pull request #3206
Opened 2022-08-18 23:14 UTC by CapCamIII

I saw people complaining day before yesterday about innie gear, especially some of the high-tier things such as colossus and zeal, being bad. So I buffed everything. Changelog has every single change in tldr form, but I'll go over each individually to explain why I did it.

1. LE-AP M125 ammo, gives innies an ammo choice that is directly better against non-shielded foes, but when going up against shields it falls short. Might be a bit OP, I can tune it down if asked.
2. Innies not having gloves sucks, hand armor is required or you get hand-gibbed as soon as you enter combat.
3. Gives SOE standard gloves, like every other role, no reason not to.
4. Mines feel like they fit the role of innies.
5. Innie LMG magazines that use the above M125 ammo, people can just re-load normal M545 magazines with M125 ammo if I didn't do this anyway, plus it makes sense.
6. Without the guns I removed, these ammo types are useless, so I replaced them with what innies now have.
7. Useful buff for ODSTs, provided they have an ODST SL or are with a command role.
8. I am going to enable personalized supply drops in a future PR for specialist and power roles, nothing effects the ingame as of now from this
9. Useless attachments, gives innies more of non-useless attachments, and RDS have a cool sprite on the DMR.
10. SOE shouldn't have marine boots, prevents wasted armor boxes.
11. A: MA37 sets innies apart from UNSC in an interesting way, especially with the M125 magazines I added. The 32 round capacity makes innies worse in long-term engagements due to lack of ammo, but in short-term engagements they preform better against non-shielded due to M125 mags.     B: Makes innies cooler, sets them apart, I also buffed the M45 to have the same capacity as M90, so no real balance change.
12. Sets MA37 apart from MA5B more, instead of being a downgrade its a sidegrade.
13. See 11B
14. Makes going through mine-types not cancer to do, allows them to be told apart in a vendor.
15. Colossus had honestly awful stats for the debuff from slow it gave you, this makes it really quite good, and the EVA change allows it to be used on a space-assault as a heavy-assault troop, sprite appears to completely sealed, so doesn't NOT make sense.
16. Zeal felt a bit underwhelming speed-wise, as often you have to stack a lot of gear and that removes the buff, EVA change allows them to assault via space, sprite appears fully sealed as well.
17. Gives roles that should have supply drops, the ability to call them, gameplay mostly non-effected as only 3 of the roles I added supply drops to are not admin-spawn.
18. I didn't want to give murmillo supply drops too, and having only 1 of the 2 primary tvoan roles have them doesn't make sense.
19. Recon hog had no real purpose, transport does.

Again, please do let me know if I need to change anything, I do feel these changes, at least the basis of them, would be quite good for the balance of revolution/OC.
Thats all.
:D

:cl: CaptainCamo
rscadd: 7.62 M125 Light Explosive Armor Piercing ammunition, comes in MA37 and M545 magazines. It does an extra 5 damage, has 5 AP, at the cost of -15 shield damage
rscadd: Insurrection armor boxes now come with gloves, equal stats to marine gloves, insulated.
rscadd: SOE gloves are now insulated and heat-proofed, that means they don't get shocked by doors and can take light-tubes from walls now
rscadd: Mines are now in innie heavy weapons vendor
rscadd: Innie heavy weapons vendor now have the option of vending M545 M125 magazines instead of just M118, see above for what that entails
rscadd: Innie ammo supply drops now have MA37, shotgun shells(buckshot), and extra DMR ammunition to replace the MA5B and BR ammo
rscadd: ODST officer, UNSC XO, and UNSC CO now have access to ODST supply drops, this is the same as a normal supply drop but instead of M6D and M7 magazines, it has M6S and M7S magazines.
rscadd: A bunch of roles now have command rank 1, this is in preperation for enabling personalized supply drops for specialist/power roles, no current effect.
rscdel: A lot of innie attachment vendor options, kept those that can fit on the guns left in their weapon vendor.
bugfix: SOE roles now all spawn with SOE magboots
tweak: MA5Bs in innie vendors have been replaced with MA37s, and M90s have been replaced with M45s
tweak: MA37 now has better accuracy, and a 4(8) rnd burst instead of 5(10) rnd burst. It also comes loaded by standard with above M125 ammunition
tweak: M45-TS shotguns now have 8+1 shell capacities
tweak: Re-named all the different types of preset mines to their actual function
tweak: Colossus armor has had its armor thickness buffed, armor overall buffed, and now has EVA capability, as well as its helmet light having an expanded lighting range
tweak: ZEAL armor is now EVA capable, a bit worse at defeating bullet and explosive damage, but has a bit more energy damage protection as well as having an additional +1 speed
tweak: The following roles now have access to supply drops: T'voan champion, Sanghelli Zealot, Sanghelli Honor Guard, Sanghelli Spec Ops, Minor Prophet, SOE Commando Officer, SOE Commando Leader.
tweak: T'voan commando no longer has supply drops, play champion instead.
tweak: UNSC/URF vehicle supply drop now sends a transport warthog, which now moves the same speed as a recon hog.

/:cl:

2022-08-19 11:22 UTC, X0-11 commented on code/modules/halo/clothing/insurrectionists.dm
>  	slowdown_general = 1
With the buffs to the baseline armour this might need to be upped a little to 1.2 or something like that?

2022-08-19 11:22 UTC, X0-11 commented on code/modules/halo/leader_support/supply_drop_variants.dm
> +/* //disabled, I will complete this at a later date in a different PR, groundwork is here, however.
What's keeping this from being enabled?

2022-08-19 11:22 UTC, X0-11 commented on code/modules/halo/leader_support/supply_drop_variants.dm
> +/datum/support_option/supply_drop/personalised_ammo/covenant/create_drop_item(var/turf/turf_at,var/mob/living/m)
This isn't needed, the subtype will inherit this handling.

2022-08-19 11:22 UTC, X0-11 commented on code/modules/halo/leader_support/supply_drop_variants.dm
> +	name = "Supply Drop (UNSC Transport Vehicle)"
Recon.

2022-08-19 11:22 UTC, X0-11 commented on code/modules/halo/machinery/gunvendors.dm
> +	products = list(
This was already inheriting the product list. What's with the override?

2022-08-19 11:22 UTC, X0-11 commented on code/modules/halo/weapons/MA37.dm
> +	burst = 4
Please explain these gun stat changes. They're ideally meant to be identical to their unsc counterpart.

2022-08-19 11:22 UTC, X0-11 commented on code/modules/halo/weapons/shotguns.dm
> +	max_shells = 8//yeah yeah not lore friendly but balance and making innies a bit more different
muh lore

2022-08-19 17:53 UTC, CapCamIII commented on code/modules/halo/leader_support/supply_drop_variants.dm
> +/* //disabled, I will complete this at a later date in a different PR, groundwork is here, however.
I don't know how to, simply uncommenting it doesn't work and causes a build error, and I don't know how to fix it, I can only re-use code, mostly.

2022-08-19 17:53 UTC, CapCamIII commented on code/modules/halo/clothing/insurrectionists.dm
>  	slowdown_general = 1
Will do.

2022-08-19 17:56 UTC, CapCamIII commented on code/modules/halo/weapons/MA37.dm
> +	burst = 4
Having just a 32 round mag makes it quite different than the MA5
5 round burst doesn't divide equally and the 1.8 burst-delay makes it a worse version of the MA5
I changed burst to 4(8 ext burst), so it would divide equally into 32, and burst delay to give it a better burst fire rate to compensate for the lost rounds.

2022-08-19 17:56 UTC, CapCamIII commented on code/modules/halo/weapons/shotguns.dm
> +	max_shells = 8//yeah yeah not lore friendly but balance and making innies a bit more different
DIdn't want to touch the balance, but I'll revert that if you want

2022-08-19 17:59 UTC, CapCamIII commented on code/modules/halo/machinery/gunvendors.dm
> +	products = list(
Changed the product list to give them different weapons and removing the BR from the options.

2022-08-19 18:23 UTC, X0-11 commented on code/modules/halo/leader_support/supply_drop_variants.dm
> +/* //disabled, I will complete this at a later date in a different PR, groundwork is here, however.
Ping me in the discord and run me through the build error you get, it might be easily fixable.

2022-08-19 18:23 UTC, X0-11 commented on code/modules/halo/machinery/gunvendors.dm
> +	products = list(
The BR fills a specific weapon niche, it's a marksman weapon that suffers from some dispersion, but less of an accuracy penalty when unscoped.

2022-08-19 18:24 UTC, X0-11 commented on code/modules/halo/weapons/MA37.dm
> +	burst = 4
Sounds good. Are the dispersion changes bringing them into baseline with the ma5b or are they different?

2022-08-19 18:25 UTC, X0-11 commented on code/modules/halo/weapons/shotguns.dm
> +	max_shells = 8//yeah yeah not lore friendly but balance and making innies a bit more different
Nah, it's fine.  It's either this or give it some other special ability to make up for the lost rounds.

2022-08-19 18:35 UTC, CapCamIII commented on code/modules/halo/weapons/MA37.dm
> +	burst = 4
Different, better dispersion than the MA5, makes it a side-grade overall with better dispersion and burst fire-rate, but significantly less fire rate

2022-08-19 18:35 UTC, CapCamIII commented on code/modules/halo/machinery/gunvendors.dm
> +	products = list(
i'll re-add it then.

2022-08-19 19:52 UTC, CapCamIII commented
@X0-11 Thats everything you brought up done, checks need re-running then good to go I believe.

2022-08-19 20:12 UTC, X0-11 requested changes

2022-08-19 20:12 UTC, X0-11 commented on code/modules/halo/weapons/shotguns.dm
> +	hud_bullet_row_num = 8//balance
You also need to change the max_shells, this is just the HUD number

2022-08-21 18:43 UTC, X0-11 approved these changes

2022-08-21 18:48 UTC, merged