Removes scope pop up menu, merges use-scope(sidearm) into use-scope.
HaloSpaceStation/HaloSpaceStation13 pull request #3208
Opened 2022-08-20 00:25 UTC by Joe44445

Changes scopes to check your active hand for a scoped weapon instead of a pop up menu (why would you want to scope with a weapon not in your active hand?), allowing for a far easier and less clunkier system to use. 

removes the use-scope(sidearm) verb, since all guns that use it will now use use-scope as there is no need for a verb to split the two anymore.

Removes all gun's scope verbs, instead grants the verb use-scope to any weapon with a zoom amount larger than 1.

:cl: Joe4444
rsctweak: tweaks the scope system to check active hand instead of giving you a pop up menu
rscdel: Removed use-scope(sidearm) verb. Any gun that used that will now use use-scope.
/:cl:

2022-08-20 06:54 UTC, X0-11 requested changes

2022-08-20 06:54 UTC, X0-11 commented on code/modules/projectiles/gun.dm
> +	set src = usr.contents
Is this needed?

2022-08-20 06:54 UTC, X0-11 commented on code/modules/halo/weapons/_guns.dm
> +		verbs += /obj/item/weapon/gun/proc/use_scope
When I saw your first draft, this is exactly what i was going to comment to tell you to do.

2022-08-20 15:13 UTC, Joe44445 commented on code/modules/projectiles/gun.dm
> +	set src = usr.contents
when I tried to test it without it before, it completely broke the scope command and i couldn't zoom in. Just tested it again locally though, and everything seems to work now without it, so i'll chalk that one up to some other change I made. I'll remove it now.

2022-08-21 18:43 UTC, X0-11 approved these changes

2022-08-21 18:48 UTC, merged