Prevents pod launch if destroyed
HaloSpaceStation/HaloSpaceStation13 pull request #3255
Opened 2023-01-07 21:16 UTC by OuterMostMonk

If a pods integrity isn't above zero it will be unable to launch until repaired

:cl: Outermonk
:tweak: Prevents pod launch if destroyed
/:cl:

2023-01-07 21:36 UTC, X0-11 commented
I was considering changing this after seeing it mentioned. I left this in on purpose because, frankly, destroying the pods is too easy for such an impact. I would rather something that allows launching but makes it dangerous. Burn damage to occupants, maybe?

2023-01-07 21:46 UTC, OuterMostMonk commented
I do think it is a bit too easy to destroy pods. But I also think being in a ship under heavy fire should be a deadly situation. I have noticed UNSC often spawn MAC ships to harass the Covenant cruiser and simply escape through the pods the moment superstructure fails. Umbilical's are still a viable escape option (if in range) and so is repairing a pod (if not under fire).

Not too well versed in the code, but I can take a look into applying an amount of damage instead if you want.

2023-01-07 21:49 UTC, X0-11 commented
Simulating an incredibly rocky escape via damage application to occupants would probably be best, yeah. You'll have to fiddle with the amounts to find some that don't instantly gib a limb though

2023-01-08 00:14 UTC, X0-11 approved these changes

2023-01-08 00:14 UTC, X0-11 commented on code/modules/halo/vehicles/types/drop_pod.dm
> +				dam_max /= 2
You're /2 like three times here, is that fully needed?

2023-01-08 00:15 UTC, X0-11 requested changes

2023-01-08 00:15 UTC, X0-11 commented on code/modules/halo/vehicles/types/drop_pod.dm
> +					l.adjustBruteLoss(dam_deal)
Subsection here's adding even more damage on? Isn't there a mob-proc for apply-damage?

2023-01-08 02:02 UTC, OuterMostMonk commented on code/modules/halo/vehicles/types/drop_pod.dm
> +				dam_max /= 2
This code is lifted from vehiclebase.dm that it procs on_death(), same for the issue below it is the same amount of random damage that occurs to people in a vehicle when it is destroyed right? If so maybe that needs tweaking as well?

I could follow the example in vehiclebase_air.dm instead for damaging occupants of a pilotless vehicle as it is more simple.

2023-01-08 20:57 UTC, X0-11 requested changes

2023-01-08 20:57 UTC, X0-11 commented on code/modules/halo/vehicles/types/drop_pod.dm
> +				dam_max /= 2
Ah, if it's being taken from elsewhere you can probably proc-ify the damage-dealing parts and re-use the proc here instead of copying the code verbatim.

2023-01-08 21:19 UTC, OuterMostMonk commented
It no longer is reusing the vehicle destruction damage code, which had all sorts of things going on and could also do incredibly large amounts of damage sometimes. A benefit of using apply_damage is I have made it do a little bit of burn damage as well as brute, due to failing protection in atmospheric entry and landing badly. There is still a chance you can die or lose a limb but it is slightly less likely.

If the copied code would be better though I can go back and turn the damage element into a proc as recommended.

2023-01-08 21:26 UTC, X0-11 commented
It's fine as-is, if you've modified it.

2023-01-08 21:26 UTC, X0-11 approved these changes

2023-01-09 00:58 UTC, merged