Stranded gamemode
HaloSpaceStation/HaloSpaceStation13 pull request #330
Opened 2017-11-07 09:43 UTC by caelaislinn

Todo:
- Changelog
- Job testing

Features:
- New "Stranded" gamemode. The players are UNSC survivors crash landed on an alien planet with waves of Flood coming in. Scavenge resources from around the map and build a base to hold them off, and watch out when night falls... survive until the pelican arrives on day 5
- Nighttime disabled due to lighting lag
- Pelican disabled
- Do not merge

2017-11-07 15:40 UTC, X0-11 requested changes

2017-11-07 15:40 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +		user.visible_message("<span class='warning'>There is [swarm_size] in the swarm.</span>")
I think you want to_chat(user,message) here. Visible_message shows a message to people around them too, I think

2017-11-07 15:40 UTC, X0-11 commented on code/modules/halo/gamemodes/stranded/turfs_areas.dm
> +			user.show_message("\red This area has already been dug")
to_chat(user,message) here too. I think travis dislikes the \red's, switch to standard "<span class = "...

2017-11-07 15:40 UTC, X0-11 commented on code/modules/halo/gamemodes/stranded/turfs_areas.dm
> +		user.show_message("\red You start digging.")
Here too

2017-11-07 15:40 UTC, X0-11 commented on code/modules/halo/gamemodes/stranded/turfs_areas.dm
> +		user.show_message("\blue You dug a hole.")
And here

2017-11-07 15:40 UTC, X0-11 commented on code/modules/materials/material_recipes.dm
> +	//recipes += new/datum/stack_recipe("[display_name] baseball bat", /obj/item/weapon/material/twohanded/baseballbat, 10, time = 20, one_per_turf = 0, on_floor = 1, supplied_material = "[name]")
I don't think this is the best way to do this. Making a new material with a slightly different name and custom recipes would be better.

2017-11-07 15:40 UTC, X0-11 commented on code/modules/halo/gamemodes/stranded/misc.dm
> +	user.show_message("It has [fuel_ticks_left] out of [max_fuel_ticks] units of fuel left ([100 * fuel_ticks_left/max_fuel_ticks]%).")
to_chat(user,message)

2017-11-07 15:40 UTC, X0-11 commented on code/modules/halo/gamemodes/stranded/flora.dm
> +		user.show_message("<span class='warning'>You need something sharp to chop down [src]</span>")
to_chat(user,message)

2017-11-07 15:40 UTC, X0-11 commented on code/modules/halo/flood/flood.dm
> +	src.show_message("<span class='danger'>[src] bursts, propelling flood spores in all directions!</span>")
to_chat(user,message)

2017-11-07 15:43 UTC, X0-11 commented on html/changelogs/cael_stranded.yml
> +  - wips: "Adds an experiement ambient lighting system (testing)"
Travis doesn't like this last one, I assume it's meant to be wip?

2017-11-07 15:45 UTC, X0-11 commented
It'd be better to have the entire stranded folder in /maps. Travis'll run some map-specific checks then.

2017-11-08 01:57 UTC, bloxgate commented on baystation12.dme
> -#include "code\datums\outfits\wizardry.dm"
😞 No more spawning in wizards in full gear to mess with people?

2017-11-08 02:06 UTC, bloxgate reviewed
I only really skimmed this, but I think @X0-11 got the majority of any problems there should be. Once those issues are fixed, I'll approve as well.

2017-11-08 02:06 UTC, bloxgate commented on code/game/machinery/floodlight.dm
> +		turn_on()
Are these supposed to both be on or should one be off?

2017-11-11 10:05 UTC, caelaislinn commented
Thanks for the pickups XO. I was pretty tired and didn't realise how many chat log muckups I made

2017-11-11 10:08 UTC, caelaislinn commented on code/modules/materials/material_recipes.dm
> +	//recipes += new/datum/stack_recipe("[display_name] baseball bat", /obj/item/weapon/material/twohanded/baseballbat, 10, time = 20, one_per_turf = 0, on_floor = 1, supplied_material = "[name]")
I want to cut out a lot of the bloat, particularly RP stuff like this

2017-11-11 10:10 UTC, X0-11 commented on code/modules/materials/material_recipes.dm
> +	//recipes += new/datum/stack_recipe("[display_name] baseball bat", /obj/item/weapon/material/twohanded/baseballbat, 10, time = 20, one_per_turf = 0, on_floor = 1, supplied_material = "[name]")
It'd be better to leave them commented then, just in case they're needed for future reference.

2017-11-11 11:49 UTC, X0-11 commented
How is this gamemode supposed to end? I don't see it using the built in check_finished proc to auto-end. Am I missing something?

2017-11-16 05:12 UTC, caelaislinn commented on code/game/machinery/floodlight.dm
> +		turn_on()
Yes. This is ran when the object is created and if on == 1 at that time then it activates the floodlight

2017-11-16 05:12 UTC, caelaislinn commented
I missed that too. Fixing that now

2017-11-16 06:36 UTC, caelaislinn commented
#289

2017-11-20 00:53 UTC, bloxgate commented
You have an unclosed <span> somewhere in flood.dm:
./code/modules/halo/flood/flood.dm

	<span> - Excess of 1 opening tag(s)

		Line 173

2017-11-24 07:05 UTC, bloxgate requested changes
It looks like something you've done recently has broken a lot of stuff on all the map tests. It appears that a lot of stuff now fails to create objects due to null locations, or other errors.

2017-11-30 07:39 UTC, X0-11 approved these changes
Three changes, but overall looks fine.

2017-11-30 07:39 UTC, X0-11 commented on code/modules/halo/flood/flood_npc.dm
> +/obj/effect/landmark/flood_spawn
Duplicate definition?

2017-11-30 07:39 UTC, X0-11 commented on code/modules/halo/gamemodes/stranded/evac_pelican.dm
> +		if(M.stat == CONSCIOUS)
!incapacitated() might be better here.

2017-11-30 07:39 UTC, X0-11 commented on code/modules/halo/gamemodes/stranded/structures.dm
> +	var/newdirname = input("Pick new direction for this barbed wire","New wire direction","North") in dir_options
Calling it barbed wire, not sandbags.

2017-12-02 19:43 UTC, merged