ONI Cargo Fixes and Reduction of Equipment in Vendors
HaloSpaceStation/HaloSpaceStation13 pull request #3326
Opened 2023-01-19 15:21 UTC by Aroliacue

:cl: Aroliacue
rscadd: Added new ONI category Restricted Goods with special purchaseables for research.
tweak: Fixed ONI Cargo not showing up.
tweak: Lowered counts of items in vendors to 30 from 50.
/:cl:

2023-01-19 15:31 UTC, X0-11 requested changes

2023-01-19 15:31 UTC, X0-11 commented on code/modules/halo/weapons/covenant/snipers.dm
> +	salvage_components = list(/obj/item/plasma_core)
the cov carbine doesnt use plasma

2023-01-19 15:31 UTC, X0-11 commented on code/modules/halo/weapons/covenant/snipers.dm
> +	salvage_components = list(/obj/item/plasma_core)
needlerifle doesnt use plasma

2023-01-19 15:31 UTC, X0-11 commented on code/modules/halo/weapons/covenant/pistols.dm
> +	salvage_components = list(/obj/item/plasma_core)
needler doesnt use plasma

2023-01-19 15:31 UTC, X0-11 commented on code/modules/halo/weapons/covenant/launchers.dm
> +	salvage_components = list(/obj/item/plasma_core = 3)
frc doesnt use plasma

2023-01-19 15:31 UTC, X0-11 commented on code/modules/halo/weapons/covenant/brute.dm
> +	salvage_components = list(/obj/item/plasma_core)
most brute weapons dont use plasma

2023-01-19 15:31 UTC, X0-11 commented on code/modules/halo/weapons/covenant/brute.dm
> +	salvage_components = list(/obj/item/plasma_core)
grenades probably shouldn't have plasma cores

2023-01-19 15:32 UTC, Aroliacue commented
What do they gain from deconstructing these weapons then?

2023-01-19 15:33 UTC, X0-11 commented
Something not currently implemented. Leave space open for further expansion.

2023-01-19 15:33 UTC, Aroliacue commented
No worries, updating soon

2023-01-19 15:41 UTC, Aroliacue commented
Reduced cargo income amounts and removed plasma cores from non-plasma weapons

2023-01-19 15:43 UTC, X0-11 approved these changes

2023-01-19 17:33 UTC, X0-11 commented on code/modules/halo/factions/player_factions.dm
> +	income = 600 //Higher than UNSC/ONI as they don't have an easy way to make money and also don't have purchases split
i dont think this quite makes up for the double income of 2x400 +supplementary from trading tbh. drop unsc / oni to like 100 and this makes a bit more sense. unsc/oni split doesnt mean much if they just extract the credits and deposit them in the other account

2023-01-19 17:33 UTC, X0-11 commented on code/modules/halo/factions/player_factions.dm
> +	income = 400
The URF probably deserve some sort of income, however minor.

2023-01-19 17:34 UTC, X0-11 commented on code/modules/halo/factions/player_factions.dm
> +	income = 600 //Higher than UNSC/ONI as they don't have an easy way to make money and also don't have purchases split
We could also make them more similar and give the covenant a set of traders for salvaged human equipment (you could make neural laces give a fair chunk of money too)

2023-01-20 00:09 UTC, merged

2023-01-20 00:15 UTC, Aroliacue commented on code/modules/halo/factions/player_factions.dm
> +	income = 600 //Higher than UNSC/ONI as they don't have an easy way to make money and also don't have purchases split
Covvies do have Kig-Yar traders in code, albeit I believe they only accept Covenant equipment and mined/farmed goods. There's a few legacy rooms on the CRS, such as the bow chapel/storage areas that I want to convert over into a new cargo setup, and it'd be easy to maybe stuff in a small botany bay and trader somewhere there (flavoured as specimens for agricultural support ships in the fleet?) I was asleep and missed this, I'll update the incomes on the second passover.