More insurrection fixes
HaloSpaceStation/HaloSpaceStation13 pull request #336
Opened 2017-11-16 08:04 UTC by X0-11

Hopefully fixes the nullspace bug this time.
Implememnts new weapon and magazine sprites.
Implements new ODST armour sprites.
Adds more information to the map's defines. No more "BAD Station"

Removes base bay species
Removes actors.
Removes respawning as mice
Hopefully stops people spawning with FBPs.

2017-11-16 08:32 UTC, BDpuffy420 commented
Many players feel the 180 seconds for the strike craft to be in effective range is not enough time for the innies to setup a proper defense, think we can add more time on the pods. The innies still lack their own secure comms, might also want add insurrectionist command role.

2017-11-16 12:15 UTC, X0-11 commented
It's very easy to change the amount of time it takes for the pods to become launch-able, any suggestions of the time to use?
Still working on getting innie-comms functioning, I think it may be due to the lack of a key combination that uses it. Command role would be easy to add, although I'm not sure what to give them to differentiate them from the usual insurrectionists.

2017-11-16 20:38 UTC, bloxgate requested changes

2017-11-16 20:38 UTC, bloxgate commented on code/modules/client/preference_setup/general/03_body.dm
> +		//	limb_selection_list -= "Full Body"
This will still allow prosthetic limbs by themselves right?

2017-11-16 20:38 UTC, bloxgate commented on code/modules/halo/comms/channel_keys.dm
> +	frequencies[innie_channel] = innie_freq
Not sure if it is actually a global, but perhaps it should be INNIE_CHANNEL to fit with the rest?

2017-11-16 20:38 UTC, bloxgate commented on code/modules/halo/misc/gunvendors.dm
> +					,/obj/item/weapon/gun/projectile/m6d_magnum = 5,/obj/item/weapon/gun/projectile/ma5b_ar =10,/obj/item/weapon/gun/projectile/br85 = 10
Fix the spacing on that second entry. It'll look nicer.

2017-11-16 20:38 UTC, bloxgate commented on code/modules/halo/weapons/ammo.dm
> +/obj/item/ammo_magazine/m762_ap/MA5B
This should have 60 rounds max. Looks like you didn't change that.

2017-11-16 20:38 UTC, bloxgate commented on code/modules/halo/weapons/rifles.dm
> +	desc = "Also formally know as the MA5."
known

2017-11-16 20:38 UTC, bloxgate commented on code/modules/mob/observer/ghost/ghost.dm
> +/*/mob/observer/ghost/verb/become_mouse()
Are mice really problematic as well?

2017-11-16 20:38 UTC, bloxgate commented on maps/insurrection/insurrection.dm
> +			modify_pod_launch(1)
What happened to the constants?

2017-11-16 20:39 UTC, X0-11 commented on maps/insurrection/insurrection.dm
> +			modify_pod_launch(1)
It's setting the timer to 1 second, which is then switched to 0 when process() is called

2017-11-16 20:40 UTC, X0-11 commented on code/modules/mob/observer/ghost/ghost.dm
> +/*/mob/observer/ghost/verb/become_mouse()
I dunno. I removed it because I remember someone saying that it was an issue.

2017-11-16 20:41 UTC, X0-11 commented on code/modules/halo/comms/channel_keys.dm
> +	frequencies[innie_channel] = innie_freq
Nah, it's not a global. Variable of the halo_frequencies datum.

2017-11-16 20:41 UTC, X0-11 commented on code/modules/client/preference_setup/general/03_body.dm
> +		//	limb_selection_list -= "Full Body"
Yep, should do.

2017-11-16 20:44 UTC, X0-11 commented on code/modules/halo/weapons/ammo.dm
> +/obj/item/ammo_magazine/m762_ap/MA5B
Original define of the magazine used 30 rounds. I assume 60 was slightly overpowered.

2017-11-16 20:47 UTC, bloxgate commented on code/modules/halo/weapons/ammo.dm
> +/obj/item/ammo_magazine/m762_ap/MA5B
The MA5B uses a 60 round magazine. You changed it from the 5D which has a 30 round magazine, to the 5B. People already get upset enough that we're not using a time period accurate weapon.

2017-11-16 20:48 UTC, X0-11 commented on code/modules/halo/weapons/ammo.dm
> +/obj/item/ammo_magazine/m762_ap/MA5B
Alright then. Hopefully this isn't a sacrifice to the balance gods.

2017-11-18 09:25 UTC, caelaislinn requested changes
Just wanted to clarify 1-2 points

2017-11-18 09:25 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +	qdel(src)
Why does this need a process tick?

2017-11-18 09:25 UTC, caelaislinn commented on code/modules/halo/comms/channel_keys.dm
> +	frequencies[innie_channel] = innie_freq
This was so the innie channel could have a randomised name

2017-11-18 09:25 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +	var/obj/armour_set = pick(list(/obj/effect/odst_armour_set/medic,/obj/effect/odst_armour_set/sharpshooter,/obj/effect/odst_armour_set/cqb,/obj/effect/odst_armour_set))
I'd prefer player armour kits aren't randomised except in specific circumstances eg looting wrecks, crashed ships etc. Just a design thought

2017-11-18 09:25 UTC, caelaislinn commented on code/modules/mob/observer/ghost/ghost.dm
> +/*/mob/observer/ghost/verb/become_mouse()
I was the one who added them like 5-6 years ago :(

2017-11-18 09:26 UTC, X0-11 commented on code/modules/halo/clothing/odst.dm
> +	qdel(src)
travis had a fit when I qdel'd it within New()

2017-11-18 09:27 UTC, X0-11 commented on code/modules/halo/clothing/odst.dm
> +	var/obj/armour_set = pick(list(/obj/effect/odst_armour_set/medic,/obj/effect/odst_armour_set/sharpshooter,/obj/effect/odst_armour_set/cqb,/obj/effect/odst_armour_set))
You can still spawn the armour kits on their own, this is just for the lockers in the ODST staging area.

2017-11-18 09:27 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +	qdel(src)
Do this instead
/obj/effect/random_ODST_set/Initialize()
	. = ..()
	return INITIALIZE_HINT_QDEL

2017-11-18 09:28 UTC, BDpuffy420 commented on code/modules/mob/observer/ghost/ghost.dm
> +/*/mob/observer/ghost/verb/become_mouse()
Mice weren't the issue, it was just the actors

2017-11-18 09:28 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +	var/obj/armour_set = pick(list(/obj/effect/odst_armour_set/medic,/obj/effect/odst_armour_set/sharpshooter,/obj/effect/odst_armour_set/cqb,/obj/effect/odst_armour_set))
In that case you should be using job lockers for the players instead of having randomised starting gear. That way players can choose their starting loadout, and they won't get frustrated if they have to tool around between different lockers to see what spawned. 

I'd give innies a randomised starting loadout though, because they're pretty close to space pirates/rebels/terrorists

2017-11-18 13:19 UTC, caelaislinn approved these changes

2017-11-20 23:12 UTC, bloxgate requested changes
Much better. Just one small thing I think we need to consider changing.

2017-11-20 23:12 UTC, bloxgate commented on code/modules/halo/weapons/covenant/rifles.dm
>  	slot_flags = SLOT_BACK
I'm fairly sure that the plasma rifle is capable of being held on a belt in lore. I don't think it would be too unbalanced to allow that.

2017-11-22 16:36 UTC, BDpuffy420 approved these changes
looks good to me

2017-11-22 16:49 UTC, merged