[DNM] Research changes + other fixes
HaloSpaceStation/HaloSpaceStation13 pull request #3375
Opened 2023-01-30 08:41 UTC by Aroliacue

:cl: Aroliacue
tweak: Changes research values
/:cl:

2023-02-09 02:54 UTC, BDpuffy420 commented
update?

2023-02-09 06:47 UTC, Aroliacue commented
Minor complication with work and personal time, might be a little while until I can commit. I'll comment again when I'm working on it

2023-05-11 00:35 UTC, Aroliacue commented
Ready for review

2023-05-11 07:56 UTC, X0-11 requested changes

2023-05-11 07:56 UTC, X0-11 commented on code/modules/halo/covenant/supply/covholyweapons.dm
> +	cost = 100
Make sure these ammo costs at least match unsc counterparts.

2023-05-11 12:55 UTC, Aroliacue commented on code/modules/halo/covenant/supply/covholyweapons.dm
> +	cost = 100
Costs reduced to be more in line with currently existing equivalents. Given the power of the Boltshot, I've put it at 75 instead of 50 (due to doubling as a shotgun)

2023-05-11 16:33 UTC, X0-11 approved these changes

2023-05-12 07:02 UTC, merged