Fixes plasma grenades
HaloSpaceStation/HaloSpaceStation13 pull request #3387
Opened 2023-02-11 12:37 UTC by OuterMostMonk

:cl: OuterMostMonk
tweak: Plasma grenades explode when thrown
tweak: Martyrdom grenades work again
/:cl:

Plasma grenades will now explode even if they do not embed in a target. Martyrdom grenades will also explode properly when dropped/thrown as intended.

2023-02-11 13:42 UTC, X0-11 commented
Oh, *that's* why they weren't activating. Thanks for catching this.

2023-02-11 13:43 UTC, X0-11 requested changes

2023-02-11 13:43 UTC, X0-11 commented on code/modules/halo/weapons/covenant/grenades.dm
> +	start_timer()
This should probably go through the usual checks throw impact does before starting the timer.

2023-02-11 17:57 UTC, OuterMostMonk commented
Yeah that start_timer() was placed funny (exploding inactivated grenades when thrown), now it should work fine. Can't place it after the checks later as that would cause it to only explode if it hits a person.

2023-02-16 19:48 UTC, X0-11 approved these changes

2023-02-16 19:49 UTC, merged