KS7 Marshal Overhaul Update
HaloSpaceStation/HaloSpaceStation13 pull request #3426
Opened 2023-07-31 21:43 UTC by YourPalHolidays

:cl: YourPalHolidays(Tsar)
rscadd: Added new Marshal gear and custom sprites. (Original credit goes to Eluxor)
rscadd: Overhauls KS7's police department.
tweak: Fixes the GCPD slowdown gear bug.
/:cl:

2023-08-01 02:31 UTC, Aroliacue approved these changes
I love this. Sprites look smooth!

2023-08-02 09:13 UTC, X0-11 requested changes
can you please also put some description of the changes to the PD

2023-08-02 09:13 UTC, X0-11 commented on .gitignore
> +baystation12.dme
why has this been changed

2023-08-02 09:13 UTC, X0-11 commented on baystation12.dme
> +#include "maps\ks7_elmsville\includes.dm"
this should not have been PR'd

2023-08-02 09:14 UTC, X0-11 commented on baystation12.dme
> +#include "maps\faction_bases\civ_shuttle.dm"
nor should have this been PR'd

2023-08-02 09:42 UTC, YourPalHolidays reviewed
This update overhauls the KS7 Marshals with new equipment, gear and apparel, as well as changes to their PD including a left that leads to a underground garage, several QoL rooms, a mayors office on the second floor along with a expanded armory and other various facilities to promote a more enjoyable experience for KS7 Colonial Marshal players.

2023-08-02 09:42 UTC, YourPalHolidays commented on .gitignore
> +baystation12.dme
Kerfuffle with inclusion and a ignore githhub that I must have did wrong, there should be no changes to the indicated files, if there is then something is wrong on my end.

2023-08-02 09:42 UTC, YourPalHolidays commented on baystation12.dme
> +#include "maps\faction_bases\civ_shuttle.dm"
Gitignore moment.

2023-08-02 09:42 UTC, YourPalHolidays commented on baystation12.dme
> +#include "maps\ks7_elmsville\includes.dm"
Gitignore moment 2.0.

2023-08-02 09:58 UTC, X0-11 commented on .gitignore
> +baystation12.dme
there are changes, that's what github tracks

2023-08-02 11:40 UTC, YourPalHolidays commented on .gitignore
> +baystation12.dme
If that is the case then I will cancel this merge request, I have not knowingly modified those files in any way and look into my own fork to see why those files have been changed.

2023-08-02 19:34 UTC, closed without merging