KS7 Marshal + Hospital update + KS7 Area Icon update
HaloSpaceStation/HaloSpaceStation13 pull request #3461
Opened 2023-08-11 14:30 UTC by Teragenic

- Adds Chief Marshal armor and Medic armor variants. Chief Marshall armor is on-par with the heavy armor, except in melee.
- Adds Chief Marshal Badge. Literally serves no purpose other than different name.
- Adds some area icons for KS7
- Gives Mayor the proper headset.
- Adds Hud icons to Marshal, Mayor, Pharmacist, Hospital Worker, and Aerodome tech.
- Adds new locker instead of the baseline SS13 HoS Locker.
- Gives Hospital Worker and Pharmacist pharmacy and hospital access respectively.

2023-08-11 14:31 UTC, Teragenic commented
I forgot to put a comma. Feck. There fixed.

2023-08-11 14:32 UTC, Teragenic commented
![image](https://github.com/HaloSpaceStation/HaloSpaceStation13/assets/67575979/bc4b8f5d-6030-44f8-a2d2-44023b29613c)
Proof of no crashes :D

2023-08-11 14:34 UTC, Teragenic commented
FIX

2023-08-11 14:40 UTC, Aroliacue approved these changes

2023-08-11 14:40 UTC, Aroliacue commented on baystation12.dme
> +#include "maps\ks7_elmsville\includes_pvp.dm"
Make sure not to include any mapfile #include definitions, as this can break the server.

2023-08-11 14:40 UTC, Aroliacue commented on code/modules/halo/clothing/marshal.dm
> +	desc = "A fully enclosed Marshal helmet with inbuilt tear gas filters designed to protect the entirety of the head from ballistics and shrapnel. This one ."
Missing a bit of its description, don't forget to add one!

2023-08-11 14:40 UTC, Aroliacue commented on code/modules/halo/clothing/marshal.dm
> +	armor_thickness = 20
Bump this up to 25 thickness to be actually on-par with the heavy vest.

2023-08-11 14:48 UTC, X0-11 requested changes, later dismissed

2023-08-11 14:48 UTC, X0-11 commented on code/modules/halo/clothing/marshal.dm
> +	armor = list(melee = 50, bullet = 55, laser = 55, energy = 45, bomb = 50, bio = 25, rad = 25) // On-par protection with the heavy vest without the drawback.
armour values shouldn't change from the baseline whilst also tweaking armour thickness, pick one to tweak, ideally thickness

2023-08-11 14:52 UTC, Aroliacue commented on code/modules/halo/clothing/marshal.dm
> +	armor = list(melee = 50, bullet = 55, laser = 55, energy = 45, bomb = 50, bio = 25, rad = 25) // On-par protection with the heavy vest without the drawback.
The armor this is inheriting from already had 25 thickness, he had reduced the thickness but increased the armor which wasn't intentional

2023-08-13 01:46 UTC, Aroliacue approved these changes

2023-08-13 01:56 UTC, merged