Gravity hammer balance and ODST call in fix
HaloSpaceStation/HaloSpaceStation13 pull request #3541
Opened 2024-02-18 05:04 UTC by OuterMostMonk

Attempts to make the powered gravity hammer useable but not too strong. Also fixes ODSTs having more than just personalised call ins.
Hopefully could lead to Chieftain being enabled in the future whether as an alternative to shipmaster or as an extra.

:cl: OuterMonk
tweak: Powered gravity hammer no longer spammable, hunters immune to its knockback.
tweak: Non-officer ODSTs get personalised call downs only
/:cl:

2024-02-18 22:36 UTC, X0-11 requested changes

2024-02-18 22:36 UTC, X0-11 commented on code/modules/halo/weapons/covenant/brute.dm
> +	if(istype(A, /atom/movable) && !istype(A, /obj/machinery/door) && !istype(A, /mob/living/simple_animal/mgalekgolo)) //No instant door breaking or bullying poor hunters
This could probably just be narrowed down to only shift /mob/living and /obj/item/

2024-02-18 22:37 UTC, X0-11 requested changes, later dismissed

2024-02-18 22:37 UTC, X0-11 commented on code/modules/halo/weapons/covenant/brute.dm
> +	if((world.time-timer)>29) // To avoid spamming non direct hits
Use a define instead of a magic number like this.

2024-02-18 22:37 UTC, X0-11 commented on code/modules/halo/weapons/covenant/brute.dm
> +		timer = world.time + 30
The define can be used here too.

2024-02-18 23:50 UTC, OuterMostMonk commented
Changes made, should be better now (I hope). I kept hunters immune with the narrowing down of targets but wonder if complete immunity is too much. Maybe I should allow them to be moved by the ground attack which has a cooldown but not direct attacks?

2024-02-19 13:09 UTC, X0-11 commented
I think keeping hunters immune is fine as-is, although you may want to check through the code and see if there's some internal size tracking for simplemobs that you can check against rather than specifically targeting hunters, as flood juggernauts should also probably be immune.

2024-02-20 00:26 UTC, OuterMostMonk commented
Large size mobs are now immune to gravity hammer knockback. Not sure what other mobs count as large but I imagine for halo mobs it is just juggernaut and hunter.

2024-02-23 22:13 UTC, BDpuffy420 approved these changes

2024-02-23 22:25 UTC, merged