[DNM] Adds Stranded resupply drops
HaloSpaceStation/HaloSpaceStation13 pull request #364
Opened 2017-12-11 11:22 UTC by caelaislinn

See commit log for more info

2017-12-11 13:49 UTC, X0-11 commented on maps/desert_outpost/gamemode/mode_stranded.dm
> +	var/turf/center_turf = locate(world.maxx / 2, world.maxy / 2, 1)
Wouldn't it be better to utilise a landmark to set the centre of the resupply exclusion zone? This currently restricts the zone to the middle of the map.

2017-12-11 13:51 UTC, X0-11 commented on maps/desert_outpost/gamemode/mode_stranded_resupply.dm
> +		var/close_range = 14
The usual Playsound proc might be better here. I don't think explosioncode is really necessary.

2017-12-11 21:27 UTC, caelaislinn commented on maps/desert_outpost/gamemode/mode_stranded.dm
> +	var/turf/center_turf = locate(world.maxx / 2, world.maxy / 2, 1)
No it excludes the middle of the map (I tested it). You're right a landmark would be better though, because this assumes that the player base is always in the middle of the map. I'll set up some stranded specific unit tests to check for it

2017-12-11 21:29 UTC, X0-11 commented on maps/desert_outpost/gamemode/mode_stranded.dm
> +	var/turf/center_turf = locate(world.maxx / 2, world.maxy / 2, 1)
Ah, That's what I meant at the time. Would substituting the locate() with a locate([typepath_to_landmark]) would provide the same effect?

2017-12-11 21:31 UTC, caelaislinn commented on maps/desert_outpost/gamemode/mode_stranded.dm
> +	var/turf/center_turf = locate(world.maxx / 2, world.maxy / 2, 1)
var/mytypepath/M = locate() in world will grab the first instance it finds

2017-12-20 05:42 UTC, bloxgate commented
You seem to have modified some globals. You'll need to run the script to update those and get the new checksum for tests.

2017-12-22 09:18 UTC, caelaislinn commented
I've actually been updating the globals checksum manually lol. I'll do my travis fixes when the features are ready to merge

2017-12-22 17:09 UTC, bloxgate commented
You really should use the script. I'm fairly sure using it touches some code files as well, like global_access that needs to be changed if globals are changed as well.

2017-12-25 22:31 UTC, X0-11 requested changes

2017-12-25 22:31 UTC, X0-11 commented on code/modules/halo/flood/flood_spawn_bio.dm
> +	world << "[src] [src.type] Bump()'d by [AM] [AM.type]"
Left a world << here.

2017-12-25 22:31 UTC, X0-11 commented on maps/desert_outpost/gamemode/mode_stranded_daynight.dm
> +		world << "Calling apply_lum()..."
world <<

2017-12-26 09:31 UTC, X0-11 approved these changes

2017-12-26 18:59 UTC, BDpuffy420 approved these changes
LGTM

2017-12-27 15:51 UTC, merged