Vehicle Overhaul + Dropship Overhaul
HaloSpaceStation/HaloSpaceStation13 pull request #427
Opened 2018-01-25 16:29 UTC by X0-11

Overhauls the movement system to make vehicle movement slide to a stop if it has accumulated enough momentum beforehand.

Integrates the dropship landing system with the vehicle system, allowing players to fly pelicans etc around the map and choose where they want to land. This also includes nose-guns for UNSC and insurrection pelicans.

Air vehicles required the implementation of an elevation system, which allows players to walk underneath elevated objects, and allows elevated objects to move over un-elevated objects. A change to projectile movement has also been made to allow them to traverse elevations.

2018-01-25 21:57 UTC, BDpuffy420 approved these changes
Nothing out of the ordinary, looks good to me!

2018-01-28 08:42 UTC, caelaislinn requested changes
There's no way to transform an overmap dropship to an air dropship, it might be good to add a mechanism to do that.

2018-01-28 08:42 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase.dm
> +				new_y -= 1
This could be tweaked so that automatic decelleration actually changes the flight speed.

2018-01-28 08:42 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase.dm
Somewhere in this file you need to add an override for proc/return_air_for_internal_lifeform() so that occupants of the vehicle can breath from internal air. Also add a var/datum/gas_mixture/internal_air of some sort. Eventually we'll need a way to replenish that air, and it can probably be paired with a method of refuelling/consuming fuel, replenishing ammo etc.

2018-01-28 08:43 UTC, caelaislinn commented
I haven't tested vehicle damage yet, I can't do that solo. We'll need to tee up a time for 2 of us to do that.

2018-01-28 08:44 UTC, X0-11 commented
Vehicle damage functions the same as mongeese, there's just a higher lower bound for damage to start hurting the pelican.

2018-01-28 08:45 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase.dm
> +				new_y -= 1
I've tried multiple ways to do that, but the few I've tried lost the slide-to-a-stop effect I had wanted.

2018-01-28 08:46 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase.dm
I think this would be better handled by a subtype /space when required later down the line. Code already exists for fuel consumption/refuelling.

2018-01-28 08:47 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase.dm
> +				new_y -= 1
At the moment it just keeps going for a few seconds then halts, it feels a bit unnatural. I'll test some things and see if I can come up with a recommendation

2018-01-28 10:50 UTC, caelaislinn commented
There is some stuff to do with collision checks and elevation which will complicate it.

2018-01-28 10:51 UTC, X0-11 commented
Personal testing has shown that it still functions. I had to modify projectile-trajectory code to deal with elevation.

2018-01-28 11:24 UTC, caelaislinn commented on code/modules/halo/vehicles/vehiclebase.dm
> +		add_momentum(0,-inertia)
Have you tried changing this to inertia/10 or inertia/5 ? how did that look?

2018-01-28 11:24 UTC, X0-11 commented on code/modules/halo/vehicles/vehiclebase.dm
> +		add_momentum(0,-inertia)
I haven't tried that, but lowering the intertia itself would have the same effect.

2018-01-28 14:40 UTC, merged