Gem city / Innie Base changes and additions
HaloSpaceStation/HaloSpaceStation13 pull request #624
Opened 2018-05-29 21:31 UTC by lngredients

Gem City- Added tons of door names for shops and official buildings
Innie Base 3- Added sink to Surgery Room 
Innie Base 2- Increased magazine count in innie armory. Most guns only had two to three magazines per weapon which is far too low. Increased to Four or five mags per gun.
Innie Base 3- Added four stock assault rifles into weapons crate in storage. Added 10 magazines for them in weapons crate below it.
Innie Base 3- Added 5 Vintage .45 pistols with one clip extra each into a weapons box in storage.
Innie Base 2- Added 5 Normal revolvers and 5 speed loader clips into a weapons crate in north storage.
Innie Base 2- Added in two extra grenades in the armory.
Innie Base 2- Added in 6 spare grenades in northern storage into a weapons crate.
Innie Base 2- Added in ten handcuffs into a secure crate in northern storage.
Innie Base 2- Added in five silencers into the eastern storage in a secure crate.
Innie Base 2- Added in three welding packs into the eastern storage in a secure crate.
Innie Base 4- Added in a sink to medical bay.
Innie Base 2- Added in 6 bear traps to eastern storage.
Innie Base 3- Added in four voice analyzers into engineering so that bombs can be made to be triggered by key words.
Innie Base 2- Added in five camers with one spare film each into normal crate in north storage. Can be used for RP purposes or recon.
Innie Base 2- Added in two sets of random clothes for each large crate in eastern storage so Innies can go incognito if they want from the start.
Innie Base 2- Added in a set of random clothes into top right office.
Innie Base 3- Added in a Four sets of random clothes into the laundry room.
Innie Base 3- Added in some metal barrels into the Hangar bay for aesthetics.

2018-05-29 21:33 UTC, caelaislinn commented
There's a lot of changes here. To minimise maplocks or merge conflicts, you should split up the changes into multiple PRs

2018-05-29 21:34 UTC, lngredients commented
So one PR per map?

2018-05-29 21:36 UTC, caelaislinn requested changes
Remove DME changes, resolve map conflicts, split maps across separate PRs

2018-05-29 21:36 UTC, caelaislinn commented on baystation12.dme
> +#include "maps\geminus_city\geminus_city_spawns.dm"
Revert these DME changes, they will muck with the map settings

2018-05-29 21:37 UTC, lngredients commented on baystation12.dme
> +#include "maps\geminus_city\geminus_city_spawns.dm"
Alright, I keep getting conflicting info about those two DMEs whether to leave them on or off.

2018-05-29 21:54 UTC, lngredients commented
So I removed the DME's and reverted the largest Commit.

2018-05-29 21:56 UTC, lngredients commented
Hmm... I'll have to see why it's still conflicting.

2018-05-29 22:10 UTC, lngredients commented
Hmm.. How do I section off each map into it's own PR?

2018-05-29 22:11 UTC, lngredients commented
They seem to be stuck together in this last commit.

2018-05-29 22:28 UTC, lngredients commented
Alright, I think I understand how this is working now. Check it for cancer please.

2018-05-30 01:23 UTC, DoctorOctopusTheOctopi requested changes

2018-05-30 01:23 UTC, DoctorOctopusTheOctopi commented on baystation12.dme
> +=======
Uncheck these from the DME, they do not need to be checked.

2018-05-30 01:23 UTC, DoctorOctopusTheOctopi commented on baystation12.dme
> +>>>>>>> parent of db506a959c... Added Door names To all the important doors.
I have no clue what this is.

2018-05-30 01:29 UTC, DoctorOctopusTheOctopi commented
Conflicts have been resolved, Travis check now needs to pass.

https://travis-ci.org/HaloSpaceStation/HaloSpaceStation13/builds/385425995?utm_source=github_status&utm_medium=notification

2018-05-30 03:42 UTC, DoctorOctopusTheOctopi commented
Error log can be found below, area's of importance circled.

[Error Log](https://gyazo.com/ee4abd2d797a3533097a313bab61e95b)

2018-05-30 06:15 UTC, lngredients commented
What is a left hand argument?

2018-05-30 06:16 UTC, lngredients commented on baystation12.dme
> +>>>>>>> parent of db506a959c... Added Door names To all the important doors.
Just adding Names to Doors for official buildings and shops

2018-05-30 11:45 UTC, caelaislinn commented on baystation12.dme
> +>>>>>>> parent of db506a959c... Added Door names To all the important doors.
That's merge conflict indicators. They've been manually inserted by git to show that there was a conflict with those files, and they're automatically removed when the merge is safely resolved. Because they're still there it means the file conflict wasn't properly resolved.

2018-05-30 11:49 UTC, caelaislinn commented
The left hand argument in there refers to the << operator not having an argument to its left... it doesn't mean anything because the <<<<<<<<< was inserted by git to show a conflict is present there and because the symbols are still there means the conflict wasn't resolved. 

At this stage you may find it easier to copy your changes, reset your repo then manually reapply your changes.

2018-05-30 18:08 UTC, closed without merging