Theta Project Changes v1.2
HaloSpaceStation/HaloSpaceStation13 pull request #627
Opened 2018-05-30 22:59 UTC by lngredients

Changed Theta Project Armor to a cooler looking armor set.
Theta armor should be capable of holding most weapons in its suit slot.
Gave the theta project closet a bullpup rifle and three mags to equip their creation, or be killed by it.
The armor gives a slight boost to walk speed.
Helmet light is twice as strong as a normal helmet light so you can actually see in the dark.
Theta Undersuit was replaced and now will actually work.
Slightly Changed Theta Project equipment names so they arn't so long.
Decreased armor on boots and gloves because the full body suit is strong enough.

2018-05-30 23:47 UTC, lngredients commented
Octopus it looks to me like the alpha locker and freezer are conflicting for some reason I don't understand.

2018-05-31 00:56 UTC, lngredients commented
I have no idea what is wrong. It CI says it's missing HUD elements and other things like that which I didn't mess with.

2018-05-31 23:35 UTC, lngredients commented
Does anyone know what I can do to make this playable?

2018-06-01 02:57 UTC, bloxgate requested changes

2018-06-01 02:57 UTC, bloxgate commented on baystation12.dme
> +#include "maps\geminus_city\geminus_city_jobs.dm"
This here is likely the problem. You seem to be including some of the map, but not all the files that are required for it to work. If you're trying to change the map to geminus, you'll need to include maps\geminus_city\geminus_city.dm

2018-06-01 12:23 UTC, lngredients commented
So adding in the requested DM  maps\geminus_city\geminus_city.dm, and I am still receiving the same errors as before it was included. 

This is the CI information the geminus-city.dm included.
https://travis-ci.org/HaloSpaceStation/HaloSpaceStation13/builds/386630838

I added in the geminuscity_2.dmm to test and see results. I will link that CI build below.
https://travis-ci.org/HaloSpaceStation/HaloSpaceStation13/builds/386635391

2018-06-06 01:59 UTC, closed without merging