Colony mode expansion
HaloSpaceStation/HaloSpaceStation13 pull request #629
Opened 2018-05-31 12:26 UTC by BDpuffy420

Added some QOL fixes to the map by adding more overmap locations and mkaing the general overmap bigger. Also added more shipnames to the NPC list.

2018-05-31 15:17 UTC, BDpuffy420 commented
I am at a lost with this error.

2018-05-31 15:20 UTC, DoctorOctopusTheOctopi submitted a review, later dismissed

2018-05-31 15:20 UTC, DoctorOctopusTheOctopi commented on baystation12.dme
> +#include "maps\odst_prowler\ODST_Ship.dmm"
Uncheck this.

2018-05-31 20:55 UTC, bloxgate commented
I'm not entirely sure what you did, but I think you jumbled something up with the #includes in the DME. Perhaps taking a look there?

2018-05-31 20:58 UTC, BDpuffy420 commented
More than likely I did.

2018-06-01 03:00 UTC, bloxgate commented
So, for the hud icons it would appear that you're trying to include some of the roles and jobs for the frigate even though that map isn't being used.

2018-06-01 05:00 UTC, DoctorOctopusTheOctopi reviewed
Why have all of these files been checked to include? That's most likely the reason why stuffs throwing an error. Refer to pink dots on screenshot.

https://gyazo.com/e93ad0d00a1b2496b792ed0c7467690b

2018-06-01 05:00 UTC, DoctorOctopusTheOctopi commented on baystation12.dme
> +#include "maps\Exoplanet Research\overmap.dm"
File referenced in screenshot.

2018-06-02 22:52 UTC, DoctorOctopusTheOctopi commented on baystation12.dme
> -#include "maps\civ_hauler\ship_cap_ghost_role.dm"
Needs to be added back in.

2018-06-02 22:55 UTC, DoctorOctopusTheOctopi requested changes
It also appears you have some incoherent areas. 
Both are classified as 
"KS7-535 Wilderness (/area/exo_Ice_facility/outer)"

One here (1,1,5)
and
One here (43,53,5)

2018-06-02 22:55 UTC, DoctorOctopusTheOctopi commented on baystation12.dme
> +#include "maps\Exoplanet Icy\spawns_jobs.dm"
Areas, Overmap, and Spawn_jobs, can be unchecked.

2018-06-02 22:55 UTC, DoctorOctopusTheOctopi commented on baystation12.dme
> +#include "maps\Exoplanet Icy\KS7535_2.dmm"
Uncheck these two, the include will assist.

2018-06-03 17:25 UTC, DoctorOctopusTheOctopi requested changes
After this everything should be good.

2018-06-03 17:25 UTC, DoctorOctopusTheOctopi commented on baystation12.dme
> -#include "code\modules\client\preference_setup\loadout\loadout_head.dm"
You've unchecked the loadout for eyeglasses and hats. May want to re-check that.

2018-06-03 17:25 UTC, DoctorOctopusTheOctopi commented on maps/Exoplanet Mining/spawns_jobs.dm
> +	restrict_job = list("Outer Colomist")
Colomist

2018-06-03 17:43 UTC, BDpuffy420 commented on maps/Exoplanet Mining/spawns_jobs.dm
> +	restrict_job = list("Outer Colomist")
Rip I thought I fixed that.

2018-06-03 18:21 UTC, DoctorOctopusTheOctopi approved these changes

2018-06-03 18:22 UTC, DoctorOctopusTheOctopi commented
Pending any Travis complaints and a changelog which can be [ci skip]ed this PR should be good to go.

2018-06-04 08:32 UTC, caelaislinn submitted a review, later dismissed
What is in the file "code/modules/halo/icons/32x64 - Copy.dmi"

2018-06-04 08:32 UTC, caelaislinn commented on baystation12.dme
> +#include "maps\unsc_frigate\jobs\unsc_jobs_includes.dm"
Did you intend to make these DME changes?

2018-06-04 08:32 UTC, caelaislinn commented on baystation12.dme
> -#include "maps\civ_hauler\ship_cap_ghost_role.dm"
Why has this been commented out?

2018-06-04 08:32 UTC, caelaislinn commented on baystation12.dme
> -#include "maps\first_contact\mapdef.dm"
Why are these changed? We should be keeping Geminus city as the default because it's good for extended rounds

2018-06-04 08:32 UTC, caelaislinn commented on code/modules/halo/overmap/npc_ships.dm
> +"Pete's Cube","The Nomad","The Alexander","Free Range","Bigger Stick","Fist of Sol","Hammerhead","Spirit of Jupiter","Trident","The Messenger","Slow But Steady","Road Less Travelled","Dawson's Christ
Are you able to make this into a config option which loads from a text file? I can help out on discord

2018-06-04 08:37 UTC, BDpuffy420 commented on code/modules/halo/overmap/npc_ships.dm
> +"Pete's Cube","The Nomad","The Alexander","Free Range","Bigger Stick","Fist of Sol","Hammerhead","Spirit of Jupiter","Trident","The Messenger","Slow But Steady","Road Less Travelled","Dawson's Christ
Not sure how to go about that.

2018-06-04 08:39 UTC, BDpuffy420 commented on baystation12.dme
> -#include "maps\first_contact\mapdef.dm"
Those are used in the FC mode, this PR is to add the maps and such from FC to GC

2018-06-04 08:39 UTC, BDpuffy420 commented on baystation12.dme
> -#include "maps\civ_hauler\ship_cap_ghost_role.dm"
I was getting errors from and and XO had a PR I believe that disable it.

2018-06-04 08:41 UTC, BDpuffy420 commented
And "code/modules/halo/icons/32x64 - Copy.dmi is the other version for the covenant glassing weapon.

2018-06-04 08:42 UTC, caelaislinn commented
Those files need proper names. Can you update them?

2018-06-04 08:42 UTC, BDpuffy420 commented
Will do

2018-06-04 08:56 UTC, caelaislinn commented on code/modules/halo/overmap/npc_ships.dm
> +"Pete's Cube","The Nomad","The Alexander","Free Range","Bigger Stick","Fist of Sol","Hammerhead","Spirit of Jupiter","Trident","The Messenger","Slow But Steady","Road Less Travelled","Dawson's Christ
Actually scrap that idea... all the random name options for other stuff is hardcoded so by doing it this way we keep to bay12 conventions. For your reference though if you are interested go to code\world.dm line 564 and it will show you a fairly simple proc you can copy

2018-06-04 18:52 UTC, merged