"Hotfix" for vessel problems+ minor additions.
HaloSpaceStation/HaloSpaceStation13 pull request #653
Opened 2018-06-07 14:41 UTC by Flaksim

- maptweak: "Added an elevator between deck 2 and MAC controls on the frigate."
  - maptweak: "Added a "supraluminal communications array" (fax) to the Kig-Yar bridge."
  - bugfix: "Fixed deck gun and archer gun controls on the frigate."
  - bugfix: "Fixed Kig-Yar vessel engines and connector port for refueling."
  - experiment: "Changed Sangheili language colour to "vox" entry."

2018-06-07 19:23 UTC, bloxgate requested changes
Changelog has issues

2018-06-07 19:23 UTC, bloxgate commented on html/changelogs/Flaksim Update 8 june.yml
> +  - maptweak: "Added a "supraluminal communications array" (fax) to the Kig-Yar bridge."
Replace
```"Added a "supraluminal communications array" (fax) to the Kig-Yar bridge."```
With ```"Added a \"supraluminal communications array\" (fax) to the Kig-Yar bridge."

2018-06-07 19:23 UTC, bloxgate commented on html/changelogs/Flaksim Update 8 june.yml
> +  - experiment: "Changed Sangheili language colour to "vox" entry."
Replace ```"Changed Sangheili language colour to "vox" entry."``` with ```"Changed Sangheili language colour to \"vox\" entry."```

2018-06-07 22:11 UTC, bloxgate approved these changes
Code changes look good. Those that touch things in map still need to be tested in a local environment by another reviewer though.

2018-06-07 23:46 UTC, Flaksim commented
So who is going to local test the maps? I did a comprehensive test for a change though, let the kig-yar ship fly for 30 minutes then checked if it still had working engines and refueling, opened and closed the shutter I added, and tested if the new elevator worked.

2018-06-08 00:01 UTC, Desolane approved these changes
Code looks fine.

2018-06-08 00:11 UTC, merged