Theta project upgrades - Theta race and Gun changes
HaloSpaceStation/HaloSpaceStation13 pull request #664
Opened 2018-06-10 23:54 UTC by lngredients

Added in Txt files for Theta First and Last Names
In Names.dm added GLobal list INit for txt files
Added in code to Theta.dm to hopefully create a new race called Theta Subject
Removed Code to deflect bullets as it wasn't working.
Added a modded Icon, MA9 gun into Weapon sprites.dm, changed the Theta Project Icon to use the MA9.
Added in code for all Theta Armor to species restrict to Theta Species.

2018-06-10 23:58 UTC, lngredients commented
Hmm.. Why are these two files conflicting? All i did was add a new sprite to the .dmi and a bit of code to the Theta Project.

2018-06-11 02:11 UTC, lngredients commented
This should be good to go.

2018-06-11 02:50 UTC, lngredients commented
Review when possible please.

2018-06-11 05:05 UTC, caelaislinn requested changes
Also what's the rationale for making Theta a race?

2018-06-11 05:05 UTC, caelaislinn commented on config/names/last_theta.txt
> +199
This should be done in code if these are the names

2018-06-11 05:05 UTC, caelaislinn commented on config/names/first_theta.txt
> +Theta
If there's only one name, why are you loading from file?

2018-06-11 05:05 UTC, caelaislinn commented on html/changelogs/mk5 armour.yml
> +  - imageadd: "Adds Mark V Mjolnir Armour and several variants."
You shouldn't be touching other changelog entries, it's mostly handled by scripts

2018-06-11 08:32 UTC, lngredients commented on config/names/first_theta.txt
> +Theta
So it will take the first name Theta, and then choose a random number to put after it.

2018-06-11 08:32 UTC, lngredients commented on html/changelogs/mk5 armour.yml
> +  - imageadd: "Adds Mark V Mjolnir Armour and several variants."
I didn't? What Changelog is this?

2018-06-11 08:36 UTC, lngredients commented on html/changelogs/mk5 armour.yml
> +  - imageadd: "Adds Mark V Mjolnir Armour and several variants."
I didn't realize this was added in with my PR, it might be from when I merged from alpha.

2018-06-11 08:36 UTC, lngredients commented on config/names/last_theta.txt
> +199
How do I do this in code then, I thought I was? I added in code to draw from this list. I was mimicing the Spartan name setup process.

2018-06-11 08:37 UTC, Desolane commented
This isn't getting merged. This lore breaking project to make yourself OP isn't getting put in.

2018-06-11 08:37 UTC, closed without merging

2018-06-11 08:39 UTC, lngredients commented
Tonight was literally the firs time I've been Theta since I've created my first PR... It's not to make myself OP...

2018-06-11 08:40 UTC, lngredients commented
Also this PR doesn't add anything to empower the theta project... just icon changes and species restriction.

2018-06-11 08:44 UTC, bloxgate commented
I'm afraid I'm going to have to say this won't be getting reopened. The staff have had a discussion on this, and decided that Theta is not something we would like to have after all the issues it has caused so far and the blatant canon violations.

We're not opposed to stretching or reasonably adding to canon; until some serious conversation and balance tweaks are done, Theta is going to be cut due to the sheer amount of constant salt it generates.

2018-06-11 09:21 UTC, lngredients commented
Is the Theta Project actually a cannon thing? I was under the impression is was a fictional addition to the server to add some flavor in the first place.

2018-06-11 20:24 UTC, caelaislinn commented on config/names/first_theta.txt
> +Theta
You can do it in one line of code ie name= "Theta [rand(1,199)]"