Project Orion
HaloSpaceStation/HaloSpaceStation13 pull request #679
Opened 2018-06-16 01:29 UTC by lngredients

Added in new surgery room at Exoresearch for Project Orion. Changed Theta project names to Project Orion for guns and armor.

Armor thickness is now only on helmet and armor pieces. Undersuit no longer provides armor values. All armor values were decreased so that max is 65 on main armor piece only for limbs.

Added in Orion Project Race called "Orion" which Admins will have to manually set once proper RP is done ICly to create project Orion. Added in armor race restrictions so it can only be worn once race is set.

Changed Theta Project .DM file name to Orion Project. Changed Project Theta evelope to reflect Project Orion's needs.

Removed the RD closet containing the Theta Project Envelope. Replaced Blank Envelopes in Exo-Research 1 with Project Orion Envelopes

Changed MA3 custom gun to custom MA9 icon.

2018-06-16 01:32 UTC, lngredients commented
If this Clears the CI I'd appreciate a review by someone to see what they think about it.

2018-06-16 01:32 UTC, DoctorOctopusTheOctopi commented
@Desolane our Head Mapper and Head Admin has requested the temporary removal of Project Theta/Orion as such I am putting this PR on a DNM until they can give their official verdict.

2018-06-16 01:39 UTC, DoctorOctopusTheOctopi commented
After a consult with @BDpuffy420 and understanding on why our Head Boy asked for its removal, I'm removing the DNM Tag. I'll throw up my personal review later and give @Desolane or @caelaislinn a chance to reply too. To confirm that the nerfs/everything is to their standards/what they want.

2018-06-16 01:43 UTC, lngredients commented
Oh, last Desolane had told me was to work on Project Orion... Well alright.

2018-06-16 02:39 UTC, lngredients commented
CI seems to have passed. Let me know if the Armor values are too much still.

2018-06-16 02:40 UTC, lngredients commented
I tried to stick to the Lore as much as possible, for instance the wiki said that the equipment given to the Orion Project was largely unknown except for the M99 sniper. So I made the M98 a carbine for use with the project.

2018-06-16 02:52 UTC, lngredients commented
Oh, also I will have to add in the Orion Code Envelope to the UNSC frigate CO quarters and probably the bridge if this does get merged which will be a small addition. It is the other half of the Orion Project Envelope so that the Researcher gives the code phrase to allow for Project Orion to be allowed on board the frigate with some independence.

2018-06-16 10:57 UTC, Flaksim commented
Can I see a screenshot? Of where you added it that is

2018-06-16 19:27 UTC, lngredients commented
https://gyazo.com/2af68ab531541f93899721140c90aa1f

2018-06-16 19:29 UTC, lngredients commented
Large view
https://gyazo.com/49f8f454eaa28409b836fff2ec3428d4

2018-06-16 20:08 UTC, lngredients commented
Not sure what's going on with the desert outpost CI check now

2018-06-16 21:03 UTC, lngredients commented
Uh... well it seems to be working now so GG.

2018-06-16 23:39 UTC, DoctorOctopusTheOctopi commented
That is a large open space for the lab. Is there any way you could shrink it or fill it with something? It'll look extremely empty in live.

2018-06-17 00:47 UTC, lngredients commented
Yeah I will see about filling it wit some other things. I'm a big fan of large open surgery rooms, often things are crammed so tightly together.

2018-06-17 08:36 UTC, lngredients commented
https://gyazo.com/bc6735dfc0382d0a1e38431bfca107fd

2018-06-17 22:30 UTC, caelaislinn requested changes
Code changes look fine. Some minor tweaks requested

2018-06-17 22:30 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +	We are expecting great results from this project as it's succesful implementation will immensely bolster our military assets on the ground, when you are done reading this document be sure to burn it
*successful

2018-06-17 22:30 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +	'Omega-Romeo-India-Oscar-November'.<br><br>\
This should be randomised in the code like traitor secret phrases

2018-06-17 22:30 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +	'Omega-Romeo-India-Oscar-November'<br><br>\
Randomised code phrase

2018-06-17 22:30 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +	<i>I.N.G.</i></tt>")
Whats I.N.G. ?

2018-06-17 22:32 UTC, Flaksim commented
I have performed an extensive remap of exoplanet research in my PR with this change in mind, merge this PR first, then merge mine to ensure the map is up to date.

2018-06-17 22:58 UTC, lngredients commented on code/game/machinery/nuclear_bomb.dm
> +	'Omega-Romeo-India-Oscar-November'.<br><br>\
Oooh? How do I pull that off, I will look at traitor code!

2018-06-17 23:00 UTC, lngredients commented on code/game/machinery/nuclear_bomb.dm
> +	<i>I.N.G.</i></tt>")
It's just an Easter egg for part of my Byond Key and it sort of looks official also. *cute face*

2018-06-20 03:34 UTC, closed without merging