Project Orion
HaloSpaceStation/HaloSpaceStation13 pull request #698
Opened 2018-06-21 04:31 UTC by lngredients

Changed Theta project names to Project Orion for guns and armor.

Armor thickness is now only on helmet and armor pieces. Undersuit no longer provides armor values. All armor values were decreased so that max is 65 on main armor piece.

Added in Orion Project Race called "Orion" which Admins will have to manually set once proper RP is done ICly to create project Orion. Added in armor race restrictions so it can only be worn once race is set.

Changed Theta Project .DM file name to Orion Project. Changed Project Theta evelope to reflect Project Orion's needs.

Removed the RD closet containing the Theta Project Envelope. Replaced Blank Envelopes in Exo-Research 1 with Project Orion Envelopes

Changed MA3 custom gun to custom MA9 icon.

Added in Chemistry station to Exo3

Swapped around surgery kits and IV drips. Added in sinks to surgery.

Deleted prototype SMGs from shooting range. Added in three ammobags for Orion project.

Replaced blank Envelope with Orion Project Envelope. Added in cargo racks with useful things in the chemistry hallway

Replaced Orion equipment tables with Three separate closets.

2018-06-21 09:35 UTC, Flaksim commented
This check fails because of: code/_helpers/global_access.dm but this file doesnt seem to be changed in this PR...

2018-06-21 09:55 UTC, lngredients commented
Thanks I'll see if I can replace it.

2018-06-21 10:25 UTC, lngredients commented
I've replaced the code with the code/_helpers/global_access.dm from the HaloSpaceStation13/HaloSpaceStation13 files and is doesn't seem to help.

2018-06-21 10:47 UTC, Flaksim commented
I'm thinking this is a natural result of some of the changes, and the travis check is made to not allow any changes in that fashion.... In that case this isnt a problem, but I'd like a coder to give input, because I'm just guessing at this point.

2018-06-21 22:18 UTC, caelaislinn commented
The "check globals unchanged" unit test doesn't actually check global_access.dm it checks all global variables in the entire project. If you add or remove a global variable to any file anywhere without updating the checksum it will fail

2018-06-21 22:19 UTC, caelaislinn commented
I think we'll need to add a test skip for the map images unit test as we're not using the minimap

2018-06-21 22:50 UTC, lngredients commented
I don't think I added a global variable

2018-06-21 22:57 UTC, lngredients commented
Well I suppose let me know what I can do to help.

2018-06-21 23:00 UTC, caelaislinn requested changes
Run gen_globals.py

2018-06-21 23:00 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +var/get_orion_password = null
Top level variables are always globals, even if not explicitly set as such.

2018-06-21 23:01 UTC, lngredients commented on code/game/machinery/nuclear_bomb.dm
> +var/get_orion_password = null
I see, hmm.

2018-06-21 23:03 UTC, lngredients commented on code/game/machinery/nuclear_bomb.dm
> +var/get_orion_password = null
And how do you update the checksum?

2018-06-21 23:08 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +var/get_orion_password = null
This also should be changed to something like var/global/orion_password = null

2018-06-22 02:27 UTC, bloxgate submitted a review, later dismissed

2018-06-22 02:27 UTC, bloxgate commented on tools/GenerateGlobalVarAccess/generateGlobalVars.bat
> +call "C:\Users\Harishini's PC\AppData\Local\Programs\Python\Python36-32\python.exe" gen_globals.py ../../baystation12.dme ../../code/_helpers/global_access.dm
No. Don't merge this. This change needs to be reverted ASAP.

2018-06-22 02:28 UTC, lngredients commented on tools/GenerateGlobalVarAccess/generateGlobalVars.bat
> +call "C:\Users\Harishini's PC\AppData\Local\Programs\Python\Python36-32\python.exe" gen_globals.py ../../baystation12.dme ../../code/_helpers/global_access.dm
What? I was told to change the path?

2018-06-22 03:20 UTC, lngredients commented
It is done!

2018-06-23 06:47 UTC, caelaislinn requested changes

2018-06-23 06:47 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +	if (get_orion_password)
procs and vars should never have the same name

2018-06-23 20:39 UTC, lngredients commented
It is done again!

2018-06-23 21:08 UTC, BDpuffy420 approved these changes
Travis is failing due to map image on Geminus  other than that it’s good, I’ll wait for Cael’s final say

2018-06-24 00:26 UTC, caelaislinn requested changes

2018-06-24 00:26 UTC, caelaislinn commented on code/_helpers/global_access.dm
> +		if("get_orion_password")
These are  now incorrect so you'll need to update them manually or run gen_globals.py

2018-06-24 00:26 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +		return orion_password
Good

2018-06-24 00:26 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +	return name
Have you tested it to work?

2018-06-24 00:26 UTC, caelaislinn commented on html/changelogs/Ingredients Orion Project 20 June.yml
> +  - tweak: "Added three Orion Code envelopes to frigate bridge and CO quarters."
Cut down the number of entries here please

2018-06-24 04:03 UTC, lngredients commented on html/changelogs/Ingredients Orion Project 20 June.yml
> +  - tweak: "Added three Orion Code envelopes to frigate bridge and CO quarters."
I minimized it, but I figured it would be nice to have a record of all the changes I am doing, eh?

2018-06-24 04:03 UTC, lngredients commented
Pass code works, stairs work, Armor is restricted, it's looking better.

2018-06-24 04:04 UTC, lngredients commented
It has also been thoroughly tested.

2018-06-24 04:05 UTC, caelaislinn commented on html/changelogs/Ingredients Orion Project 20 June.yml
> +  - tweak: "Added three Orion Code envelopes to frigate bridge and CO quarters."
Git is the record of the changes, the changelog is just what we communicate to the players. That kind of communication is best concise and relevant

2018-06-24 04:09 UTC, caelaislinn requested changes

2018-06-24 04:09 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +var/global/orion_password = get_orion_password()
This won't work. It needs to start at null then you assign it in the first call of get_orion_password()

2018-06-24 04:09 UTC, caelaislinn commented on html/changelogs/Ingredients Orion Project 20 June.yml
> +  - tweak: "Added three Orion Code envelopes to frigate bridge and CO quarters."
I think the changes are still too verbose. You don't need to mention every tiny change, just a loose summary is fine.

2018-06-24 04:09 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +
Add a line here orion_password = name so that it saves

2018-06-24 04:13 UTC, lngredients commented on code/game/machinery/nuclear_bomb.dm
> +var/global/orion_password = get_orion_password()
I am on my third test of this now and it appears to work.

2018-06-24 04:14 UTC, lngredients commented on code/game/machinery/nuclear_bomb.dm
> +
I'll try this instead and see if it works.

2018-06-24 04:25 UTC, caelaislinn commented on code/game/machinery/nuclear_bomb.dm
> +var/global/orion_password = get_orion_password()
Uhh... get_orion_password() is a global proc so I guess that works then. Fucking byond you can get away with doing so much silly stuff. It's a terrible language to learn coding on because you'll get into so many bad habits XD

2018-06-24 04:39 UTC, lngredients commented on code/game/machinery/nuclear_bomb.dm
> +var/global/orion_password = get_orion_password()
I changed it to your suggestion since that also seems to work.

2018-06-24 05:50 UTC, lngredients commented
Let me know if this is good to go now.

2018-06-24 05:57 UTC, caelaislinn requested changes

2018-06-24 05:57 UTC, caelaislinn commented on code/_helpers/global_access.dm
> +		if("get_orion_password")
This still needs to be updated

2018-06-24 05:57 UTC, caelaislinn commented on code/_helpers/global_access.dm
> +		if("get_orion_password")
And this one

2018-06-24 05:57 UTC, caelaislinn commented on code/_helpers/global_access.dm
> +	"get_orion_password",
And this one

2018-06-24 05:57 UTC, caelaislinn commented on html/changelogs/Ingredients Orion Project 20 June.yml
> +  - tweak: "Added in Chemistry station to Exo3."
maptweak

2018-06-24 05:57 UTC, caelaislinn commented on html/changelogs/Ingredients Orion Project 20 June.yml
> +  - tweak: "Added a modded Icon, MA9 gun into Weapon sprites.dm, changed the Orion Project Icon gun to use the MA9. Changed weight class from huge to large."
imageadd

2018-06-24 05:57 UTC, caelaislinn commented on html/changelogs/Ingredients Orion Project 20 June.yml
> +  - tweak: "Changed Theta Project .DM file name to Orion Project. Changed Project Theta evelope to reflect Project Orion's needs."
Redundant entry

2018-06-24 05:57 UTC, caelaislinn commented on html/changelogs/Ingredients Orion Project 20 June.yml
> +  - tweak: "Removed random project theta Labratory hidden in rocks of Exo-research 2. Removed old project theta lab in Gem City RnD"
maptweak

2018-06-25 12:12 UTC, Flaksim commented
Looks like this is good to go?

2018-06-25 12:18 UTC, caelaislinn approved these changes

2018-06-25 20:42 UTC, merged