Small ONI base fixes
HaloSpaceStation/HaloSpaceStation13 pull request #710
Opened 2018-07-05 01:49 UTC by erty80s

-The fences outside the base no longer have weird collision issues and should work as intended

-Fixed the issue where the mech parts didn't stick to the chasis and the torso spawned invisible.

2018-07-06 03:09 UTC, BDpuffy420 submitted a review, later dismissed

2018-07-07 02:03 UTC, bloxgate requested changes
Map contains step_x and step_y, movement code will break if merged.

2018-07-07 02:03 UTC, bloxgate commented on maps/Exoplanet Research/ExoResearch_1.dmm
> +"cR" = (/obj/structure/electric_fence/ns{bound_height = 96; step_x = 0; step_y = 0},/turf/simulated/floor/exoplanet/desert,/area/exo_research_facility/outer)
Both step_x and step_y need to be removed here.

2018-07-07 02:03 UTC, bloxgate commented on maps/Exoplanet Research/ExoResearch_1.dmm
> +"fB" = (/obj/structure/electric_fence/ns{bound_height = 96; step_x = 0; step_y = 0},/turf/simulated/floor/exoplanet/desert,/area/exo_research_facility{base_turf = /turf/simulated/floor/exoplanet/dese
And again

2018-07-07 15:53 UTC, Flaksim commented
Hold on, why is exoresearch_1 deleted? Shit like that can break our entire load order with the flaky things we have in to link maps.

2018-07-10 07:45 UTC, erty80s commented
hmm it still seems to fail the travis check, anyone know why?

2018-07-10 16:48 UTC, BDpuffy420 commented
It passed , it’s just Blox’s review

2018-07-11 23:07 UTC, bloxgate approved these changes

2018-07-11 23:07 UTC, bloxgate commented
Whoops, sorry about the delay. LGTM.

2018-07-11 23:22 UTC, erty80s commented
Yes, basically what happened was that I made a copy of exoresearch and placed it in the wrong folder. Anyways, everything should be in order and ready to go.

2018-07-12 03:20 UTC, merged