New Floorsigns
HaloSpaceStation/HaloSpaceStation13 pull request #720
Opened 2018-07-12 08:53 UTC by lngredients

Mostly for medbay. Useful?

2018-07-12 23:22 UTC, bloxgate commented
Why does this remove all your previous changelogs?

2018-07-15 21:26 UTC, caelaislinn requested changes
Restore the missing changelogs please

2018-07-16 02:28 UTC, lngredients commented
Added them back in.

2018-07-16 02:31 UTC, lngredients commented
That should do it.

2018-07-16 05:52 UTC, caelaislinn submitted a review, later dismissed

2018-07-16 05:52 UTC, caelaislinn commented on html/changelogs/Ingredients New Floor signs 12 July.yml
> +  - imageadd: "New floorsigns for medical."
By the looks of it you have still deleted a changelog file "Ingredients URF Ship Items and New Innie Armors 30 June.yml"

2018-07-17 19:07 UTC, lngredients commented on html/changelogs/Ingredients New Floor signs 12 July.yml
> +  - imageadd: "New floorsigns for medical."
Found it and added it in.

2018-07-19 19:22 UTC, BDpuffy420 approved these changes

2018-07-19 19:27 UTC, merged