Various fixes, folder redesign
HaloSpaceStation/HaloSpaceStation13 pull request #722
Opened 2018-07-12 22:45 UTC by Flaksim

changes: 
  - maptweak: "Fixed gravity and power issues on Geminus (Someone forgot areas when mapping new things in...)"
  - rscdel: "Cleaned up map folders to get rid of outdated and horribly broken maps."
  - bugfix: "Implemented XO-11's movement fix."
  - tweak: "Rounded out items here and there, nothing major, this update is mostly fixing little things and step 1 in src reorganization."

2018-07-12 23:03 UTC, Flaksim commented
The maps fail because the dmb is setup for FC mode, not for geminus, files it needs for those maps arent included in that load order, its not because something is wrong with them.

2018-07-12 23:19 UTC, bloxgate commented
You'll need to fix that. Including the map/gamemode's code file should include everything the map needs to run, and not stuff from other modes/maps.

2018-07-12 23:28 UTC, Flaksim commented
Yeah, that map is actually gone, removed it from the includes file now.

As for including everything. Its either loading a shitton of extra files, or a couple of months rebuilding the shit pile people who came before made of it, too many items that are needed over different maps and gamemodes were put in specific subfolders or made dependent on files exclusive to another map/gamemode.

2018-07-12 23:33 UTC, bloxgate commented
Personally, I'd prefer if the code we have on alpha passes all Travis test. Having people get used to it failing will eventually cause an actual problem to get ignored at some point.

We may have to just bit the bullet and fix our horrible include situation. I'd put that more on the order of a few hours of serious work, rather than a month though.

2018-07-14 07:21 UTC, erty80s commented on maps/first_contact/maps/UNSC_Corvette.dmm
> +"am" = (/obj/structure/sink{dir = 1; pixel_y = 16},/obj/structure/mirror{pixel_x = 0; pixel_y = 30},/turf/simulated/floor/tiled/freezer,/area/om_ships/unscpatrol/captainroom)
This pixel_x and pixel_y might be why it doesnt pass the travis check. Correct me if I'm wrong

2018-07-14 18:19 UTC, Flaksim commented on maps/first_contact/maps/UNSC_Corvette.dmm
> +"am" = (/obj/structure/sink{dir = 1; pixel_y = 16},/obj/structure/mirror{pixel_x = 0; pixel_y = 30},/turf/simulated/floor/tiled/freezer,/area/om_ships/unscpatrol/captainroom)
pixel_x and Y are intended to be used, what you CANNOT use is step_x and y

2018-07-15 03:59 UTC, bloxgate reviewed
Yeah looks good. Just have one small question about the change to the example map though.

2018-07-15 03:59 UTC, bloxgate commented on maps/example/example_define.dm
> +	allowed_spawns = list("Test Spawn")
Reason for changing this?

2018-07-15 04:14 UTC, Flaksim commented on maps/example/example_define.dm
> +	allowed_spawns = list("Test Spawn")
turned it into a localised test contained to the examples file
the way it did spawns on the file it was using to test wasnt even the same as the way we do spawns, so it was a pretty useless test for our purposes.

2018-07-15 05:48 UTC, Desolane approved these changes
I give it a semi golden ticket of approval, albeit the light for the helmet buff irks me and the area code has some redundancy, otherwise, keep up the trend of adding armor thickness to helmets and we'll see how it effects gameplay before opting to remove it.

2018-07-15 21:42 UTC, caelaislinn requested changes
Requesting some tweaks and clarifications

2018-07-15 21:42 UTC, caelaislinn commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	item_state = null
I'd like to keep halo items in the modules folder for preference

2018-07-15 21:42 UTC, caelaislinn commented on code/modules/clothing/suits/storage.dm
>  	pockets = new/obj/item/weapon/storage/internal/pockets(src, slots = 4, slot_size = 2)
Unnecessary line changes

2018-07-15 21:42 UTC, caelaislinn commented on code/modules/halo/clothing/odst.dm
> +	..()
This is redundant

2018-07-15 21:42 UTC, caelaislinn commented on code/modules/halo/structures/diesel_gen.dm
> -	name = name + " #[rand(0,9)]"
This would be better done as a static var  counting the number of instances

2018-07-15 21:42 UTC, caelaislinn commented on code/modules/halo/structures/diesel_gen.dm
> -	slot_flags = null	//they have no straps!
Why was this entire file cleared? I can't see if its re-added

2018-07-15 22:16 UTC, Flaksim commented on code/modules/halo/clothing/odst.dm
> +	..()
A leftover from an attempt to make integrated oxytanks, the next pr i'm working on deals mainly with that file and removes redundant stuff like that.

2018-07-15 22:17 UTC, Flaksim commented on code/modules/halo/structures/diesel_gen.dm
> -	name = name + " #[rand(0,9)]"
Diesel gens are gone. the file was removed.

2018-07-15 22:17 UTC, Flaksim commented on code/modules/halo/structures/diesel_gen.dm
> -	slot_flags = null	//they have no straps!
Diesel gens are gone. the file was removed. Its unused and I was asked to clear out some stuff we wouldnt need.

2018-07-15 22:18 UTC, Flaksim commented on code/modules/clothing/suits/storage.dm
>  	pockets = new/obj/item/weapon/storage/internal/pockets(src, slots = 4, slot_size = 2)
Indeed, its because something was tried before, and I undid it again.

2018-07-15 22:18 UTC, Flaksim commented on code/game/objects/items/weapons/tanks/tank_types.dm
> +	item_state = null
This is in progress, its being worked on, but It will be removed from that file in the next PR.

2018-07-16 05:55 UTC, caelaislinn commented on code/modules/halo/structures/diesel_gen.dm
> -	name = name + " #[rand(0,9)]"
Just a thought for if they come back.

2018-07-16 05:56 UTC, caelaislinn commented on code/modules/halo/structures/diesel_gen.dm
> -	slot_flags = null	//they have no straps!
Our only problem is with having too many zlevels and map files. This kind of content isn't a problem at all.

2018-07-16 11:21 UTC, Flaksim commented on code/modules/halo/structures/diesel_gen.dm
> -	slot_flags = null	//they have no straps!
The mapfiles will be shrunk in the next PR aswell, there are several that can go imo, but for insurrection for example, the new map isnt fully compatible with the mode yet, I'm in the process of doing that, then the old ones can go. All those maps will be moved to a "map archive" folder, and just unused untill/IF we want to revisit them.

As for all the Z levels and mapfiles being used: FC and Geminus modes individually dont have too many Z levels, but we've been running on a "mode" that just throws all the FC maps into Geminus, which is a bad idea.
Will take that up in staff to see what we will and wont include in Geminus.

2018-07-17 22:41 UTC, Flaksim commented
Its done for the moment, merge this, makes the game playable again ;)

2018-07-17 23:18 UTC, caelaislinn commented on code/modules/halo/structures/diesel_gen.dm
> -	slot_flags = null	//they have no straps!
My point was that code like this can stay around until we start using it.

2018-07-17 23:30 UTC, caelaislinn approved these changes

2018-07-18 18:29 UTC, merged