Changed Orions to not be a subset of humans so they can wear their armor
HaloSpaceStation/HaloSpaceStation13 pull request #725
Opened 2018-07-20 03:40 UTC by lngredients

Made Orions their own separate race and not a subset
Deleted a spare set of undersuits inside the closets.

2018-07-20 03:49 UTC, lngredients commented
When tested with the new Orion species path they were capable of wearing their clothing.

2018-07-20 20:46 UTC, lngredients commented
God damn Mob runtimes...

2018-07-20 21:42 UTC, lngredients commented
Tell me if this is mergeable.

2018-07-20 23:40 UTC, bloxgate requested changes
There aren't merge conflicts exactly, however there does seem to be a problem with whatever you did to ExoResearch-3

2018-07-20 23:40 UTC, bloxgate commented on code/modules/mob/living/carbon/human/species/station/orion.dm
> +	unarmed_types = list(/datum/unarmed_attack/orionpunch, /datum/unarmed_attack/orionkick, /datum/unarmed_attack, /datum/unarmed_attack/bite)
I'm not the most familiar with the unarmed attack code, but are we sure having the *base* unarmed attack here is ok?

2018-07-20 23:40 UTC, bloxgate commented on code/modules/mob/living/carbon/human/species/station/orion.dm
> +	spawn_flags = SPECIES_IS_WHITELISTED
Did you check with staff that this is being moved to a whitelist role?

2018-07-20 23:40 UTC, bloxgate commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +<<<<<<< HEAD:maps/Exoplanet Research/ExoResearch_3.dmm
This is broken. You did something very wrong when fixing merge conflicts.

2018-07-20 23:40 UTC, bloxgate commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +"du" = (/obj/structure/bed/chair/office/dark{dir = 1},/turf/simulated/floor/tiled/dark,/area/exo_research_facility
Ditto.

2018-07-20 23:40 UTC, bloxgate commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +>>>>>>> alpha:maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
And again

2018-07-20 23:41 UTC, bloxgate commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +"du" = (/obj/structure/bed/chair/office/dark{dir = 1},/turf/simulated/floor/tiled/dark,/area/exo_research_facility
Uh whoops, this one should've been one line lower.

2018-07-21 02:32 UTC, lngredients commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +>>>>>>> alpha:maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
What now? Why is that a line above where it should be? I didn't mess with it

2018-07-21 02:34 UTC, lngredients commented on code/modules/mob/living/carbon/human/species/station/orion.dm
> +	spawn_flags = SPECIES_IS_WHITELISTED
No I didn't I suppose it can stay as restricted. The idea is that people wouldn't be able to become it unless admins made someone an Orion, similar to how spartans work.

2018-07-21 02:35 UTC, lngredients commented on code/modules/mob/living/carbon/human/species/station/orion.dm
> +	unarmed_types = list(/datum/unarmed_attack/orionpunch, /datum/unarmed_attack/orionkick, /datum/unarmed_attack, /datum/unarmed_attack/bite)
The base unarmed attack there should be alright, it's already a part of every normal mobs attack routine who don't have custom attack codes, but I put it in there to make sure it would cycle through them in case listing only the custom attack codes would take out the defaults.

2018-07-21 02:36 UTC, lngredients commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +<<<<<<< HEAD:maps/Exoplanet Research/ExoResearch_3.dmm
The only thing I did to exo research 3 is remove three extra pairs of Orion suits from the lockers that I noticed? What is fucked up?

2018-07-21 02:36 UTC, bloxgate commented on code/modules/mob/living/carbon/human/species/station/orion.dm
> +	spawn_flags = SPECIES_IS_WHITELISTED
I'm fairly sure that that is what restricted is. But ask @Desolane what he wants.

2018-07-21 02:38 UTC, bloxgate commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +>>>>>>> alpha:maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
That's not what I said. You messed up resolving a merge conflict here.

2018-07-21 02:40 UTC, lngredients reviewed
Hmm... hmm... if it's that messed up I will see about just closing this PR and rebasing completely. And redoing the changes since they are all pretty minor.

2018-07-21 02:40 UTC, lngredients commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +<<<<<<< HEAD:maps/Exoplanet Research/ExoResearch_3.dmm
And I didn't technically fix any merge conflicts, I just merged the Origin Alpha branch into my local Alpha branch, then merged my local Alpha into my Orion branch.

2018-07-21 02:40 UTC, bloxgate commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +<<<<<<< HEAD:maps/Exoplanet Research/ExoResearch_3.dmm
This was broken in commit c604e36, which is one of yours. It looks like you made a mistake when pulling new changes in.

2018-07-21 02:42 UTC, lngredients commented on maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm
> +<<<<<<< HEAD:maps/Exoplanet Research/ExoResearch_3.dmm
Oh dear... Alright I thought merging the Origin into my alpha when new updates from other people were added would be alright.

2018-07-21 03:04 UTC, lngredients commented on code/modules/mob/living/carbon/human/species/station/orion.dm
> +	unarmed_types = list(/datum/unarmed_attack/orionpunch, /datum/unarmed_attack/orionkick, /datum/unarmed_attack, /datum/unarmed_attack/bite)
I'll probably just take out any attack code

2018-07-21 03:13 UTC, closed without merging