Created two other suit colors to help differentiate Orion Armor wearers
HaloSpaceStation/HaloSpaceStation13 pull request #803
Opened 2018-09-10 07:02 UTC by lngredients

There is now red, blue, and green orion armors

2018-09-10 07:03 UTC, lngredients commented
Hopefully they don't look dumb

2018-09-10 21:44 UTC, caelaislinn requested changes

2018-09-10 21:44 UTC, caelaislinn commented on code/modules/halo/misc/Orion Project.dm
> +/obj/item/clothing/suit/space/void/swat/thetar
Changing these file paths breaks the geminus city map... you'll need to either update the file paths in the map or add the coloured variants as a different path (preferably a subclass)

2018-09-11 00:27 UTC, lngredients commented on code/modules/halo/misc/Orion Project.dm
> +/obj/item/clothing/suit/space/void/swat/thetar
I don't know why there is theta armor in gemcity in the first place, I'll look into it.

2018-09-11 00:28 UTC, caelaislinn commented on code/modules/halo/misc/Orion Project.dm
> +/obj/item/clothing/suit/space/void/swat/thetar
Weren't you the one who added it?

2018-09-28 00:23 UTC, closed without merging

2018-09-29 00:00 UTC, lngredients commented on code/modules/halo/misc/Orion Project.dm
> +/obj/item/clothing/suit/space/void/swat/thetar
No, I didn't add the theta armor in gemcity, it should have been removed in fact.