Exo research changes
HaloSpaceStation/HaloSpaceStation13 pull request #840
Opened 2018-09-29 03:12 UTC by lngredients

Read Changelog for general changes, read specific commits for more details.

2018-09-29 03:17 UTC, caelaislinn requested changes
Changelog entry doesn't have your name

2018-09-29 03:17 UTC, caelaislinn commented on html/changelogs/Changelog Ingredients ONI Changes.yml
> +author: Unknown
This needs to have your name in it

2018-09-29 03:18 UTC, caelaislinn commented
Also try to leave commits until you are completely finished... 9 commits for only 4 files changed is a bit messy

2018-09-29 03:19 UTC, lngredients commented on html/changelogs/Changelog Ingredients ONI Changes.yml
> +author: Unknown
Will do, and I thought it would make it easier to tell what changes I made if I split it up like that, I suppose I won't next time.

2018-09-29 03:20 UTC, caelaislinn commented on html/changelogs/Changelog Ingredients ONI Changes.yml
> +author: Unknown
Oh those commits are map changesets... yeah that's fine

2018-09-29 03:21 UTC, caelaislinn approved these changes

2018-09-29 03:33 UTC, lngredients commented on html/changelogs/Changelog Ingredients ONI Changes.yml
> +author: Unknown
For the briefcases I don't think I can change their amount without editing their variables.  I think those are the only map changesets I made if I am understanding that term correctly.

2018-09-29 03:35 UTC, lngredients commented on html/changelogs/Changelog Ingredients ONI Changes.yml
> +author: Unknown
Actually, I take that back, I did have to edit access variables.

2018-09-29 13:42 UTC, BDpuffy420 requested changes
maps/first_contact/maps/Exoplanet Research/ExoResearch_3.dmm

2018-09-30 23:56 UTC, lngredients commented
BD what do you want changed exactly, I don't understand.

2018-10-01 02:06 UTC, closed without merging