Spartan Laser <DO NOT MERGE>
HaloSpaceStation/HaloSpaceStation13 pull request #972
Opened 2018-12-08 01:36 UTC by Stingray540

Essentially, adding this PR in order to get help/comments.

-Correctly links the Spartan Laser to the sprite already present in the files
-Adds a variable for if a weapon needs to be "charged", defaulted to 0 for everything aside from/charged weapons
-Adds a delay to firing the Spartan Laser, as previously at was instant fire. The sound for firing is linked to the charge, however, I'm currently trying to cause the do_after to be triggered at the same time as the charge/fire sound.

Most of this is likely incomplete and inefficient as I'm very new to this, so please give any tips you can think of. Thanks!

2018-12-08 06:35 UTC, caelaislinn requested changes
Ignore the travis failure. This may be good to merge, but I'd like to manually test it first

2018-12-08 06:35 UTC, caelaislinn commented on code/modules/halo/weapons/projectiles/beams.dm
> +	damage = 200
This could potentially be boosted. We don't have a unified way of handling vehicles but 200 is around the max HP of mobs which means there's a small chance of survival if being hit

2018-12-08 06:35 UTC, caelaislinn commented on code/modules/projectiles/gun.dm
> +
Unnecesary line change

2018-12-08 06:35 UTC, caelaislinn commented on code/modules/projectiles/gun.dm
> +		playsound(src.loc, charge_sound, 100, 1)
This will play the firing sound I believe?

2018-12-08 06:35 UTC, caelaislinn commented on code/modules/projectiles/gun.dm
> +	var/arm_time = 2.5 //Default charge time for weapons that charge
Time in byond is measured in deciseconds, so this will amount to 1/4 of a second. To make it 2.5 seconds you should either set this value to 25 or you could go var/arm_time = 2.5 SECONDS

SECONDS is a macro which automatically converts a value from deciseconds to seconds by multiplying it by 10

2018-12-08 12:55 UTC, Stingray540 commented on code/modules/projectiles/gun.dm
> +		playsound(src.loc, charge_sound, 100, 1)
Yes. Currently, it'll play the charging/firing sound (which is one .ogg). Is it possible for me to cause the .ogg to stop playing if the do_after fails, or will I have to split the actual laser firing sound and the laser charging sound into two in order to prevent it triggering even when not actually fired?

2018-12-08 13:41 UTC, Stingray540 commented on code/modules/projectiles/gun.dm
> +		playsound(src.loc, charge_sound, 100, 1)
As of the latest commit, I'd say I've got three main things to sort:

-Cause the charging sound to stop when charging fails rather than still play the entire .ogg

-Add some kind of tracer during the charging phase to alert enemies due to its strength. No idea how to do this. Not required, but unless it stays admin-spawn forever will likely be needed for balance.

-Get a l/r hand sprite for the weapon. I'm not a spriter so I can't do this, but I guess I'll try and lean if I complete everything else.

Thanks for all the help so far.

2018-12-08 15:47 UTC, Delnth commented
There is an item in the code that's called >Infrared emitter.

This item allows an option to render the infrared beam visible or not. You might want to check it out and work from there. It has a distance limit, though.

2018-12-11 09:22 UTC, Stingray540 commented
As of the latest commit, I have two more main goals, one of which I'm not entirely sure I can complete on my own after multiple attempts (at my beginner level of coding for SS13).

-Add the IR beam effect to the spartan laser while it is charging. I've messed around with this a bunch and can't quite figure it out. This isn't strictly an essential feature, but for balance it is. (The instadeath beam needs *some* tells, after all). If any actual developers would be willing to either 'handhold' me through it so I learn, or take over for this feature, I'd be very grateful.

-Make the 'charging' part of the sound stop once the charging do_after is stopped. The most recent commit prevents the 'beam' sound from playing by splitting the file in two, but if possible I'd still like it to stop the .ogg entirely, as currently, it will still play the entire charging sound even if, say, it is cancelled as soon as it begins. Not even sure if .ogg can be stopped midway.

The weapon also needs l/r hand sprites. I'm not a spriter so I'm not considering this one of my personal goals, it could be merged without it, however.

Thank you for all the help so far.

2018-12-11 12:00 UTC, caelaislinn commented on code/modules/projectiles/gun.dm
> +		playsound(src.loc, charge_sound, 100, 1)
How long is the ogg? It is probably fine to just let it play out then only play the fire sound if the do_after is successful. You could probably modify or reuse the halo rocket launcher in hand sprite. 

A tracer for the laser while charging will need some finicking but its doable

2018-12-11 12:05 UTC, Stingray540 commented on code/modules/projectiles/gun.dm
> +		playsound(src.loc, charge_sound, 100, 1)
Currently the charge .ogg is around 3 seconds and the fire .ogg around 1, making the total around 4 when firing is successful. Your suggestion is essentially what I've done - the fire sound is added to the beam itself firing and the charge effect will play just before the do_after starts. (Being 3s long makes it match). And yeah, the tracers are going to be a pain for me. Some help with that would be great. Thanks again, Cael.

2018-12-11 16:40 UTC, Stingray540 commented
Edited this PR to include my armour changes - which adds sounds to spartan shield breaking and charging, along with thickness changes, bug fixes when spawning. Also spaceproofs the URFC armour

2018-12-11 23:42 UTC, BDpuffy420 approved these changes

2018-12-11 23:43 UTC, merged